# fortis_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

require_relative 'controller_test_base'

class Level3DataControllerTest < ControllerTestBase
  # Called only once for the class before any test has executed
  def setup
    setup_class
    @controller = @client.level_3_data
    @response_catcher = @controller.http_call_back
  end

  # Delete a single level3 record
  def test_delete_a_single_level3_record
    # Parameters for the API call
    transaction_id = '11e95f8ec39de8fbdb0a4f1a'
    level3_id = '11e95f8ec39de8fbdb0a4f1a'

    # Perform the API call through the SDK function
    result = @controller.delete_a_single_level3_record(transaction_id,
                                                       level3_id)

    # Test response code
    assert_equal(200, @response_catcher.response.status_code)
    # Test headers
    expected_headers = {}
    expected_headers['content-type'] = 'application/json; charset=utf-8'

    assert(ComparisonHelper.match_headers(expected_headers, @response_catcher.response.headers))

    # Test whether the captured response is as we expected
    refute_nil(result)
    expected_body = JSON.parse(
      '{"type":"TransactionLevel3","data":{"id":"11e95f8ec39de8fbdb0a4f1a","tr'\
      'ansaction_id":"11e95f8ec39de8fbdb0a4f1a","level3_data":{"destination_co'\
      'untry_code":"840","duty_amount":0,"freight_amount":0,"national_tax":2,"'\
      'sales_tax":200,"shipfrom_zip_code":"AZ1234","shipto_zip_code":"FL1234",'\
      '"tax_amount":10,"tax_exempt":"0","customer_vat_registration":"12345678"'\
      ',"merchant_vat_registration":"123456","order_date":"171006","summary_co'\
      'mmodity_code":"C1K2","tax_rate":0,"unique_vat_ref_number":"vat1234","li'\
      'ne_items":[{"description":"cool drink","commodity_code":"cc123456","dis'\
      'count_amount":0,"other_tax_amount":0,"product_code":"fanta123456","quan'\
      'tity":12,"tax_amount":4,"tax_rate":0,"unit_code":"gll","unit_cost":3,"a'\
      'lternate_tax_id":"1234","debit_credit":"C","discount_rate":11,"tax_type'\
      '_applied":"22","tax_type_id":"11"}]}}}'
    )
    received_body = JSON.parse(@response_catcher.response.raw_body)
    assert(ComparisonHelper.match_body(expected_body, received_body))
  end

  # View single level3 record
  def test_view_single_level3_record
    # Parameters for the API call
    transaction_id = '11e95f8ec39de8fbdb0a4f1a'
    level3_id = '11e95f8ec39de8fbdb0a4f1a'

    # Perform the API call through the SDK function
    result = @controller.view_single_level3_record(transaction_id, level3_id)

    # Test response code
    assert_equal(200, @response_catcher.response.status_code)
    # Test headers
    expected_headers = {}
    expected_headers['content-type'] = 'application/json; charset=utf-8'

    assert(ComparisonHelper.match_headers(expected_headers, @response_catcher.response.headers))

    # Test whether the captured response is as we expected
    refute_nil(result)
    expected_body = JSON.parse(
      '{"type":"TransactionLevel3","data":{"id":"11e95f8ec39de8fbdb0a4f1a","tr'\
      'ansaction_id":"11e95f8ec39de8fbdb0a4f1a","level3_data":{"destination_co'\
      'untry_code":"840","duty_amount":0,"freight_amount":0,"national_tax":2,"'\
      'sales_tax":200,"shipfrom_zip_code":"AZ1234","shipto_zip_code":"FL1234",'\
      '"tax_amount":10,"tax_exempt":"0","customer_vat_registration":"12345678"'\
      ',"merchant_vat_registration":"123456","order_date":"171006","summary_co'\
      'mmodity_code":"C1K2","tax_rate":0,"unique_vat_ref_number":"vat1234","li'\
      'ne_items":[{"description":"cool drink","commodity_code":"cc123456","dis'\
      'count_amount":0,"other_tax_amount":0,"product_code":"fanta123456","quan'\
      'tity":12,"tax_amount":4,"tax_rate":0,"unit_code":"gll","unit_cost":3,"a'\
      'lternate_tax_id":"1234","debit_credit":"C","discount_rate":11,"tax_type'\
      '_applied":"22","tax_type_id":"11"}]}}}'
    )
    received_body = JSON.parse(@response_catcher.response.raw_body)
    assert(ComparisonHelper.match_body(expected_body, received_body))
  end

end