# fortis_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module FortisApi
  # AccountVaultCauLog Model.
  class AccountVaultCauLog < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Token CAU Log ID
    # @return [String]
    attr_accessor :id

    # Product Transaction ID
    # @return [String]
    attr_accessor :product_transaction_id

    # Token ID
    # @return [String]
    attr_accessor :account_vault_id

    # Created Time Stamp
    # @return [Integer]
    attr_accessor :created_ts

    # User ID Created the register
    # @return [String]
    attr_accessor :created_user_id

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['id'] = 'id'
      @_hash['product_transaction_id'] = 'product_transaction_id'
      @_hash['account_vault_id'] = 'account_vault_id'
      @_hash['created_ts'] = 'created_ts'
      @_hash['created_user_id'] = 'created_user_id'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        id
        product_transaction_id
        account_vault_id
        created_ts
        created_user_id
      ]
    end

    # An array for nullable fields
    def self.nullables
      %w[
        product_transaction_id
        account_vault_id
        created_ts
        created_user_id
      ]
    end

    def initialize(id: SKIP, product_transaction_id: SKIP,
                   account_vault_id: SKIP, created_ts: SKIP,
                   created_user_id: SKIP, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @id = id unless id == SKIP
      @product_transaction_id = product_transaction_id unless product_transaction_id == SKIP
      @account_vault_id = account_vault_id unless account_vault_id == SKIP
      @created_ts = created_ts unless created_ts == SKIP
      @created_user_id = created_user_id unless created_user_id == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      id = hash.key?('id') ? hash['id'] : SKIP
      product_transaction_id =
        hash.key?('product_transaction_id') ? hash['product_transaction_id'] : SKIP
      account_vault_id =
        hash.key?('account_vault_id') ? hash['account_vault_id'] : SKIP
      created_ts = hash.key?('created_ts') ? hash['created_ts'] : SKIP
      created_user_id =
        hash.key?('created_user_id') ? hash['created_user_id'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      AccountVaultCauLog.new(id: id,
                             product_transaction_id: product_transaction_id,
                             account_vault_id: account_vault_id,
                             created_ts: created_ts,
                             created_user_id: created_user_id,
                             additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} id: #{@id}, product_transaction_id: #{@product_transaction_id},"\
      " account_vault_id: #{@account_vault_id}, created_ts: #{@created_ts}, created_user_id:"\
      " #{@created_user_id}, additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} id: #{@id.inspect}, product_transaction_id:"\
      " #{@product_transaction_id.inspect}, account_vault_id: #{@account_vault_id.inspect},"\
      " created_ts: #{@created_ts.inspect}, created_user_id: #{@created_user_id.inspect},"\
      " additional_properties: #{@additional_properties}>"
    end
  end
end
