# fortis_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module FortisApi
  # Indication of whether a challenge is required for the transaction to be
  # authorised due to local/regional mandates or other variable. >Y - Challenge
  # is mandated > >N - Challenge is not mandated >
  class AcsChallengeMandated
    ACS_CHALLENGE_MANDATED = [
      # TODO: Write general description for Y
      Y = 'Y'.freeze,

      # TODO: Write general description for N
      N = 'N'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      true
    end

    def self.from_value(value, default_value = Y)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'y' then Y
      when 'n' then N
      else
        default_value
      end
    end
  end
end
