# fortis_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module FortisApi
  # Address
  class Address1 < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # City name
    # @return [String]
    attr_accessor :city

    # State name
    # @return [String]
    attr_accessor :state

    # Postal code
    # @return [String]
    attr_accessor :postal_code

    # An alpha 2 format country code of US or CA.
    # @return [CountryEnum]
    attr_accessor :country

    # Street
    # @return [String]
    attr_accessor :street

    # Street 2
    # @return [String]
    attr_accessor :street2

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['city'] = 'city'
      @_hash['state'] = 'state'
      @_hash['postal_code'] = 'postal_code'
      @_hash['country'] = 'country'
      @_hash['street'] = 'street'
      @_hash['street2'] = 'street2'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        city
        state
        postal_code
        country
        street
        street2
      ]
    end

    # An array for nullable fields
    def self.nullables
      %w[
        city
        state
        postal_code
        country
        street
        street2
      ]
    end

    def initialize(city = SKIP, state = SKIP, postal_code = SKIP,
                   country = SKIP, street = SKIP, street2 = SKIP,
                   additional_properties = {})
      # Add additional model properties to the instance.
      additional_properties.each do |_name, _value|
        instance_variable_set("@#{_name}", _value)
      end

      @city = city unless city == SKIP
      @state = state unless state == SKIP
      @postal_code = postal_code unless postal_code == SKIP
      @country = country unless country == SKIP
      @street = street unless street == SKIP
      @street2 = street2 unless street2 == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      city = hash.key?('city') ? hash['city'] : SKIP
      state = hash.key?('state') ? hash['state'] : SKIP
      postal_code = hash.key?('postal_code') ? hash['postal_code'] : SKIP
      country = hash.key?('country') ? hash['country'] : SKIP
      street = hash.key?('street') ? hash['street'] : SKIP
      street2 = hash.key?('street2') ? hash['street2'] : SKIP

      # Clean out expected properties from Hash.
      additional_properties = hash.reject { |k, _| names.value?(k) }

      # Create object from extracted values.
      Address1.new(city,
                   state,
                   postal_code,
                   country,
                   street,
                   street2,
                   additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} city: #{@city}, state: #{@state}, postal_code: #{@postal_code}, country:"\
      " #{@country}, street: #{@street}, street2: #{@street2}, additional_properties:"\
      " #{get_additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} city: #{@city.inspect}, state: #{@state.inspect}, postal_code:"\
      " #{@postal_code.inspect}, country: #{@country.inspect}, street: #{@street.inspect},"\
      " street2: #{@street2.inspect}, additional_properties: #{get_additional_properties}>"
    end
  end
end
