# fortis_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module FortisApi
  # Alert Type
  class AlertTypeEnum
    ALERT_TYPE_ENUM = [
      # TODO: Write general description for ENUM_0
      ENUM_0 = 0,

      # TODO: Write general description for ENUM_1
      ENUM_1 = 1,

      # TODO: Write general description for ENUM_2
      ENUM_2 = 2,

      # TODO: Write general description for ENUM_3
      ENUM_3 = 3,

      # TODO: Write general description for ENUM_4
      ENUM_4 = 4,

      # TODO: Write general description for ENUM_5
      ENUM_5 = 5
    ].freeze

    def self.validate(value)
      return false if value.nil?

      ALERT_TYPE_ENUM.include?(value)
    end

    def self.from_value(value, default_value = ENUM_0)
      return default_value if value.nil?

      str = value.to_s.strip
      if str.match?(/\A\d+\z/)
        num = str.to_i
        return num if ALERT_TYPE_ENUM.include?(num)

        return default_value
      end

      case str.downcase
      when 'enum_0' then ENUM_0
      when 'enum_1' then ENUM_1
      when 'enum_2' then ENUM_2
      when 'enum_3' then ENUM_3
      when 'enum_4' then ENUM_4
      when 'enum_5' then ENUM_5
      else
        default_value
      end
    end
  end
end
