# fortis_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module FortisApi
  # AllTag Model.
  class AllTag < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Location ID
    # @return [String]
    attr_accessor :location_id

    # Tag Title
    # @return [String]
    attr_accessor :title

    # Tag ID
    # @return [String]
    attr_accessor :id

    # Created Time Stamp
    # @return [Integer]
    attr_accessor :created_ts

    # Modified Time Stamp
    # @return [Integer]
    attr_accessor :modified_ts

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['location_id'] = 'location_id'
      @_hash['title'] = 'title'
      @_hash['id'] = 'id'
      @_hash['created_ts'] = 'created_ts'
      @_hash['modified_ts'] = 'modified_ts'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        location_id
        title
        id
        created_ts
        modified_ts
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(location_id = SKIP, title = SKIP, id = SKIP,
                   created_ts = SKIP, modified_ts = SKIP,
                   additional_properties = {})
      # Add additional model properties to the instance.
      additional_properties.each do |_name, _value|
        instance_variable_set("@#{_name}", _value)
      end

      @location_id = location_id unless location_id == SKIP
      @title = title unless title == SKIP
      @id = id unless id == SKIP
      @created_ts = created_ts unless created_ts == SKIP
      @modified_ts = modified_ts unless modified_ts == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      location_id = hash.key?('location_id') ? hash['location_id'] : SKIP
      title = hash.key?('title') ? hash['title'] : SKIP
      id = hash.key?('id') ? hash['id'] : SKIP
      created_ts = hash.key?('created_ts') ? hash['created_ts'] : SKIP
      modified_ts = hash.key?('modified_ts') ? hash['modified_ts'] : SKIP

      # Clean out expected properties from Hash.
      additional_properties = hash.reject { |k, _| names.value?(k) }

      # Create object from extracted values.
      AllTag.new(location_id,
                 title,
                 id,
                 created_ts,
                 modified_ts,
                 additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} location_id: #{@location_id}, title: #{@title}, id: #{@id}, created_ts:"\
      " #{@created_ts}, modified_ts: #{@modified_ts}, additional_properties:"\
      " #{get_additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} location_id: #{@location_id.inspect}, title: #{@title.inspect}, id:"\
      " #{@id.inspect}, created_ts: #{@created_ts.inspect}, modified_ts: #{@modified_ts.inspect},"\
      " additional_properties: #{get_additional_properties}>"
    end
  end
end
