# fortis_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module FortisApi
  # Array of bank account objects. >One account with “deposit_type” of primary
  # is required. Maximum of two accounts are allowed. >
  class BankAccount1 < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Account holder name.
    # @return [String]
    attr_accessor :account_holder_name

    # Nine-digit Bank routing number.
    # @return [String]
    attr_accessor :routing_number

    # Account number.
    # @return [String]
    attr_accessor :account_number

    # Flag indicating whether or not the account is the primary account. Only
    # one account can be marked as primary.
    # >Indicates that the account should be the primary account for the
    # merchant. One and only one account may be set to true.
    # >
    # @return [TrueClass | FalseClass]
    attr_accessor :is_primary

    # Account type. Either "checking" or "savings"
    # @return [AccountType12Enum]
    attr_accessor :account_type

    # Array of deposit types. ('fees', 'adjustments', 'returns')
    # @return [Array[String]]
    attr_accessor :alt_deposit_types

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['account_holder_name'] = 'account_holder_name'
      @_hash['routing_number'] = 'routing_number'
      @_hash['account_number'] = 'account_number'
      @_hash['is_primary'] = 'is_primary'
      @_hash['account_type'] = 'account_type'
      @_hash['alt_deposit_types'] = 'alt_deposit_types'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        is_primary
        alt_deposit_types
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(account_holder_name = nil, routing_number = nil,
                   account_number = nil, account_type = nil, is_primary = SKIP,
                   alt_deposit_types = SKIP, additional_properties = {})
      # Add additional model properties to the instance.
      additional_properties.each do |_name, _value|
        instance_variable_set("@#{_name}", _value)
      end

      @account_holder_name = account_holder_name
      @routing_number = routing_number
      @account_number = account_number
      @is_primary = is_primary unless is_primary == SKIP
      @account_type = account_type
      @alt_deposit_types = alt_deposit_types unless alt_deposit_types == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      account_holder_name =
        hash.key?('account_holder_name') ? hash['account_holder_name'] : nil
      routing_number =
        hash.key?('routing_number') ? hash['routing_number'] : nil
      account_number =
        hash.key?('account_number') ? hash['account_number'] : nil
      account_type = hash.key?('account_type') ? hash['account_type'] : nil
      is_primary = hash.key?('is_primary') ? hash['is_primary'] : SKIP
      alt_deposit_types =
        hash.key?('alt_deposit_types') ? hash['alt_deposit_types'] : SKIP

      # Clean out expected properties from Hash.
      additional_properties = hash.reject { |k, _| names.value?(k) }

      # Create object from extracted values.
      BankAccount1.new(account_holder_name,
                       routing_number,
                       account_number,
                       account_type,
                       is_primary,
                       alt_deposit_types,
                       additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} account_holder_name: #{@account_holder_name}, routing_number:"\
      " #{@routing_number}, account_number: #{@account_number}, is_primary: #{@is_primary},"\
      " account_type: #{@account_type}, alt_deposit_types: #{@alt_deposit_types},"\
      " additional_properties: #{get_additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} account_holder_name: #{@account_holder_name.inspect}, routing_number:"\
      " #{@routing_number.inspect}, account_number: #{@account_number.inspect}, is_primary:"\
      " #{@is_primary.inspect}, account_type: #{@account_type.inspect}, alt_deposit_types:"\
      " #{@alt_deposit_types.inspect}, additional_properties: #{get_additional_properties}>"
    end
  end
end
