# fortis_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module FortisApi
  # BatchRiskConfig1 Model.
  class BatchRiskConfig1 < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Blind Refund Total Count
    # @return [Integer]
    attr_accessor :blind_refund_total_count

    # Blind Refund Max Amount
    # @return [Integer]
    attr_accessor :blind_refund_max_amount

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['blind_refund_total_count'] = 'blind_refund_total_count'
      @_hash['blind_refund_max_amount'] = 'blind_refund_max_amount'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        blind_refund_total_count
        blind_refund_max_amount
      ]
    end

    # An array for nullable fields
    def self.nullables
      %w[
        blind_refund_total_count
        blind_refund_max_amount
      ]
    end

    def initialize(blind_refund_total_count: SKIP,
                   blind_refund_max_amount: SKIP, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @blind_refund_total_count = blind_refund_total_count unless blind_refund_total_count == SKIP
      @blind_refund_max_amount = blind_refund_max_amount unless blind_refund_max_amount == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      blind_refund_total_count =
        hash.key?('blind_refund_total_count') ? hash['blind_refund_total_count'] : SKIP
      blind_refund_max_amount =
        hash.key?('blind_refund_max_amount') ? hash['blind_refund_max_amount'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      BatchRiskConfig1.new(blind_refund_total_count: blind_refund_total_count,
                           blind_refund_max_amount: blind_refund_max_amount,
                           additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} blind_refund_total_count: #{@blind_refund_total_count},"\
      " blind_refund_max_amount: #{@blind_refund_max_amount}, additional_properties:"\
      " #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} blind_refund_total_count: #{@blind_refund_total_count.inspect},"\
      " blind_refund_max_amount: #{@blind_refund_max_amount.inspect}, additional_properties:"\
      " #{@additional_properties}>"
    end
  end
end
