# fortis_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module FortisApi
  # Contains information for the Cardholder. This field is required unless
  # market or regional mandate restricts sending this information.
  class Cardholder < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Indicates whether the Cardholder Shipping Address and Cardholder Billing
    # Address are the same.
    #  If the field is not set and the shipping and billing addresses are the
    # same, the 3DS Server will set the value to Y. Otherwise, the value will
    # not be changed.
    # >Y - Shipping Address matches Billing Address
    # >
    # >N - Shipping Address does not match Billing Address
    # >
    # @return [AddressMatchEnum]
    attr_accessor :address_match

    # Cardholder billing address object
    # @return [BillingAddress24]
    attr_accessor :billing_address

    # The email address associated with the account that is either entered by
    # the Cardholder, or is on file with the 3DS Requestor. This field shall
    # meet requirements of Section 3.4 of IETF RFC 5322.
    # This field is required unless market or regional mandate restricts sending
    # this information.
    # @return [String]
    attr_accessor :email

    # The home phone provided by the Cardholder. Refer to ITU-E.164 for
    # additional information on format and length.
    # This field is required if available, unless market or regional mandate
    # restricts sending this information.
    # @return [HomePhone]
    attr_accessor :home_phone

    # The mobile phone provided by the Cardholder. Refer to ITU-E.164 for
    # additional information on format and length.
    # This field is required if available, unless market or regional mandate
    # restricts sending this information.
    # @return [MobilePhone]
    attr_accessor :mobile_phone

    # The work phone provided by the Cardholder. Refer to ITU-E.164 for
    # additional information on format and length.
    # This field is required if available, unless market or regional mandate
    # restricts sending this information.
    # @return [WorkPhone]
    attr_accessor :work_phone

    # Name of the Cardholder.
    # This field is required unless market or regional mandate restricts sending
    # this information.
    # @return [String]
    attr_accessor :cardholder_name

    # Cardholder shipping address object
    # @return [ShippingAddress]
    attr_accessor :shipping_address

    # Tax ID is the Cardholder's tax identification.
    # This field is required depending on the rules provided by the Directory
    # Server.
    # Available for supporting EMV 3DS 2.3.1 and later versions.
    # @return [String]
    attr_accessor :tax_id

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['address_match'] = 'address_match'
      @_hash['billing_address'] = 'billing_address'
      @_hash['email'] = 'email'
      @_hash['home_phone'] = 'home_phone'
      @_hash['mobile_phone'] = 'mobile_phone'
      @_hash['work_phone'] = 'work_phone'
      @_hash['cardholder_name'] = 'cardholder_name'
      @_hash['shipping_address'] = 'shipping_address'
      @_hash['tax_id'] = 'tax_id'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        address_match
        billing_address
        email
        home_phone
        mobile_phone
        work_phone
        cardholder_name
        shipping_address
        tax_id
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(address_match = SKIP, billing_address = SKIP, email = SKIP,
                   home_phone = SKIP, mobile_phone = SKIP, work_phone = SKIP,
                   cardholder_name = SKIP, shipping_address = SKIP,
                   tax_id = SKIP, additional_properties = {})
      # Add additional model properties to the instance.
      additional_properties.each do |_name, _value|
        instance_variable_set("@#{_name}", _value)
      end

      @address_match = address_match unless address_match == SKIP
      @billing_address = billing_address unless billing_address == SKIP
      @email = email unless email == SKIP
      @home_phone = home_phone unless home_phone == SKIP
      @mobile_phone = mobile_phone unless mobile_phone == SKIP
      @work_phone = work_phone unless work_phone == SKIP
      @cardholder_name = cardholder_name unless cardholder_name == SKIP
      @shipping_address = shipping_address unless shipping_address == SKIP
      @tax_id = tax_id unless tax_id == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      address_match = hash.key?('address_match') ? hash['address_match'] : SKIP
      billing_address = BillingAddress24.from_hash(hash['billing_address']) if
        hash['billing_address']
      email = hash.key?('email') ? hash['email'] : SKIP
      home_phone = HomePhone.from_hash(hash['home_phone']) if hash['home_phone']
      mobile_phone = MobilePhone.from_hash(hash['mobile_phone']) if hash['mobile_phone']
      work_phone = WorkPhone.from_hash(hash['work_phone']) if hash['work_phone']
      cardholder_name =
        hash.key?('cardholder_name') ? hash['cardholder_name'] : SKIP
      shipping_address = ShippingAddress.from_hash(hash['shipping_address']) if
        hash['shipping_address']
      tax_id = hash.key?('tax_id') ? hash['tax_id'] : SKIP

      # Clean out expected properties from Hash.
      additional_properties = hash.reject { |k, _| names.value?(k) }

      # Create object from extracted values.
      Cardholder.new(address_match,
                     billing_address,
                     email,
                     home_phone,
                     mobile_phone,
                     work_phone,
                     cardholder_name,
                     shipping_address,
                     tax_id,
                     additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} address_match: #{@address_match}, billing_address: #{@billing_address},"\
      " email: #{@email}, home_phone: #{@home_phone}, mobile_phone: #{@mobile_phone}, work_phone:"\
      " #{@work_phone}, cardholder_name: #{@cardholder_name}, shipping_address:"\
      " #{@shipping_address}, tax_id: #{@tax_id}, additional_properties:"\
      " #{get_additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} address_match: #{@address_match.inspect}, billing_address:"\
      " #{@billing_address.inspect}, email: #{@email.inspect}, home_phone: #{@home_phone.inspect},"\
      " mobile_phone: #{@mobile_phone.inspect}, work_phone: #{@work_phone.inspect},"\
      " cardholder_name: #{@cardholder_name.inspect}, shipping_address:"\
      " #{@shipping_address.inspect}, tax_id: #{@tax_id.inspect}, additional_properties:"\
      " #{get_additional_properties}>"
    end
  end
end
