# fortis_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module FortisApi
  # Cau Subscribe Type Code
  class CauSubscribeTypeCode
    CAU_SUBSCRIBE_TYPE_CODE = [
      # TODO: Write general description for ENUM_0
      ENUM_0 = 0,

      # TODO: Write general description for ENUM_1
      ENUM_1 = 1,

      # TODO: Write general description for ENUM_2
      ENUM_2 = 2
    ].freeze

    def self.validate(value)
      return false if value.nil?

      true
    end

    def self.from_value(value, default_value = ENUM_0)
      return default_value if value.nil?

      str = value.to_s.strip
      if str.match?(/\A\d+\z/)
        num = str.to_i
        return num if CAU_SUBSCRIBE_TYPE_CODE.include?(num)

        return default_value
      end

      case str.downcase
      when 'enum_0' then ENUM_0
      when 'enum_1' then ENUM_1
      when 'enum_2' then ENUM_2
      else
        default_value
      end
    end
  end
end
