# fortis_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module FortisApi
  # Conditions4 Model.
  class Conditions4 < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [Method5]
    attr_accessor :method

    # TODO: Write general description for this method
    # @return [Values4]
    attr_accessor :values

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['method'] = 'method'
      @_hash['values'] = 'values'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        method
        values
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(method: SKIP, values: SKIP, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @method = method unless method == SKIP
      @values = values unless values == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      method = hash.key?('method') ? hash['method'] : SKIP
      values = hash.key?('values') ? hash['values'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      Conditions4.new(method: method,
                      values: values,
                      additional_properties: additional_properties)
    end

    # Validates an instance of the object from a given value.
    # @param [Conditions4 | Hash] The value against the validation is performed.
    def self.validate(value)
      return true if value.instance_of? self

      return false unless value.instance_of? Hash

      true
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} method: #{@method}, values: #{@values}, additional_properties:"\
      " #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} method: #{@method.inspect}, values: #{@values.inspect},"\
      " additional_properties: #{@additional_properties}>"
    end
  end
end
