# fortis_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module FortisApi
  # Data18 Model.
  class Data18 < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Location ID
    # @return [String]
    attr_accessor :location_id

    # Title
    # @return [String]
    attr_accessor :title

    # Transaction ID
    # @return [String]
    attr_accessor :cc_product_transaction_id

    # ACH Product Transaction Id
    # @return [String]
    attr_accessor :ach_product_transaction_id

    # Due Date, Format: Y-m-d
    # @return [String]
    attr_accessor :due_date

    # Item List
    # @return [Array[ItemList]]
    attr_accessor :item_list

    # Allow Overpayment.
    # @return [TrueClass | FalseClass]
    attr_accessor :allow_overpayment

    # Bank Funded Only override
    # @return [TrueClass | FalseClass]
    attr_accessor :bank_funded_only_override

    # Email
    # @return [String]
    attr_accessor :email

    # Contact ID
    # @return [String]
    attr_accessor :contact_id

    # Contact API Id
    # @return [String]
    attr_accessor :contact_api_id

    # Quick Invoice API Id
    # @return [String]
    attr_accessor :quick_invoice_api_id

    # Customer Id
    # @return [String]
    attr_accessor :customer_id

    # Expire Date.
    # @return [String]
    attr_accessor :expire_date

    # Allow partial pay
    # @return [TrueClass | FalseClass]
    attr_accessor :allow_partial_pay

    # Attach Files to Email
    # @return [TrueClass | FalseClass]
    attr_accessor :attach_files_to_email

    # Send Email
    # @return [TrueClass | FalseClass]
    attr_accessor :send_email

    # Invoice number
    # @return [String]
    attr_accessor :invoice_number

    # Item Header
    # @return [String]
    attr_accessor :item_header

    # Item footer
    # @return [String]
    attr_accessor :item_footer

    # Amount Due
    # @return [Float]
    attr_accessor :amount_due

    # Notification email
    # @return [String]
    attr_accessor :notification_email

    # Notification email
    # @return [Object]
    attr_accessor :status_id

    # Notification email
    # @return [Object]
    attr_accessor :status_code

    # Note
    # @return [String]
    attr_accessor :note

    # Notification days before due date
    # @return [Integer]
    attr_accessor :notification_days_before_due_date

    # Notification days after due date
    # @return [Integer]
    attr_accessor :notification_days_after_due_date

    # Notification on due date
    # @return [TrueClass | FalseClass]
    attr_accessor :notification_on_due_date

    # Send Text To Pay
    # @return [TrueClass | FalseClass]
    attr_accessor :send_text_to_pay

    # File Information on `expand`
    # @return [Array[File]]
    attr_accessor :files

    # Remaining Balance
    # @return [Float]
    attr_accessor :remaining_balance

    # Single Payment Min Amount
    # @return [Integer]
    attr_accessor :single_payment_min_amount

    # Single Payment Max Amount
    # @return [Integer]
    attr_accessor :single_payment_max_amount

    # Cell Phone
    # @return [String]
    attr_accessor :cell_phone

    # Tag Information on `expand`
    # @return [Array[Tag]]
    attr_accessor :tags

    # Custom field 1 for api users to store custom data
    # @return [String]
    attr_accessor :quick_invoice_c1

    # Custom field 2 for api users to store custom data
    # @return [String]
    attr_accessor :quick_invoice_c2

    # Custom field 1 for api users to store custom data
    # @return [String]
    attr_accessor :quick_invoice_c3

    # Auto Reopen. If set to true, a void, refund or detachment of a Transaction
    # Payment will cause the QuickInvoice to be opened again
    # @return [TrueClass | FalseClass]
    attr_accessor :auto_reopen

    # Quick Invoice ID
    # @return [String]
    attr_accessor :id

    # Created Time Stamp
    # @return [Integer]
    attr_accessor :created_ts

    # Modified Time Stamp
    # @return [Integer]
    attr_accessor :modified_ts

    # Created User Id
    # @return [String]
    attr_accessor :created_user_id

    # Modified User Id
    # @return [String]
    attr_accessor :modified_user_id

    # Active status
    # @return [TrueClass | FalseClass]
    attr_accessor :active

    # Payment Status Id
    # @return [Integer]
    attr_accessor :payment_status_id

    # Register is active
    # @return [TrueClass | FalseClass]
    attr_accessor :is_active

    # Register is active
    # @return [QuickInvoiceSetting1]
    attr_accessor :quick_invoice_setting

    # Quick Invoice View Information on `expand`
    # @return [Array[QuickInvoiceView]]
    attr_accessor :quick_invoice_views

    # Quick Invoice View Information on `expand`
    # @return [Location18]
    attr_accessor :location

    # Quick Invoice View Information on `expand`
    # @return [User9]
    attr_accessor :created_user

    # Quick Invoice View Information on `expand`
    # @return [User9]
    attr_accessor :modified_user

    # Changelog Information on `expand`
    # @return [Array[Changelog]]
    attr_accessor :changelogs

    # Changelog Information on `expand`
    # @return [Contact3]
    attr_accessor :contact

    # Log Email Information on `expand`
    # @return [Array[LogEmail]]
    attr_accessor :log_emails

    # Log Email Information on `expand`
    # @return [LogSms1]
    attr_accessor :log_sms

    # Transaction Information on `expand`
    # @return [Array[Transaction]]
    attr_accessor :transactions

    # Transaction Information on `expand`
    # @return [ProductTransaction1]
    attr_accessor :cc_product_transaction

    # Transaction Information on `expand`
    # @return [ProductTransaction1]
    attr_accessor :ach_product_transaction

    # Transaction Information on `expand`
    # @return [EmailBlacklist1]
    attr_accessor :email_blacklist

    # Transaction Information on `expand`
    # @return [SmsBlacklist1]
    attr_accessor :sms_blacklist

    # Payment Url Information on `expand`
    # @return [String]
    attr_accessor :payment_url

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['location_id'] = 'location_id'
      @_hash['title'] = 'title'
      @_hash['cc_product_transaction_id'] = 'cc_product_transaction_id'
      @_hash['ach_product_transaction_id'] = 'ach_product_transaction_id'
      @_hash['due_date'] = 'due_date'
      @_hash['item_list'] = 'item_list'
      @_hash['allow_overpayment'] = 'allow_overpayment'
      @_hash['bank_funded_only_override'] = 'bank_funded_only_override'
      @_hash['email'] = 'email'
      @_hash['contact_id'] = 'contact_id'
      @_hash['contact_api_id'] = 'contact_api_id'
      @_hash['quick_invoice_api_id'] = 'quick_invoice_api_id'
      @_hash['customer_id'] = 'customer_id'
      @_hash['expire_date'] = 'expire_date'
      @_hash['allow_partial_pay'] = 'allow_partial_pay'
      @_hash['attach_files_to_email'] = 'attach_files_to_email'
      @_hash['send_email'] = 'send_email'
      @_hash['invoice_number'] = 'invoice_number'
      @_hash['item_header'] = 'item_header'
      @_hash['item_footer'] = 'item_footer'
      @_hash['amount_due'] = 'amount_due'
      @_hash['notification_email'] = 'notification_email'
      @_hash['status_id'] = 'status_id'
      @_hash['status_code'] = 'status_code'
      @_hash['note'] = 'note'
      @_hash['notification_days_before_due_date'] =
        'notification_days_before_due_date'
      @_hash['notification_days_after_due_date'] =
        'notification_days_after_due_date'
      @_hash['notification_on_due_date'] = 'notification_on_due_date'
      @_hash['send_text_to_pay'] = 'send_text_to_pay'
      @_hash['files'] = 'files'
      @_hash['remaining_balance'] = 'remaining_balance'
      @_hash['single_payment_min_amount'] = 'single_payment_min_amount'
      @_hash['single_payment_max_amount'] = 'single_payment_max_amount'
      @_hash['cell_phone'] = 'cell_phone'
      @_hash['tags'] = 'tags'
      @_hash['quick_invoice_c1'] = 'quick_invoice_c1'
      @_hash['quick_invoice_c2'] = 'quick_invoice_c2'
      @_hash['quick_invoice_c3'] = 'quick_invoice_c3'
      @_hash['auto_reopen'] = 'auto_reopen'
      @_hash['id'] = 'id'
      @_hash['created_ts'] = 'created_ts'
      @_hash['modified_ts'] = 'modified_ts'
      @_hash['created_user_id'] = 'created_user_id'
      @_hash['modified_user_id'] = 'modified_user_id'
      @_hash['active'] = 'active'
      @_hash['payment_status_id'] = 'payment_status_id'
      @_hash['is_active'] = 'is_active'
      @_hash['quick_invoice_setting'] = 'quick_invoice_setting'
      @_hash['quick_invoice_views'] = 'quick_invoice_views'
      @_hash['location'] = 'location'
      @_hash['created_user'] = 'created_user'
      @_hash['modified_user'] = 'modified_user'
      @_hash['changelogs'] = 'changelogs'
      @_hash['contact'] = 'contact'
      @_hash['log_emails'] = 'log_emails'
      @_hash['log_sms'] = 'log_sms'
      @_hash['transactions'] = 'transactions'
      @_hash['cc_product_transaction'] = 'cc_product_transaction'
      @_hash['ach_product_transaction'] = 'ach_product_transaction'
      @_hash['email_blacklist'] = 'email_blacklist'
      @_hash['sms_blacklist'] = 'sms_blacklist'
      @_hash['payment_url'] = 'payment_url'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        location_id
        title
        cc_product_transaction_id
        ach_product_transaction_id
        due_date
        item_list
        allow_overpayment
        bank_funded_only_override
        email
        contact_id
        contact_api_id
        quick_invoice_api_id
        customer_id
        expire_date
        allow_partial_pay
        attach_files_to_email
        send_email
        invoice_number
        item_header
        item_footer
        amount_due
        notification_email
        status_id
        status_code
        note
        notification_days_before_due_date
        notification_days_after_due_date
        notification_on_due_date
        send_text_to_pay
        files
        remaining_balance
        single_payment_min_amount
        single_payment_max_amount
        cell_phone
        tags
        quick_invoice_c1
        quick_invoice_c2
        quick_invoice_c3
        auto_reopen
        id
        created_ts
        modified_ts
        created_user_id
        modified_user_id
        active
        payment_status_id
        is_active
        quick_invoice_setting
        quick_invoice_views
        location
        created_user
        modified_user
        changelogs
        contact
        log_emails
        log_sms
        transactions
        cc_product_transaction
        ach_product_transaction
        email_blacklist
        sms_blacklist
        payment_url
      ]
    end

    # An array for nullable fields
    def self.nullables
      %w[
        location_id
        cc_product_transaction_id
        ach_product_transaction_id
        bank_funded_only_override
        email
        contact_id
        contact_api_id
        quick_invoice_api_id
        customer_id
        expire_date
        invoice_number
        item_header
        item_footer
        amount_due
        notification_email
        note
        notification_days_before_due_date
        notification_days_after_due_date
        remaining_balance
        single_payment_min_amount
        single_payment_max_amount
        cell_phone
        quick_invoice_c1
        quick_invoice_c2
        quick_invoice_c3
        created_user_id
        modified_user_id
        payment_status_id
        payment_url
      ]
    end

    def initialize(location_id: SKIP, title: SKIP,
                   cc_product_transaction_id: SKIP,
                   ach_product_transaction_id: SKIP, due_date: SKIP,
                   item_list: SKIP, allow_overpayment: SKIP,
                   bank_funded_only_override: SKIP, email: SKIP,
                   contact_id: SKIP, contact_api_id: SKIP,
                   quick_invoice_api_id: SKIP, customer_id: SKIP,
                   expire_date: SKIP, allow_partial_pay: SKIP,
                   attach_files_to_email: SKIP, send_email: SKIP,
                   invoice_number: SKIP, item_header: SKIP, item_footer: SKIP,
                   amount_due: SKIP, notification_email: SKIP, status_id: SKIP,
                   status_code: SKIP, note: SKIP,
                   notification_days_before_due_date: SKIP,
                   notification_days_after_due_date: SKIP,
                   notification_on_due_date: SKIP, send_text_to_pay: SKIP,
                   files: SKIP, remaining_balance: SKIP,
                   single_payment_min_amount: SKIP,
                   single_payment_max_amount: 999999999, cell_phone: SKIP,
                   tags: SKIP, quick_invoice_c1: SKIP, quick_invoice_c2: SKIP,
                   quick_invoice_c3: SKIP, auto_reopen: SKIP, id: SKIP,
                   created_ts: SKIP, modified_ts: SKIP, created_user_id: SKIP,
                   modified_user_id: SKIP, active: SKIP,
                   payment_status_id: SKIP, is_active: SKIP,
                   quick_invoice_setting: SKIP, quick_invoice_views: SKIP,
                   location: SKIP, created_user: SKIP, modified_user: SKIP,
                   changelogs: SKIP, contact: SKIP, log_emails: SKIP,
                   log_sms: SKIP, transactions: SKIP,
                   cc_product_transaction: SKIP, ach_product_transaction: SKIP,
                   email_blacklist: SKIP, sms_blacklist: SKIP,
                   payment_url: SKIP, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @location_id = location_id unless location_id == SKIP
      @title = title unless title == SKIP
      unless cc_product_transaction_id == SKIP
        @cc_product_transaction_id =
          cc_product_transaction_id
      end
      unless ach_product_transaction_id == SKIP
        @ach_product_transaction_id =
          ach_product_transaction_id
      end
      @due_date = due_date unless due_date == SKIP
      @item_list = item_list unless item_list == SKIP
      @allow_overpayment = allow_overpayment unless allow_overpayment == SKIP
      unless bank_funded_only_override == SKIP
        @bank_funded_only_override =
          bank_funded_only_override
      end
      @email = email unless email == SKIP
      @contact_id = contact_id unless contact_id == SKIP
      @contact_api_id = contact_api_id unless contact_api_id == SKIP
      @quick_invoice_api_id = quick_invoice_api_id unless quick_invoice_api_id == SKIP
      @customer_id = customer_id unless customer_id == SKIP
      @expire_date = expire_date unless expire_date == SKIP
      @allow_partial_pay = allow_partial_pay unless allow_partial_pay == SKIP
      @attach_files_to_email = attach_files_to_email unless attach_files_to_email == SKIP
      @send_email = send_email unless send_email == SKIP
      @invoice_number = invoice_number unless invoice_number == SKIP
      @item_header = item_header unless item_header == SKIP
      @item_footer = item_footer unless item_footer == SKIP
      @amount_due = amount_due unless amount_due == SKIP
      @notification_email = notification_email unless notification_email == SKIP
      @status_id = status_id unless status_id == SKIP
      @status_code = status_code unless status_code == SKIP
      @note = note unless note == SKIP
      unless notification_days_before_due_date == SKIP
        @notification_days_before_due_date =
          notification_days_before_due_date
      end
      unless notification_days_after_due_date == SKIP
        @notification_days_after_due_date =
          notification_days_after_due_date
      end
      @notification_on_due_date = notification_on_due_date unless notification_on_due_date == SKIP
      @send_text_to_pay = send_text_to_pay unless send_text_to_pay == SKIP
      @files = files unless files == SKIP
      @remaining_balance = remaining_balance unless remaining_balance == SKIP
      unless single_payment_min_amount == SKIP
        @single_payment_min_amount =
          single_payment_min_amount
      end
      unless single_payment_max_amount == SKIP
        @single_payment_max_amount =
          single_payment_max_amount
      end
      @cell_phone = cell_phone unless cell_phone == SKIP
      @tags = tags unless tags == SKIP
      @quick_invoice_c1 = quick_invoice_c1 unless quick_invoice_c1 == SKIP
      @quick_invoice_c2 = quick_invoice_c2 unless quick_invoice_c2 == SKIP
      @quick_invoice_c3 = quick_invoice_c3 unless quick_invoice_c3 == SKIP
      @auto_reopen = auto_reopen unless auto_reopen == SKIP
      @id = id unless id == SKIP
      @created_ts = created_ts unless created_ts == SKIP
      @modified_ts = modified_ts unless modified_ts == SKIP
      @created_user_id = created_user_id unless created_user_id == SKIP
      @modified_user_id = modified_user_id unless modified_user_id == SKIP
      @active = active unless active == SKIP
      @payment_status_id = payment_status_id unless payment_status_id == SKIP
      @is_active = is_active unless is_active == SKIP
      @quick_invoice_setting = quick_invoice_setting unless quick_invoice_setting == SKIP
      @quick_invoice_views = quick_invoice_views unless quick_invoice_views == SKIP
      @location = location unless location == SKIP
      @created_user = created_user unless created_user == SKIP
      @modified_user = modified_user unless modified_user == SKIP
      @changelogs = changelogs unless changelogs == SKIP
      @contact = contact unless contact == SKIP
      @log_emails = log_emails unless log_emails == SKIP
      @log_sms = log_sms unless log_sms == SKIP
      @transactions = transactions unless transactions == SKIP
      @cc_product_transaction = cc_product_transaction unless cc_product_transaction == SKIP
      @ach_product_transaction = ach_product_transaction unless ach_product_transaction == SKIP
      @email_blacklist = email_blacklist unless email_blacklist == SKIP
      @sms_blacklist = sms_blacklist unless sms_blacklist == SKIP
      @payment_url = payment_url unless payment_url == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      location_id = hash.key?('location_id') ? hash['location_id'] : SKIP
      title = hash.key?('title') ? hash['title'] : SKIP
      cc_product_transaction_id =
        hash.key?('cc_product_transaction_id') ? hash['cc_product_transaction_id'] : SKIP
      ach_product_transaction_id =
        hash.key?('ach_product_transaction_id') ? hash['ach_product_transaction_id'] : SKIP
      due_date = hash.key?('due_date') ? hash['due_date'] : SKIP
      # Parameter is an array, so we need to iterate through it
      item_list = nil
      unless hash['item_list'].nil?
        item_list = []
        hash['item_list'].each do |structure|
          item_list << (ItemList.from_hash(structure) if structure)
        end
      end

      item_list = SKIP unless hash.key?('item_list')
      allow_overpayment =
        hash.key?('allow_overpayment') ? hash['allow_overpayment'] : SKIP
      bank_funded_only_override =
        hash.key?('bank_funded_only_override') ? hash['bank_funded_only_override'] : SKIP
      email = hash.key?('email') ? hash['email'] : SKIP
      contact_id = hash.key?('contact_id') ? hash['contact_id'] : SKIP
      contact_api_id =
        hash.key?('contact_api_id') ? hash['contact_api_id'] : SKIP
      quick_invoice_api_id =
        hash.key?('quick_invoice_api_id') ? hash['quick_invoice_api_id'] : SKIP
      customer_id = hash.key?('customer_id') ? hash['customer_id'] : SKIP
      expire_date = hash.key?('expire_date') ? hash['expire_date'] : SKIP
      allow_partial_pay =
        hash.key?('allow_partial_pay') ? hash['allow_partial_pay'] : SKIP
      attach_files_to_email =
        hash.key?('attach_files_to_email') ? hash['attach_files_to_email'] : SKIP
      send_email = hash.key?('send_email') ? hash['send_email'] : SKIP
      invoice_number =
        hash.key?('invoice_number') ? hash['invoice_number'] : SKIP
      item_header = hash.key?('item_header') ? hash['item_header'] : SKIP
      item_footer = hash.key?('item_footer') ? hash['item_footer'] : SKIP
      amount_due = hash.key?('amount_due') ? hash['amount_due'] : SKIP
      notification_email =
        hash.key?('notification_email') ? hash['notification_email'] : SKIP
      status_id = hash.key?('status_id') ? hash['status_id'] : SKIP
      status_code = hash.key?('status_code') ? hash['status_code'] : SKIP
      note = hash.key?('note') ? hash['note'] : SKIP
      notification_days_before_due_date =
        hash.key?('notification_days_before_due_date') ? hash['notification_days_before_due_date'] : SKIP
      notification_days_after_due_date =
        hash.key?('notification_days_after_due_date') ? hash['notification_days_after_due_date'] : SKIP
      notification_on_due_date =
        hash.key?('notification_on_due_date') ? hash['notification_on_due_date'] : SKIP
      send_text_to_pay =
        hash.key?('send_text_to_pay') ? hash['send_text_to_pay'] : SKIP
      # Parameter is an array, so we need to iterate through it
      files = nil
      unless hash['files'].nil?
        files = []
        hash['files'].each do |structure|
          files << (File.from_hash(structure) if structure)
        end
      end

      files = SKIP unless hash.key?('files')
      remaining_balance =
        hash.key?('remaining_balance') ? hash['remaining_balance'] : SKIP
      single_payment_min_amount =
        hash.key?('single_payment_min_amount') ? hash['single_payment_min_amount'] : SKIP
      single_payment_max_amount =
        hash['single_payment_max_amount'] ||= 999999999
      cell_phone = hash.key?('cell_phone') ? hash['cell_phone'] : SKIP
      # Parameter is an array, so we need to iterate through it
      tags = nil
      unless hash['tags'].nil?
        tags = []
        hash['tags'].each do |structure|
          tags << (Tag.from_hash(structure) if structure)
        end
      end

      tags = SKIP unless hash.key?('tags')
      quick_invoice_c1 =
        hash.key?('quick_invoice_c1') ? hash['quick_invoice_c1'] : SKIP
      quick_invoice_c2 =
        hash.key?('quick_invoice_c2') ? hash['quick_invoice_c2'] : SKIP
      quick_invoice_c3 =
        hash.key?('quick_invoice_c3') ? hash['quick_invoice_c3'] : SKIP
      auto_reopen = hash.key?('auto_reopen') ? hash['auto_reopen'] : SKIP
      id = hash.key?('id') ? hash['id'] : SKIP
      created_ts = hash.key?('created_ts') ? hash['created_ts'] : SKIP
      modified_ts = hash.key?('modified_ts') ? hash['modified_ts'] : SKIP
      created_user_id =
        hash.key?('created_user_id') ? hash['created_user_id'] : SKIP
      modified_user_id =
        hash.key?('modified_user_id') ? hash['modified_user_id'] : SKIP
      active = hash.key?('active') ? hash['active'] : SKIP
      payment_status_id =
        hash.key?('payment_status_id') ? hash['payment_status_id'] : SKIP
      is_active = hash.key?('is_active') ? hash['is_active'] : SKIP
      quick_invoice_setting = QuickInvoiceSetting1.from_hash(hash['quick_invoice_setting']) if
        hash['quick_invoice_setting']
      # Parameter is an array, so we need to iterate through it
      quick_invoice_views = nil
      unless hash['quick_invoice_views'].nil?
        quick_invoice_views = []
        hash['quick_invoice_views'].each do |structure|
          quick_invoice_views << (QuickInvoiceView.from_hash(structure) if structure)
        end
      end

      quick_invoice_views = SKIP unless hash.key?('quick_invoice_views')
      location = Location18.from_hash(hash['location']) if hash['location']
      created_user = User9.from_hash(hash['created_user']) if hash['created_user']
      modified_user = User9.from_hash(hash['modified_user']) if hash['modified_user']
      # Parameter is an array, so we need to iterate through it
      changelogs = nil
      unless hash['changelogs'].nil?
        changelogs = []
        hash['changelogs'].each do |structure|
          changelogs << (Changelog.from_hash(structure) if structure)
        end
      end

      changelogs = SKIP unless hash.key?('changelogs')
      contact = Contact3.from_hash(hash['contact']) if hash['contact']
      # Parameter is an array, so we need to iterate through it
      log_emails = nil
      unless hash['log_emails'].nil?
        log_emails = []
        hash['log_emails'].each do |structure|
          log_emails << (LogEmail.from_hash(structure) if structure)
        end
      end

      log_emails = SKIP unless hash.key?('log_emails')
      log_sms = LogSms1.from_hash(hash['log_sms']) if hash['log_sms']
      # Parameter is an array, so we need to iterate through it
      transactions = nil
      unless hash['transactions'].nil?
        transactions = []
        hash['transactions'].each do |structure|
          transactions << (Transaction.from_hash(structure) if structure)
        end
      end

      transactions = SKIP unless hash.key?('transactions')
      cc_product_transaction = ProductTransaction1.from_hash(hash['cc_product_transaction']) if
        hash['cc_product_transaction']
      ach_product_transaction = ProductTransaction1.from_hash(hash['ach_product_transaction']) if
        hash['ach_product_transaction']
      email_blacklist = EmailBlacklist1.from_hash(hash['email_blacklist']) if
        hash['email_blacklist']
      sms_blacklist = SmsBlacklist1.from_hash(hash['sms_blacklist']) if hash['sms_blacklist']
      payment_url = hash.key?('payment_url') ? hash['payment_url'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      Data18.new(location_id: location_id,
                 title: title,
                 cc_product_transaction_id: cc_product_transaction_id,
                 ach_product_transaction_id: ach_product_transaction_id,
                 due_date: due_date,
                 item_list: item_list,
                 allow_overpayment: allow_overpayment,
                 bank_funded_only_override: bank_funded_only_override,
                 email: email,
                 contact_id: contact_id,
                 contact_api_id: contact_api_id,
                 quick_invoice_api_id: quick_invoice_api_id,
                 customer_id: customer_id,
                 expire_date: expire_date,
                 allow_partial_pay: allow_partial_pay,
                 attach_files_to_email: attach_files_to_email,
                 send_email: send_email,
                 invoice_number: invoice_number,
                 item_header: item_header,
                 item_footer: item_footer,
                 amount_due: amount_due,
                 notification_email: notification_email,
                 status_id: status_id,
                 status_code: status_code,
                 note: note,
                 notification_days_before_due_date: notification_days_before_due_date,
                 notification_days_after_due_date: notification_days_after_due_date,
                 notification_on_due_date: notification_on_due_date,
                 send_text_to_pay: send_text_to_pay,
                 files: files,
                 remaining_balance: remaining_balance,
                 single_payment_min_amount: single_payment_min_amount,
                 single_payment_max_amount: single_payment_max_amount,
                 cell_phone: cell_phone,
                 tags: tags,
                 quick_invoice_c1: quick_invoice_c1,
                 quick_invoice_c2: quick_invoice_c2,
                 quick_invoice_c3: quick_invoice_c3,
                 auto_reopen: auto_reopen,
                 id: id,
                 created_ts: created_ts,
                 modified_ts: modified_ts,
                 created_user_id: created_user_id,
                 modified_user_id: modified_user_id,
                 active: active,
                 payment_status_id: payment_status_id,
                 is_active: is_active,
                 quick_invoice_setting: quick_invoice_setting,
                 quick_invoice_views: quick_invoice_views,
                 location: location,
                 created_user: created_user,
                 modified_user: modified_user,
                 changelogs: changelogs,
                 contact: contact,
                 log_emails: log_emails,
                 log_sms: log_sms,
                 transactions: transactions,
                 cc_product_transaction: cc_product_transaction,
                 ach_product_transaction: ach_product_transaction,
                 email_blacklist: email_blacklist,
                 sms_blacklist: sms_blacklist,
                 payment_url: payment_url,
                 additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} location_id: #{@location_id}, title: #{@title}, cc_product_transaction_id:"\
      " #{@cc_product_transaction_id}, ach_product_transaction_id: #{@ach_product_transaction_id},"\
      " due_date: #{@due_date}, item_list: #{@item_list}, allow_overpayment:"\
      " #{@allow_overpayment}, bank_funded_only_override: #{@bank_funded_only_override}, email:"\
      " #{@email}, contact_id: #{@contact_id}, contact_api_id: #{@contact_api_id},"\
      " quick_invoice_api_id: #{@quick_invoice_api_id}, customer_id: #{@customer_id}, expire_date:"\
      " #{@expire_date}, allow_partial_pay: #{@allow_partial_pay}, attach_files_to_email:"\
      " #{@attach_files_to_email}, send_email: #{@send_email}, invoice_number: #{@invoice_number},"\
      " item_header: #{@item_header}, item_footer: #{@item_footer}, amount_due: #{@amount_due},"\
      " notification_email: #{@notification_email}, status_id: #{@status_id}, status_code:"\
      " #{@status_code}, note: #{@note}, notification_days_before_due_date:"\
      " #{@notification_days_before_due_date}, notification_days_after_due_date:"\
      " #{@notification_days_after_due_date}, notification_on_due_date:"\
      " #{@notification_on_due_date}, send_text_to_pay: #{@send_text_to_pay}, files: #{@files},"\
      " remaining_balance: #{@remaining_balance}, single_payment_min_amount:"\
      " #{@single_payment_min_amount}, single_payment_max_amount: #{@single_payment_max_amount},"\
      " cell_phone: #{@cell_phone}, tags: #{@tags}, quick_invoice_c1: #{@quick_invoice_c1},"\
      " quick_invoice_c2: #{@quick_invoice_c2}, quick_invoice_c3: #{@quick_invoice_c3},"\
      " auto_reopen: #{@auto_reopen}, id: #{@id}, created_ts: #{@created_ts}, modified_ts:"\
      " #{@modified_ts}, created_user_id: #{@created_user_id}, modified_user_id:"\
      " #{@modified_user_id}, active: #{@active}, payment_status_id: #{@payment_status_id},"\
      " is_active: #{@is_active}, quick_invoice_setting: #{@quick_invoice_setting},"\
      " quick_invoice_views: #{@quick_invoice_views}, location: #{@location}, created_user:"\
      " #{@created_user}, modified_user: #{@modified_user}, changelogs: #{@changelogs}, contact:"\
      " #{@contact}, log_emails: #{@log_emails}, log_sms: #{@log_sms}, transactions:"\
      " #{@transactions}, cc_product_transaction: #{@cc_product_transaction},"\
      " ach_product_transaction: #{@ach_product_transaction}, email_blacklist:"\
      " #{@email_blacklist}, sms_blacklist: #{@sms_blacklist}, payment_url: #{@payment_url},"\
      " additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} location_id: #{@location_id.inspect}, title: #{@title.inspect},"\
      " cc_product_transaction_id: #{@cc_product_transaction_id.inspect},"\
      " ach_product_transaction_id: #{@ach_product_transaction_id.inspect}, due_date:"\
      " #{@due_date.inspect}, item_list: #{@item_list.inspect}, allow_overpayment:"\
      " #{@allow_overpayment.inspect}, bank_funded_only_override:"\
      " #{@bank_funded_only_override.inspect}, email: #{@email.inspect}, contact_id:"\
      " #{@contact_id.inspect}, contact_api_id: #{@contact_api_id.inspect}, quick_invoice_api_id:"\
      " #{@quick_invoice_api_id.inspect}, customer_id: #{@customer_id.inspect}, expire_date:"\
      " #{@expire_date.inspect}, allow_partial_pay: #{@allow_partial_pay.inspect},"\
      " attach_files_to_email: #{@attach_files_to_email.inspect}, send_email:"\
      " #{@send_email.inspect}, invoice_number: #{@invoice_number.inspect}, item_header:"\
      " #{@item_header.inspect}, item_footer: #{@item_footer.inspect}, amount_due:"\
      " #{@amount_due.inspect}, notification_email: #{@notification_email.inspect}, status_id:"\
      " #{@status_id.inspect}, status_code: #{@status_code.inspect}, note: #{@note.inspect},"\
      " notification_days_before_due_date: #{@notification_days_before_due_date.inspect},"\
      " notification_days_after_due_date: #{@notification_days_after_due_date.inspect},"\
      " notification_on_due_date: #{@notification_on_due_date.inspect}, send_text_to_pay:"\
      " #{@send_text_to_pay.inspect}, files: #{@files.inspect}, remaining_balance:"\
      " #{@remaining_balance.inspect}, single_payment_min_amount:"\
      " #{@single_payment_min_amount.inspect}, single_payment_max_amount:"\
      " #{@single_payment_max_amount.inspect}, cell_phone: #{@cell_phone.inspect}, tags:"\
      " #{@tags.inspect}, quick_invoice_c1: #{@quick_invoice_c1.inspect}, quick_invoice_c2:"\
      " #{@quick_invoice_c2.inspect}, quick_invoice_c3: #{@quick_invoice_c3.inspect}, auto_reopen:"\
      " #{@auto_reopen.inspect}, id: #{@id.inspect}, created_ts: #{@created_ts.inspect},"\
      " modified_ts: #{@modified_ts.inspect}, created_user_id: #{@created_user_id.inspect},"\
      " modified_user_id: #{@modified_user_id.inspect}, active: #{@active.inspect},"\
      " payment_status_id: #{@payment_status_id.inspect}, is_active: #{@is_active.inspect},"\
      " quick_invoice_setting: #{@quick_invoice_setting.inspect}, quick_invoice_views:"\
      " #{@quick_invoice_views.inspect}, location: #{@location.inspect}, created_user:"\
      " #{@created_user.inspect}, modified_user: #{@modified_user.inspect}, changelogs:"\
      " #{@changelogs.inspect}, contact: #{@contact.inspect}, log_emails: #{@log_emails.inspect},"\
      " log_sms: #{@log_sms.inspect}, transactions: #{@transactions.inspect},"\
      " cc_product_transaction: #{@cc_product_transaction.inspect}, ach_product_transaction:"\
      " #{@ach_product_transaction.inspect}, email_blacklist: #{@email_blacklist.inspect},"\
      " sms_blacklist: #{@sms_blacklist.inspect}, payment_url: #{@payment_url.inspect},"\
      " additional_properties: #{@additional_properties}>"
    end
  end
end
