# fortis_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module FortisApi
  # Data2 Model.
  class Data2 < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Location ID
    # @return [String]
    attr_accessor :location_id

    # Contact Account Number
    # @return [String]
    attr_accessor :account_number

    # Contact API Id
    # @return [String]
    attr_accessor :contact_api_id

    # First Name
    # @return [String]
    attr_accessor :first_name

    # Last Name
    # @return [String]
    attr_accessor :last_name

    # Cell phone of contact
    # @return [String]
    attr_accessor :cell_phone

    # Balance
    # @return [Float]
    attr_accessor :balance

    # Address of contact
    # @return [Address]
    attr_accessor :address

    # Company Name
    # @return [String]
    attr_accessor :company_name

    # Header Message
    # @return [String]
    attr_accessor :header_message

    # Contacts DOB, Format: yyyy-MM-dd
    # @return [String]
    attr_accessor :date_of_birth

    # Whether or not to email all transactions receipts to contact (1 or 0)
    # @return [TrueClass | FalseClass]
    attr_accessor :email_trx_receipt

    # Contacts home phone
    # @return [String]
    attr_accessor :home_phone

    # Contacts office phone
    # @return [String]
    attr_accessor :office_phone

    # Contacts office phone extension for office phone
    # @return [String]
    attr_accessor :office_phone_ext

    # Home phone country code
    # @return [String]
    attr_accessor :home_phone_country_code

    # Office phone country code
    # @return [String]
    attr_accessor :office_phone_country_code

    # Cell phone country code
    # @return [String]
    attr_accessor :cell_phone_country_code

    # Header Message Type
    # @return [Integer]
    attr_accessor :header_message_type

    # Update If Exists
    # @return [UpdateIfExistsEnum]
    attr_accessor :update_if_exists

    # Custom field 1 for api users to store custom data
    # @return [String]
    attr_accessor :contact_c1

    # Custom field 2 for api users to store custom data
    # @return [String]
    attr_accessor :contact_c2

    # Custom field 3 for api users to store custom data
    # @return [String]
    attr_accessor :contact_c3

    # Parent Id
    # @return [String]
    attr_accessor :parent_id

    # Email of contact
    # @return [String]
    attr_accessor :email

    # Token Import Id
    # @return [String]
    attr_accessor :token_import_id

    # Contact ID
    # @return [String]
    attr_accessor :id

    # Created Time Stamp
    # @return [Integer]
    attr_accessor :created_ts

    # Modified Time Stamp
    # @return [Integer]
    attr_accessor :modified_ts

    # Active
    # @return [TrueClass | FalseClass]
    attr_accessor :active

    # User ID Created the register
    # @return [String]
    attr_accessor :created_user_id

    # Received Email Information on `expand`
    # @return [Array[ReceivedEmail]]
    attr_accessor :received_emails

    # Is Deletable Information on `expand`
    # @return [TrueClass | FalseClass]
    attr_accessor :is_deletable

    # Location Information on `expand`
    # @return [Location]
    attr_accessor :location

    # User Information on `expand`
    # @return [User1]
    attr_accessor :user

    # Recurring Information on `expand`
    # @return [Array[Recurring]]
    attr_accessor :recurrings

    # Email Blacklist Information on `expand`
    # @return [EmailBlacklist]
    attr_accessor :email_blacklist

    # Sms Blacklist Information on `expand`
    # @return [SmsBlacklist]
    attr_accessor :sms_blacklist

    # Changelog Information on `expand`
    # @return [Array[Changelog]]
    attr_accessor :changelogs

    # Postback Log Information on `expand`
    # @return [Array[PostbackLog]]
    attr_accessor :postback_logs

    # User Information on `expand`
    # @return [CreatedUser]
    attr_accessor :created_user

    # Parent Information on `expand`
    # @return [Parent]
    attr_accessor :parent

    # Children Information on `expand`
    # @return [Children]
    attr_accessor :children

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['location_id'] = 'location_id'
      @_hash['account_number'] = 'account_number'
      @_hash['contact_api_id'] = 'contact_api_id'
      @_hash['first_name'] = 'first_name'
      @_hash['last_name'] = 'last_name'
      @_hash['cell_phone'] = 'cell_phone'
      @_hash['balance'] = 'balance'
      @_hash['address'] = 'address'
      @_hash['company_name'] = 'company_name'
      @_hash['header_message'] = 'header_message'
      @_hash['date_of_birth'] = 'date_of_birth'
      @_hash['email_trx_receipt'] = 'email_trx_receipt'
      @_hash['home_phone'] = 'home_phone'
      @_hash['office_phone'] = 'office_phone'
      @_hash['office_phone_ext'] = 'office_phone_ext'
      @_hash['home_phone_country_code'] = 'home_phone_country_code'
      @_hash['office_phone_country_code'] = 'office_phone_country_code'
      @_hash['cell_phone_country_code'] = 'cell_phone_country_code'
      @_hash['header_message_type'] = 'header_message_type'
      @_hash['update_if_exists'] = 'update_if_exists'
      @_hash['contact_c1'] = 'contact_c1'
      @_hash['contact_c2'] = 'contact_c2'
      @_hash['contact_c3'] = 'contact_c3'
      @_hash['parent_id'] = 'parent_id'
      @_hash['email'] = 'email'
      @_hash['token_import_id'] = 'token_import_id'
      @_hash['id'] = 'id'
      @_hash['created_ts'] = 'created_ts'
      @_hash['modified_ts'] = 'modified_ts'
      @_hash['active'] = 'active'
      @_hash['created_user_id'] = 'created_user_id'
      @_hash['received_emails'] = 'received_emails'
      @_hash['is_deletable'] = 'is_deletable'
      @_hash['location'] = 'location'
      @_hash['user'] = 'user'
      @_hash['recurrings'] = 'recurrings'
      @_hash['email_blacklist'] = 'email_blacklist'
      @_hash['sms_blacklist'] = 'sms_blacklist'
      @_hash['changelogs'] = 'changelogs'
      @_hash['postback_logs'] = 'postback_logs'
      @_hash['created_user'] = 'created_user'
      @_hash['parent'] = 'parent'
      @_hash['children'] = 'children'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        location_id
        account_number
        contact_api_id
        first_name
        last_name
        cell_phone
        balance
        address
        company_name
        header_message
        date_of_birth
        email_trx_receipt
        home_phone
        office_phone
        office_phone_ext
        home_phone_country_code
        office_phone_country_code
        cell_phone_country_code
        header_message_type
        update_if_exists
        contact_c1
        contact_c2
        contact_c3
        parent_id
        email
        token_import_id
        id
        created_ts
        modified_ts
        active
        created_user_id
        received_emails
        is_deletable
        location
        user
        recurrings
        email_blacklist
        sms_blacklist
        changelogs
        postback_logs
        created_user
        parent
        children
      ]
    end

    # An array for nullable fields
    def self.nullables
      %w[
        account_number
        contact_api_id
        first_name
        cell_phone
        balance
        company_name
        header_message
        date_of_birth
        home_phone
        office_phone
        office_phone_ext
        home_phone_country_code
        office_phone_country_code
        cell_phone_country_code
        update_if_exists
        contact_c1
        contact_c2
        contact_c3
        parent_id
        email
        token_import_id
        created_user_id
      ]
    end

    def initialize(location_id = SKIP, account_number = SKIP,
                   contact_api_id = SKIP, first_name = SKIP, last_name = SKIP,
                   cell_phone = SKIP, balance = SKIP, address = SKIP,
                   company_name = SKIP, header_message = SKIP,
                   date_of_birth = SKIP, email_trx_receipt = SKIP,
                   home_phone = SKIP, office_phone = SKIP,
                   office_phone_ext = SKIP, home_phone_country_code = SKIP,
                   office_phone_country_code = SKIP,
                   cell_phone_country_code = SKIP, header_message_type = SKIP,
                   update_if_exists = SKIP, contact_c1 = SKIP,
                   contact_c2 = SKIP, contact_c3 = SKIP, parent_id = SKIP,
                   email = SKIP, token_import_id = SKIP, id = SKIP,
                   created_ts = SKIP, modified_ts = SKIP, active = SKIP,
                   created_user_id = SKIP, received_emails = SKIP,
                   is_deletable = SKIP, location = SKIP, user = SKIP,
                   recurrings = SKIP, email_blacklist = SKIP,
                   sms_blacklist = SKIP, changelogs = SKIP,
                   postback_logs = SKIP, created_user = SKIP, parent = SKIP,
                   children = SKIP, additional_properties = {})
      # Add additional model properties to the instance.
      additional_properties.each do |_name, _value|
        instance_variable_set("@#{_name}", _value)
      end

      @location_id = location_id unless location_id == SKIP
      @account_number = account_number unless account_number == SKIP
      @contact_api_id = contact_api_id unless contact_api_id == SKIP
      @first_name = first_name unless first_name == SKIP
      @last_name = last_name unless last_name == SKIP
      @cell_phone = cell_phone unless cell_phone == SKIP
      @balance = balance unless balance == SKIP
      @address = address unless address == SKIP
      @company_name = company_name unless company_name == SKIP
      @header_message = header_message unless header_message == SKIP
      @date_of_birth = date_of_birth unless date_of_birth == SKIP
      @email_trx_receipt = email_trx_receipt unless email_trx_receipt == SKIP
      @home_phone = home_phone unless home_phone == SKIP
      @office_phone = office_phone unless office_phone == SKIP
      @office_phone_ext = office_phone_ext unless office_phone_ext == SKIP
      @home_phone_country_code = home_phone_country_code unless home_phone_country_code == SKIP
      unless office_phone_country_code == SKIP
        @office_phone_country_code =
          office_phone_country_code
      end
      @cell_phone_country_code = cell_phone_country_code unless cell_phone_country_code == SKIP
      @header_message_type = header_message_type unless header_message_type == SKIP
      @update_if_exists = update_if_exists unless update_if_exists == SKIP
      @contact_c1 = contact_c1 unless contact_c1 == SKIP
      @contact_c2 = contact_c2 unless contact_c2 == SKIP
      @contact_c3 = contact_c3 unless contact_c3 == SKIP
      @parent_id = parent_id unless parent_id == SKIP
      @email = email unless email == SKIP
      @token_import_id = token_import_id unless token_import_id == SKIP
      @id = id unless id == SKIP
      @created_ts = created_ts unless created_ts == SKIP
      @modified_ts = modified_ts unless modified_ts == SKIP
      @active = active unless active == SKIP
      @created_user_id = created_user_id unless created_user_id == SKIP
      @received_emails = received_emails unless received_emails == SKIP
      @is_deletable = is_deletable unless is_deletable == SKIP
      @location = location unless location == SKIP
      @user = user unless user == SKIP
      @recurrings = recurrings unless recurrings == SKIP
      @email_blacklist = email_blacklist unless email_blacklist == SKIP
      @sms_blacklist = sms_blacklist unless sms_blacklist == SKIP
      @changelogs = changelogs unless changelogs == SKIP
      @postback_logs = postback_logs unless postback_logs == SKIP
      @created_user = created_user unless created_user == SKIP
      @parent = parent unless parent == SKIP
      @children = children unless children == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      location_id = hash.key?('location_id') ? hash['location_id'] : SKIP
      account_number =
        hash.key?('account_number') ? hash['account_number'] : SKIP
      contact_api_id =
        hash.key?('contact_api_id') ? hash['contact_api_id'] : SKIP
      first_name = hash.key?('first_name') ? hash['first_name'] : SKIP
      last_name = hash.key?('last_name') ? hash['last_name'] : SKIP
      cell_phone = hash.key?('cell_phone') ? hash['cell_phone'] : SKIP
      balance = hash.key?('balance') ? hash['balance'] : SKIP
      address = Address.from_hash(hash['address']) if hash['address']
      company_name = hash.key?('company_name') ? hash['company_name'] : SKIP
      header_message =
        hash.key?('header_message') ? hash['header_message'] : SKIP
      date_of_birth = hash.key?('date_of_birth') ? hash['date_of_birth'] : SKIP
      email_trx_receipt =
        hash.key?('email_trx_receipt') ? hash['email_trx_receipt'] : SKIP
      home_phone = hash.key?('home_phone') ? hash['home_phone'] : SKIP
      office_phone = hash.key?('office_phone') ? hash['office_phone'] : SKIP
      office_phone_ext =
        hash.key?('office_phone_ext') ? hash['office_phone_ext'] : SKIP
      home_phone_country_code =
        hash.key?('home_phone_country_code') ? hash['home_phone_country_code'] : SKIP
      office_phone_country_code =
        hash.key?('office_phone_country_code') ? hash['office_phone_country_code'] : SKIP
      cell_phone_country_code =
        hash.key?('cell_phone_country_code') ? hash['cell_phone_country_code'] : SKIP
      header_message_type =
        hash.key?('header_message_type') ? hash['header_message_type'] : SKIP
      update_if_exists =
        hash.key?('update_if_exists') ? hash['update_if_exists'] : SKIP
      contact_c1 = hash.key?('contact_c1') ? hash['contact_c1'] : SKIP
      contact_c2 = hash.key?('contact_c2') ? hash['contact_c2'] : SKIP
      contact_c3 = hash.key?('contact_c3') ? hash['contact_c3'] : SKIP
      parent_id = hash.key?('parent_id') ? hash['parent_id'] : SKIP
      email = hash.key?('email') ? hash['email'] : SKIP
      token_import_id =
        hash.key?('token_import_id') ? hash['token_import_id'] : SKIP
      id = hash.key?('id') ? hash['id'] : SKIP
      created_ts = hash.key?('created_ts') ? hash['created_ts'] : SKIP
      modified_ts = hash.key?('modified_ts') ? hash['modified_ts'] : SKIP
      active = hash.key?('active') ? hash['active'] : SKIP
      created_user_id =
        hash.key?('created_user_id') ? hash['created_user_id'] : SKIP
      # Parameter is an array, so we need to iterate through it
      received_emails = nil
      unless hash['received_emails'].nil?
        received_emails = []
        hash['received_emails'].each do |structure|
          received_emails << (ReceivedEmail.from_hash(structure) if structure)
        end
      end

      received_emails = SKIP unless hash.key?('received_emails')
      is_deletable = hash.key?('is_deletable') ? hash['is_deletable'] : SKIP
      location = Location.from_hash(hash['location']) if hash['location']
      user = User1.from_hash(hash['user']) if hash['user']
      # Parameter is an array, so we need to iterate through it
      recurrings = nil
      unless hash['recurrings'].nil?
        recurrings = []
        hash['recurrings'].each do |structure|
          recurrings << (Recurring.from_hash(structure) if structure)
        end
      end

      recurrings = SKIP unless hash.key?('recurrings')
      email_blacklist = EmailBlacklist.from_hash(hash['email_blacklist']) if
        hash['email_blacklist']
      sms_blacklist = SmsBlacklist.from_hash(hash['sms_blacklist']) if hash['sms_blacklist']
      # Parameter is an array, so we need to iterate through it
      changelogs = nil
      unless hash['changelogs'].nil?
        changelogs = []
        hash['changelogs'].each do |structure|
          changelogs << (Changelog.from_hash(structure) if structure)
        end
      end

      changelogs = SKIP unless hash.key?('changelogs')
      # Parameter is an array, so we need to iterate through it
      postback_logs = nil
      unless hash['postback_logs'].nil?
        postback_logs = []
        hash['postback_logs'].each do |structure|
          postback_logs << (PostbackLog.from_hash(structure) if structure)
        end
      end

      postback_logs = SKIP unless hash.key?('postback_logs')
      created_user = CreatedUser.from_hash(hash['created_user']) if hash['created_user']
      parent = Parent.from_hash(hash['parent']) if hash['parent']
      children = Children.from_hash(hash['children']) if hash['children']

      # Clean out expected properties from Hash.
      additional_properties = hash.reject { |k, _| names.value?(k) }

      # Create object from extracted values.
      Data2.new(location_id,
                account_number,
                contact_api_id,
                first_name,
                last_name,
                cell_phone,
                balance,
                address,
                company_name,
                header_message,
                date_of_birth,
                email_trx_receipt,
                home_phone,
                office_phone,
                office_phone_ext,
                home_phone_country_code,
                office_phone_country_code,
                cell_phone_country_code,
                header_message_type,
                update_if_exists,
                contact_c1,
                contact_c2,
                contact_c3,
                parent_id,
                email,
                token_import_id,
                id,
                created_ts,
                modified_ts,
                active,
                created_user_id,
                received_emails,
                is_deletable,
                location,
                user,
                recurrings,
                email_blacklist,
                sms_blacklist,
                changelogs,
                postback_logs,
                created_user,
                parent,
                children,
                additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} location_id: #{@location_id}, account_number: #{@account_number},"\
      " contact_api_id: #{@contact_api_id}, first_name: #{@first_name}, last_name: #{@last_name},"\
      " cell_phone: #{@cell_phone}, balance: #{@balance}, address: #{@address}, company_name:"\
      " #{@company_name}, header_message: #{@header_message}, date_of_birth: #{@date_of_birth},"\
      " email_trx_receipt: #{@email_trx_receipt}, home_phone: #{@home_phone}, office_phone:"\
      " #{@office_phone}, office_phone_ext: #{@office_phone_ext}, home_phone_country_code:"\
      " #{@home_phone_country_code}, office_phone_country_code: #{@office_phone_country_code},"\
      " cell_phone_country_code: #{@cell_phone_country_code}, header_message_type:"\
      " #{@header_message_type}, update_if_exists: #{@update_if_exists}, contact_c1:"\
      " #{@contact_c1}, contact_c2: #{@contact_c2}, contact_c3: #{@contact_c3}, parent_id:"\
      " #{@parent_id}, email: #{@email}, token_import_id: #{@token_import_id}, id: #{@id},"\
      " created_ts: #{@created_ts}, modified_ts: #{@modified_ts}, active: #{@active},"\
      " created_user_id: #{@created_user_id}, received_emails: #{@received_emails}, is_deletable:"\
      " #{@is_deletable}, location: #{@location}, user: #{@user}, recurrings: #{@recurrings},"\
      " email_blacklist: #{@email_blacklist}, sms_blacklist: #{@sms_blacklist}, changelogs:"\
      " #{@changelogs}, postback_logs: #{@postback_logs}, created_user: #{@created_user}, parent:"\
      " #{@parent}, children: #{@children}, additional_properties: #{get_additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} location_id: #{@location_id.inspect}, account_number:"\
      " #{@account_number.inspect}, contact_api_id: #{@contact_api_id.inspect}, first_name:"\
      " #{@first_name.inspect}, last_name: #{@last_name.inspect}, cell_phone:"\
      " #{@cell_phone.inspect}, balance: #{@balance.inspect}, address: #{@address.inspect},"\
      " company_name: #{@company_name.inspect}, header_message: #{@header_message.inspect},"\
      " date_of_birth: #{@date_of_birth.inspect}, email_trx_receipt:"\
      " #{@email_trx_receipt.inspect}, home_phone: #{@home_phone.inspect}, office_phone:"\
      " #{@office_phone.inspect}, office_phone_ext: #{@office_phone_ext.inspect},"\
      " home_phone_country_code: #{@home_phone_country_code.inspect}, office_phone_country_code:"\
      " #{@office_phone_country_code.inspect}, cell_phone_country_code:"\
      " #{@cell_phone_country_code.inspect}, header_message_type: #{@header_message_type.inspect},"\
      " update_if_exists: #{@update_if_exists.inspect}, contact_c1: #{@contact_c1.inspect},"\
      " contact_c2: #{@contact_c2.inspect}, contact_c3: #{@contact_c3.inspect}, parent_id:"\
      " #{@parent_id.inspect}, email: #{@email.inspect}, token_import_id:"\
      " #{@token_import_id.inspect}, id: #{@id.inspect}, created_ts: #{@created_ts.inspect},"\
      " modified_ts: #{@modified_ts.inspect}, active: #{@active.inspect}, created_user_id:"\
      " #{@created_user_id.inspect}, received_emails: #{@received_emails.inspect}, is_deletable:"\
      " #{@is_deletable.inspect}, location: #{@location.inspect}, user: #{@user.inspect},"\
      " recurrings: #{@recurrings.inspect}, email_blacklist: #{@email_blacklist.inspect},"\
      " sms_blacklist: #{@sms_blacklist.inspect}, changelogs: #{@changelogs.inspect},"\
      " postback_logs: #{@postback_logs.inspect}, created_user: #{@created_user.inspect}, parent:"\
      " #{@parent.inspect}, children: #{@children.inspect}, additional_properties:"\
      " #{get_additional_properties}>"
    end
  end
end
