# fortis_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module FortisApi
  # Indicates the merchandise delivery timeframe. >01 - Electronic Delivery >
  # >02 - Same day shipping > >03 - Overnight shipping > >04 - Two-day or more
  # shipping >
  class DeliveryTimeframe
    DELIVERY_TIMEFRAME = [
      # TODO: Write general description for ENUM_01
      ENUM_01 = '01'.freeze,

      # TODO: Write general description for ENUM_02
      ENUM_02 = '02'.freeze,

      # TODO: Write general description for ENUM_03
      ENUM_03 = '03'.freeze,

      # TODO: Write general description for ENUM_04
      ENUM_04 = '04'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      true
    end

    def self.from_value(value, default_value = ENUM_01)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'enum_01' then ENUM_01
      when 'enum_02' then ENUM_02
      when 'enum_03' then ENUM_03
      when 'enum_04' then ENUM_04
      else
        default_value
      end
    end
  end
end
