# fortis_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module FortisApi
  # Contains device information. Available for supporting EMV 3DS 2.3.1 and
  # later versions.
  class Device < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Enables the communication of Device Binding Status between the ACS, the DS
    # and the 3DS Requestor. For bound devices (value = 11–14), Device Binding
    # Status also conveys the type of binding that was performed.
    # >01 - Device is not bound by Cardholder
    # >
    # >02 - Not eligible as determined by Issuer
    # >
    # >03 - Pending confirmation by Cardholder
    # >
    # >04 - Cardholder rejected
    # >
    # >05 - Device Binding Status unknown, unavailable, or does not apply
    # >
    # >06 through 10 - Reserved for EMVCo future use (values invalid until
    # defined by EMVCo)
    # >
    # >11 - Device is bound by Cardholder (device is bound using hardware / SIM
    # internal to the Consumer Device. For instance, keys stored in a secure
    # element on the device)
    # >
    # >12 - Device is bound by Cardholder (device is bound using hardware
    # external to the Consumer Device. For example, an external FIDO
    # Authenticator
    # >
    # >13 - Device is bound by Cardholder (device is bound using data that
    # includes dynamically generated data and could include a unique device ID)
    # >
    # >14 - Device is bound by Cardholder (device is bound using static device
    # data that has been obtained from the Consumer Device
    # >
    # >15 - Device is bound by Cardholder (Other method)
    # >
    # >16 through 79 - Reserved for EMVCo future use (values invalid until
    # defined by EMVCo)
    # >
    # >80 through 99 - Reserved for DS use
    # >
    # @return [DeviceBindingStatusEnum]
    attr_accessor :device_binding_status

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['device_binding_status'] = 'device_binding_status'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        device_binding_status
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(device_binding_status = SKIP, additional_properties = {})
      # Add additional model properties to the instance.
      additional_properties.each do |_name, _value|
        instance_variable_set("@#{_name}", _value)
      end

      @device_binding_status = device_binding_status unless device_binding_status == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      device_binding_status =
        hash.key?('device_binding_status') ? hash['device_binding_status'] : SKIP

      # Clean out expected properties from Hash.
      additional_properties = hash.reject { |k, _| names.value?(k) }

      # Create object from extracted values.
      Device.new(device_binding_status,
                 additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} device_binding_status: #{@device_binding_status}, additional_properties:"\
      " #{get_additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} device_binding_status: #{@device_binding_status.inspect},"\
      " additional_properties: #{get_additional_properties}>"
    end
  end
end
