# fortis_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module FortisApi
  # expand117.
  class Expand117Enum
    EXPAND117_ENUM = [
      # TODO: Write general description for RECEIVED_EMAILS
      RECEIVED_EMAILS = 'received_emails'.freeze,

      # TODO: Write general description for FEATURE_FLAGS
      FEATURE_FLAGS = 'feature_flags'.freeze,

      # TODO: Write general description for PRIMARY_LOCATION
      PRIMARY_LOCATION = 'primary_location'.freeze,

      # TODO: Write general description for LOCATIONS
      LOCATIONS = 'locations'.freeze,

      # TODO: Write general description for CONTACT
      CONTACT = 'contact'.freeze,

      # TODO: Write general description for ISDELETABLE
      ISDELETABLE = 'isDeletable'.freeze,

      # TODO: Write general description for ACTIVE_NOTIFICATION_ALERTS
      ACTIVE_NOTIFICATION_ALERTS = 'active_notification_alerts'.freeze,

      # TODO: Write general description for LOCATION_USERS
      LOCATION_USERS = 'location_users'.freeze,

      # TODO: Write general description for AUTH_ROLES
      AUTH_ROLES = 'auth_roles'.freeze,

      # TODO: Write general description for CONTACT_ID
      CONTACT_ID = 'contact_id'.freeze,

      # TODO: Write general description for CHANGELOGS
      CHANGELOGS = 'changelogs'.freeze,

      # TODO: Write general description for RESOURCES
      RESOURCES = 'resources'.freeze,

      # TODO: Write general description for DOMAIN
      DOMAIN = 'domain'.freeze,

      # TODO: Write general description for CREATED_USER
      CREATED_USER = 'created_user'.freeze,

      # TODO: Write general description for LOCATION_MARKETPLACES
      LOCATION_MARKETPLACES = 'location_marketplaces'.freeze,

      # TODO: Write general description for EMAIL_BLACKLIST
      EMAIL_BLACKLIST = 'email_blacklist'.freeze,

      # TODO: Write general description for HELPPAGE
      HELPPAGE = 'helppage'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      EXPAND117_ENUM.include?(value)
    end

    def self.from_value(value, default_value = RECEIVED_EMAILS)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'received_emails' then RECEIVED_EMAILS
      when 'feature_flags' then FEATURE_FLAGS
      when 'primary_location' then PRIMARY_LOCATION
      when 'locations' then LOCATIONS
      when 'contact' then CONTACT
      when 'isdeletable' then ISDELETABLE
      when 'active_notification_alerts' then ACTIVE_NOTIFICATION_ALERTS
      when 'location_users' then LOCATION_USERS
      when 'auth_roles' then AUTH_ROLES
      when 'contact_id' then CONTACT_ID
      when 'changelogs' then CHANGELOGS
      when 'resources' then RESOURCES
      when 'domain' then DOMAIN
      when 'created_user' then CREATED_USER
      when 'location_marketplaces' then LOCATION_MARKETPLACES
      when 'email_blacklist' then EMAIL_BLACKLIST
      when 'helppage' then HELPPAGE
      else
        default_value
      end
    end
  end
end
