# fortis_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module FortisApi
  # expand10.
  class Expand10Enum
    EXPAND10_ENUM = [
      # TODO: Write general description for ADDITIONAL_ACCESS
      ADDITIONAL_ACCESS = 'additional_access'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      EXPAND10_ENUM.include?(value)
    end

    def self.from_value(value, default_value = ADDITIONAL_ACCESS)
      return default_value if value.nil?

      default_value
    end
  end
end
