# fortis_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module FortisApi
  # expand15.
  class Expand15Enum
    EXPAND15_ENUM = [
      # TODO: Write general description for DETAILS
      DETAILS = 'details'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      EXPAND15_ENUM.include?(value)
    end

    def self.from_value(value, default_value = DETAILS)
      return default_value if value.nil?

      default_value
    end
  end
end
