# fortis_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module FortisApi
  # expand47.
  class Expand47Enum
    EXPAND47_ENUM = [
      # TODO: Write general description for LOCATION
      LOCATION = 'location'.freeze,

      # TODO: Write general description for CONTACT
      CONTACT = 'contact'.freeze,

      # TODO: Write general description for TRANSACTIONS
      TRANSACTIONS = 'transactions'.freeze,

      # TODO: Write general description for ACTIVERECURRINGS
      ACTIVERECURRINGS = 'activeRecurrings'.freeze,

      # TODO: Write general description for IS_DELETABLE
      IS_DELETABLE = 'is_deletable'.freeze,

      # TODO: Write general description for SIGNATURE
      SIGNATURE = 'signature'.freeze,

      # TODO: Write general description for CREATED_USER
      CREATED_USER = 'created_user'.freeze,

      # TODO: Write general description for CHANGELOGS
      CHANGELOGS = 'changelogs'.freeze,

      # TODO: Write general description for ACCOUNT_VAULT_CAU_LOGS
      ACCOUNT_VAULT_CAU_LOGS = 'account_vault_cau_logs'.freeze,

      # TODO: Write general description for
      # ACCOUNT_VAULT_CAU_PRODUCT_TRANSACTIONS
      ACCOUNT_VAULT_CAU_PRODUCT_TRANSACTIONS = 'account_vault_cau_product_transactions'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      EXPAND47_ENUM.include?(value)
    end

    def self.from_value(value, default_value = LOCATION)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'location' then LOCATION
      when 'contact' then CONTACT
      when 'transactions' then TRANSACTIONS
      when 'activerecurrings' then ACTIVERECURRINGS
      when 'is_deletable' then IS_DELETABLE
      when 'signature' then SIGNATURE
      when 'created_user' then CREATED_USER
      when 'changelogs' then CHANGELOGS
      when 'account_vault_cau_logs' then ACCOUNT_VAULT_CAU_LOGS
      when 'account_vault_cau_product_transactions' then ACCOUNT_VAULT_CAU_PRODUCT_TRANSACTIONS
      else
        default_value
      end
    end
  end
end
