# fortis_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module FortisApi
  # expand26.
  class Expand26
    EXPAND26 = [
      # TODO: Write general description for LOG_EMAILS
      LOG_EMAILS = 'log_emails'.freeze,

      # TODO: Write general description for CONTACT
      CONTACT = 'contact'.freeze,

      # TODO: Write general description for ACCOUNT_VAULT
      ACCOUNT_VAULT = 'account_vault'.freeze,

      # TODO: Write general description for CREATED_USER
      CREATED_USER = 'created_user'.freeze,

      # TODO: Write general description for TRANSACTIONS
      TRANSACTIONS = 'transactions'.freeze,

      # TODO: Write general description for SIGNATURE
      SIGNATURE = 'signature'.freeze,

      # TODO: Write general description for PAYMENT_SCHEDULE
      PAYMENT_SCHEDULE = 'payment_schedule'.freeze,

      # TODO: Write general description for LOCATION
      LOCATION = 'location'.freeze,

      # TODO: Write general description for PRODUCT_TRANSACTION
      PRODUCT_TRANSACTION = 'product_transaction'.freeze,

      # TODO: Write general description for NEXT_RUN_DATE_MIN
      NEXT_RUN_DATE_MIN = 'next_run_date_min'.freeze,

      # TODO: Write general description for NEXT_RUN_DATE_MAX
      NEXT_RUN_DATE_MAX = 'next_run_date_max'.freeze,

      # TODO: Write general description for TAGS
      TAGS = 'tags'.freeze,

      # TODO: Write general description for ALL_TAGS
      ALL_TAGS = 'all_tags'.freeze,

      # TODO: Write general description for CHANGELOGS
      CHANGELOGS = 'changelogs'.freeze,

      # TODO: Write general description for FORECAST
      FORECAST = 'forecast'.freeze,

      # TODO: Write general description for RECURRING_SPLITS
      RECURRING_SPLITS = 'recurring_splits'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      true
    end

    def self.from_value(value, default_value = LOG_EMAILS)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'log_emails' then LOG_EMAILS
      when 'contact' then CONTACT
      when 'account_vault' then ACCOUNT_VAULT
      when 'created_user' then CREATED_USER
      when 'transactions' then TRANSACTIONS
      when 'signature' then SIGNATURE
      when 'payment_schedule' then PAYMENT_SCHEDULE
      when 'location' then LOCATION
      when 'product_transaction' then PRODUCT_TRANSACTION
      when 'next_run_date_min' then NEXT_RUN_DATE_MIN
      when 'next_run_date_max' then NEXT_RUN_DATE_MAX
      when 'tags' then TAGS
      when 'all_tags' then ALL_TAGS
      when 'changelogs' then CHANGELOGS
      when 'forecast' then FORECAST
      when 'recurring_splits' then RECURRING_SPLITS
      else
        default_value
      end
    end
  end
end
