# fortis_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module FortisApi
  # field43.
  class Field43Enum
    FIELD43_ENUM = [
      # TODO: Write general description for ACCOUNT_VAULT_ID
      ACCOUNT_VAULT_ID = 'account_vault_id'.freeze,

      # TODO: Write general description for TOKEN_ID
      TOKEN_ID = 'token_id'.freeze,

      # TODO: Write general description for CONTACT_ID
      CONTACT_ID = 'contact_id'.freeze,

      # TODO: Write general description for ACCOUNT_VAULT_API_ID
      ACCOUNT_VAULT_API_ID = 'account_vault_api_id'.freeze,

      # TODO: Write general description for TOKEN_API_ID
      TOKEN_API_ID = 'token_api_id'.freeze,

      # TODO: Write general description for _JOI
      _JOI = '_joi'.freeze,

      # TODO: Write general description for ACTIVE
      ACTIVE = 'active'.freeze,

      # TODO: Write general description for DESCRIPTION
      DESCRIPTION = 'description'.freeze,

      # TODO: Write general description for END_DATE
      END_DATE = 'end_date'.freeze,

      # TODO: Write general description for INSTALLMENT_TOTAL_COUNT
      INSTALLMENT_TOTAL_COUNT = 'installment_total_count'.freeze,

      # TODO: Write general description for INTERVAL
      INTERVAL = 'interval'.freeze,

      # TODO: Write general description for INTERVAL_TYPE
      INTERVAL_TYPE = 'interval_type'.freeze,

      # TODO: Write general description for LOCATION_ID
      LOCATION_ID = 'location_id'.freeze,

      # TODO: Write general description for NOTIFICATION_DAYS
      NOTIFICATION_DAYS = 'notification_days'.freeze,

      # TODO: Write general description for PAYMENT_METHOD
      PAYMENT_METHOD = 'payment_method'.freeze,

      # TODO: Write general description for PRODUCT_TRANSACTION_ID
      PRODUCT_TRANSACTION_ID = 'product_transaction_id'.freeze,

      # TODO: Write general description for RECURRING_ID
      RECURRING_ID = 'recurring_id'.freeze,

      # TODO: Write general description for RECURRING_API_ID
      RECURRING_API_ID = 'recurring_api_id'.freeze,

      # TODO: Write general description for START_DATE
      START_DATE = 'start_date'.freeze,

      # TODO: Write general description for STATUS
      STATUS = 'status'.freeze,

      # TODO: Write general description for TRANSACTION_AMOUNT
      TRANSACTION_AMOUNT = 'transaction_amount'.freeze,

      # TODO: Write general description for TERMS_AGREE
      TERMS_AGREE = 'terms_agree'.freeze,

      # TODO: Write general description for TERMS_AGREE_IP
      TERMS_AGREE_IP = 'terms_agree_ip'.freeze,

      # TODO: Write general description for RECURRING_C1
      RECURRING_C1 = 'recurring_c1'.freeze,

      # TODO: Write general description for RECURRING_C2
      RECURRING_C2 = 'recurring_c2'.freeze,

      # TODO: Write general description for RECURRING_C3
      RECURRING_C3 = 'recurring_c3'.freeze,

      # TODO: Write general description for SEND_TO_PROC_AS_RECUR
      SEND_TO_PROC_AS_RECUR = 'send_to_proc_as_recur'.freeze,

      # TODO: Write general description for TAGS
      TAGS = 'tags'.freeze,

      # TODO: Write general description for SECONDARY_AMOUNT
      SECONDARY_AMOUNT = 'secondary_amount'.freeze,

      # TODO: Write general description for CURRENCY
      CURRENCY = 'currency'.freeze,

      # TODO: Write general description for ID
      ID = 'id'.freeze,

      # TODO: Write general description for NEXT_RUN_DATE
      NEXT_RUN_DATE = 'next_run_date'.freeze,

      # TODO: Write general description for CREATED_TS
      CREATED_TS = 'created_ts'.freeze,

      # TODO: Write general description for MODIFIED_TS
      MODIFIED_TS = 'modified_ts'.freeze,

      # TODO: Write general description for RECURRING_TYPE_ID
      RECURRING_TYPE_ID = 'recurring_type_id'.freeze,

      # TODO: Write general description for INSTALLMENT_AMOUNT_TOTAL
      INSTALLMENT_AMOUNT_TOTAL = 'installment_amount_total'.freeze,

      # TODO: Write general description for CREATED_USER_ID
      CREATED_USER_ID = 'created_user_id'.freeze,

      # TODO: Write general description for LOG_EMAILS
      LOG_EMAILS = 'log_emails'.freeze,

      # TODO: Write general description for CONTACT
      CONTACT = 'contact'.freeze,

      # TODO: Write general description for ACCOUNT_VAULT
      ACCOUNT_VAULT = 'account_vault'.freeze,

      # TODO: Write general description for CREATED_USER
      CREATED_USER = 'created_user'.freeze,

      # TODO: Write general description for SIGNATURE
      SIGNATURE = 'signature'.freeze,

      # TODO: Write general description for PAYMENT_SCHEDULE
      PAYMENT_SCHEDULE = 'payment_schedule'.freeze,

      # TODO: Write general description for LOCATION
      LOCATION = 'location'.freeze,

      # TODO: Write general description for PRODUCT_TRANSACTION
      PRODUCT_TRANSACTION = 'product_transaction'.freeze,

      # TODO: Write general description for NEXT_RUN_DATE_MIN
      NEXT_RUN_DATE_MIN = 'next_run_date_min'.freeze,

      # TODO: Write general description for NEXT_RUN_DATE_MAX
      NEXT_RUN_DATE_MAX = 'next_run_date_max'.freeze,

      # TODO: Write general description for ALL_TAGS
      ALL_TAGS = 'all_tags'.freeze,

      # TODO: Write general description for CHANGELOGS
      CHANGELOGS = 'changelogs'.freeze,

      # TODO: Write general description for FORECAST
      FORECAST = 'forecast'.freeze,

      # TODO: Write general description for RECURRING_SPLITS
      RECURRING_SPLITS = 'recurring_splits'.freeze,

      # TODO: Write general description for TRANSACTIONS
      TRANSACTIONS = 'transactions'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      FIELD43_ENUM.include?(value)
    end

    def self.from_value(value, default_value = ACCOUNT_VAULT_ID)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'account_vault_id' then ACCOUNT_VAULT_ID
      when 'token_id' then TOKEN_ID
      when 'contact_id' then CONTACT_ID
      when 'account_vault_api_id' then ACCOUNT_VAULT_API_ID
      when 'token_api_id' then TOKEN_API_ID
      when '_joi' then _JOI
      when 'active' then ACTIVE
      when 'description' then DESCRIPTION
      when 'end_date' then END_DATE
      when 'installment_total_count' then INSTALLMENT_TOTAL_COUNT
      when 'interval' then INTERVAL
      when 'interval_type' then INTERVAL_TYPE
      when 'location_id' then LOCATION_ID
      when 'notification_days' then NOTIFICATION_DAYS
      when 'payment_method' then PAYMENT_METHOD
      when 'product_transaction_id' then PRODUCT_TRANSACTION_ID
      when 'recurring_id' then RECURRING_ID
      when 'recurring_api_id' then RECURRING_API_ID
      when 'start_date' then START_DATE
      when 'status' then STATUS
      when 'transaction_amount' then TRANSACTION_AMOUNT
      when 'terms_agree' then TERMS_AGREE
      when 'terms_agree_ip' then TERMS_AGREE_IP
      when 'recurring_c1' then RECURRING_C1
      when 'recurring_c2' then RECURRING_C2
      when 'recurring_c3' then RECURRING_C3
      when 'send_to_proc_as_recur' then SEND_TO_PROC_AS_RECUR
      when 'tags' then TAGS
      when 'secondary_amount' then SECONDARY_AMOUNT
      when 'currency' then CURRENCY
      when 'id' then ID
      when 'next_run_date' then NEXT_RUN_DATE
      when 'created_ts' then CREATED_TS
      when 'modified_ts' then MODIFIED_TS
      when 'recurring_type_id' then RECURRING_TYPE_ID
      when 'installment_amount_total' then INSTALLMENT_AMOUNT_TOTAL
      when 'created_user_id' then CREATED_USER_ID
      when 'log_emails' then LOG_EMAILS
      when 'contact' then CONTACT
      when 'account_vault' then ACCOUNT_VAULT
      when 'created_user' then CREATED_USER
      when 'signature' then SIGNATURE
      when 'payment_schedule' then PAYMENT_SCHEDULE
      when 'location' then LOCATION
      when 'product_transaction' then PRODUCT_TRANSACTION
      when 'next_run_date_min' then NEXT_RUN_DATE_MIN
      when 'next_run_date_max' then NEXT_RUN_DATE_MAX
      when 'all_tags' then ALL_TAGS
      when 'changelogs' then CHANGELOGS
      when 'forecast' then FORECAST
      when 'recurring_splits' then RECURRING_SPLITS
      when 'transactions' then TRANSACTIONS
      else
        default_value
      end
    end
  end
end
