# fortis_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module FortisApi
  # field49.
  class Field49
    FIELD49 = [
      # TODO: Write general description for LOCATION_ID
      LOCATION_ID = 'location_id'.freeze,

      # TODO: Write general description for DEFAULT_PRODUCT_TRANSACTION_ID
      DEFAULT_PRODUCT_TRANSACTION_ID = 'default_product_transaction_id'.freeze,

      # TODO: Write general description for TERMINAL_APPLICATION_ID
      TERMINAL_APPLICATION_ID = 'terminal_application_id'.freeze,

      # TODO: Write general description for TERMINAL_CVM_ID
      TERMINAL_CVM_ID = 'terminal_cvm_id'.freeze,

      # TODO: Write general description for TERMINAL_MANUFACTURER_CODE
      TERMINAL_MANUFACTURER_CODE = 'terminal_manufacturer_code'.freeze,

      # TODO: Write general description for TITLE
      TITLE = 'title'.freeze,

      # TODO: Write general description for MAC_ADDRESS
      MAC_ADDRESS = 'mac_address'.freeze,

      # TODO: Write general description for LOCAL_IP_ADDRESS
      LOCAL_IP_ADDRESS = 'local_ip_address'.freeze,

      # TODO: Write general description for PORT
      PORT = 'port'.freeze,

      # TODO: Write general description for SERIAL_NUMBER
      SERIAL_NUMBER = 'serial_number'.freeze,

      # TODO: Write general description for TERMINAL_NUMBER
      TERMINAL_NUMBER = 'terminal_number'.freeze,

      # TODO: Write general description for TERMINAL_TIMEOUTS
      TERMINAL_TIMEOUTS = 'terminal_timeouts'.freeze,

      # TODO: Write general description for TIP_PERCENTS
      TIP_PERCENTS = 'tip_percents'.freeze,

      # TODO: Write general description for LOCATION_API_ID
      LOCATION_API_ID = 'location_api_id'.freeze,

      # TODO: Write general description for TERMINAL_API_ID
      TERMINAL_API_ID = 'terminal_api_id'.freeze,

      # TODO: Write general description for HEADER_LINE_1
      HEADER_LINE_1 = 'header_line_1'.freeze,

      # TODO: Write general description for HEADER_LINE_2
      HEADER_LINE_2 = 'header_line_2'.freeze,

      # TODO: Write general description for HEADER_LINE_3
      HEADER_LINE_3 = 'header_line_3'.freeze,

      # TODO: Write general description for HEADER_LINE_4
      HEADER_LINE_4 = 'header_line_4'.freeze,

      # TODO: Write general description for HEADER_LINE_5
      HEADER_LINE_5 = 'header_line_5'.freeze,

      # TODO: Write general description for TRAILER_LINE_1
      TRAILER_LINE_1 = 'trailer_line_1'.freeze,

      # TODO: Write general description for TRAILER_LINE_2
      TRAILER_LINE_2 = 'trailer_line_2'.freeze,

      # TODO: Write general description for TRAILER_LINE_3
      TRAILER_LINE_3 = 'trailer_line_3'.freeze,

      # TODO: Write general description for TRAILER_LINE_4
      TRAILER_LINE_4 = 'trailer_line_4'.freeze,

      # TODO: Write general description for TRAILER_LINE_5
      TRAILER_LINE_5 = 'trailer_line_5'.freeze,

      # TODO: Write general description for DEFAULT_CHECKIN
      DEFAULT_CHECKIN = 'default_checkin'.freeze,

      # TODO: Write general description for DEFAULT_CHECKOUT
      DEFAULT_CHECKOUT = 'default_checkout'.freeze,

      # TODO: Write general description for DEFAULT_ROOM_RATE
      DEFAULT_ROOM_RATE = 'default_room_rate'.freeze,

      # TODO: Write general description for DEFAULT_ROOM_NUMBER
      DEFAULT_ROOM_NUMBER = 'default_room_number'.freeze,

      # TODO: Write general description for DEBIT
      DEBIT = 'debit'.freeze,

      # TODO: Write general description for EMV
      EMV = 'emv'.freeze,

      # TODO: Write general description for CASHBACK_ENABLE
      CASHBACK_ENABLE = 'cashback_enable'.freeze,

      # TODO: Write general description for PRINT_ENABLE
      PRINT_ENABLE = 'print_enable'.freeze,

      # TODO: Write general description for SIG_CAPTURE_ENABLE
      SIG_CAPTURE_ENABLE = 'sig_capture_enable'.freeze,

      # TODO: Write general description for IS_PROVISIONED
      IS_PROVISIONED = 'is_provisioned'.freeze,

      # TODO: Write general description for TIP_ENABLE
      TIP_ENABLE = 'tip_enable'.freeze,

      # TODO: Write general description for VALIDATED_DECRYPTION
      VALIDATED_DECRYPTION = 'validated_decryption'.freeze,

      # TODO: Write general description for COMMUNICATION_TYPE
      COMMUNICATION_TYPE = 'communication_type'.freeze,

      # TODO: Write general description for ACTIVE
      ACTIVE = 'active'.freeze,

      # TODO: Write general description for ID
      ID = 'id'.freeze,

      # TODO: Write general description for CREATED_TS
      CREATED_TS = 'created_ts'.freeze,

      # TODO: Write general description for MODIFIED_TS
      MODIFIED_TS = 'modified_ts'.freeze,

      # TODO: Write general description for LAST_REGISTRATION_TS
      LAST_REGISTRATION_TS = 'last_registration_ts'.freeze,

      # TODO: Write general description for CREATED_USER_ID
      CREATED_USER_ID = 'created_user_id'.freeze,

      # TODO: Write general description for MODIFIED_USER_ID
      MODIFIED_USER_ID = 'modified_user_id'.freeze,

      # TODO: Write general description for LOCATION
      LOCATION = 'location'.freeze,

      # TODO: Write general description for CREATED_USER
      CREATED_USER = 'created_user'.freeze,

      # TODO: Write general description for TERMINAL_APPLICATION
      TERMINAL_APPLICATION = 'terminal_application'.freeze,

      # TODO: Write general description for CHANGELOGS
      CHANGELOGS = 'changelogs'.freeze,

      # TODO: Write general description for TERMINAL_ROUTERS
      TERMINAL_ROUTERS = 'terminal_routers'.freeze,

      # TODO: Write general description for HAS_TERMINAL_ROUTERS
      HAS_TERMINAL_ROUTERS = 'has_terminal_routers'.freeze,

      # TODO: Write general description for TERMINAL_CVM
      TERMINAL_CVM = 'terminal_cvm'.freeze,

      # TODO: Write general description for TERMINAL_MANUFACTURER
      TERMINAL_MANUFACTURER = 'terminal_manufacturer'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      true
    end

    def self.from_value(value, default_value = LOCATION_ID)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'location_id' then LOCATION_ID
      when 'default_product_transaction_id' then DEFAULT_PRODUCT_TRANSACTION_ID
      when 'terminal_application_id' then TERMINAL_APPLICATION_ID
      when 'terminal_cvm_id' then TERMINAL_CVM_ID
      when 'terminal_manufacturer_code' then TERMINAL_MANUFACTURER_CODE
      when 'title' then TITLE
      when 'mac_address' then MAC_ADDRESS
      when 'local_ip_address' then LOCAL_IP_ADDRESS
      when 'port' then PORT
      when 'serial_number' then SERIAL_NUMBER
      when 'terminal_number' then TERMINAL_NUMBER
      when 'terminal_timeouts' then TERMINAL_TIMEOUTS
      when 'tip_percents' then TIP_PERCENTS
      when 'location_api_id' then LOCATION_API_ID
      when 'terminal_api_id' then TERMINAL_API_ID
      when 'header_line_1' then HEADER_LINE_1
      when 'header_line_2' then HEADER_LINE_2
      when 'header_line_3' then HEADER_LINE_3
      when 'header_line_4' then HEADER_LINE_4
      when 'header_line_5' then HEADER_LINE_5
      when 'trailer_line_1' then TRAILER_LINE_1
      when 'trailer_line_2' then TRAILER_LINE_2
      when 'trailer_line_3' then TRAILER_LINE_3
      when 'trailer_line_4' then TRAILER_LINE_4
      when 'trailer_line_5' then TRAILER_LINE_5
      when 'default_checkin' then DEFAULT_CHECKIN
      when 'default_checkout' then DEFAULT_CHECKOUT
      when 'default_room_rate' then DEFAULT_ROOM_RATE
      when 'default_room_number' then DEFAULT_ROOM_NUMBER
      when 'debit' then DEBIT
      when 'emv' then EMV
      when 'cashback_enable' then CASHBACK_ENABLE
      when 'print_enable' then PRINT_ENABLE
      when 'sig_capture_enable' then SIG_CAPTURE_ENABLE
      when 'is_provisioned' then IS_PROVISIONED
      when 'tip_enable' then TIP_ENABLE
      when 'validated_decryption' then VALIDATED_DECRYPTION
      when 'communication_type' then COMMUNICATION_TYPE
      when 'active' then ACTIVE
      when 'id' then ID
      when 'created_ts' then CREATED_TS
      when 'modified_ts' then MODIFIED_TS
      when 'last_registration_ts' then LAST_REGISTRATION_TS
      when 'created_user_id' then CREATED_USER_ID
      when 'modified_user_id' then MODIFIED_USER_ID
      when 'location' then LOCATION
      when 'created_user' then CREATED_USER
      when 'terminal_application' then TERMINAL_APPLICATION
      when 'changelogs' then CHANGELOGS
      when 'terminal_routers' then TERMINAL_ROUTERS
      when 'has_terminal_routers' then HAS_TERMINAL_ROUTERS
      when 'terminal_cvm' then TERMINAL_CVM
      when 'terminal_manufacturer' then TERMINAL_MANUFACTURER
      else
        default_value
      end
    end
  end
end
