# fortis_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module FortisApi
  # field28.
  class Field28
    FIELD28 = [
      # TODO: Write general description for LOCATION_ID
      LOCATION_ID = 'location_id'.freeze,

      # TODO: Write general description for ACCOUNT_NUMBER
      ACCOUNT_NUMBER = 'account_number'.freeze,

      # TODO: Write general description for CONTACT_API_ID
      CONTACT_API_ID = 'contact_api_id'.freeze,

      # TODO: Write general description for FIRST_NAME
      FIRST_NAME = 'first_name'.freeze,

      # TODO: Write general description for LAST_NAME
      LAST_NAME = 'last_name'.freeze,

      # TODO: Write general description for CELL_PHONE
      CELL_PHONE = 'cell_phone'.freeze,

      # TODO: Write general description for BALANCE
      BALANCE = 'balance'.freeze,

      # TODO: Write general description for ADDRESS
      ADDRESS = 'address'.freeze,

      # TODO: Write general description for COMPANY_NAME
      COMPANY_NAME = 'company_name'.freeze,

      # TODO: Write general description for HEADER_MESSAGE
      HEADER_MESSAGE = 'header_message'.freeze,

      # TODO: Write general description for DATE_OF_BIRTH
      DATE_OF_BIRTH = 'date_of_birth'.freeze,

      # TODO: Write general description for EMAIL_TRX_RECEIPT
      EMAIL_TRX_RECEIPT = 'email_trx_receipt'.freeze,

      # TODO: Write general description for HOME_PHONE
      HOME_PHONE = 'home_phone'.freeze,

      # TODO: Write general description for OFFICE_PHONE
      OFFICE_PHONE = 'office_phone'.freeze,

      # TODO: Write general description for OFFICE_PHONE_EXT
      OFFICE_PHONE_EXT = 'office_phone_ext'.freeze,

      # TODO: Write general description for HOME_PHONE_COUNTRY_CODE
      HOME_PHONE_COUNTRY_CODE = 'home_phone_country_code'.freeze,

      # TODO: Write general description for OFFICE_PHONE_COUNTRY_CODE
      OFFICE_PHONE_COUNTRY_CODE = 'office_phone_country_code'.freeze,

      # TODO: Write general description for CELL_PHONE_COUNTRY_CODE
      CELL_PHONE_COUNTRY_CODE = 'cell_phone_country_code'.freeze,

      # TODO: Write general description for HEADER_MESSAGE_TYPE
      HEADER_MESSAGE_TYPE = 'header_message_type'.freeze,

      # TODO: Write general description for UPDATE_IF_EXISTS
      UPDATE_IF_EXISTS = 'update_if_exists'.freeze,

      # TODO: Write general description for CONTACT_C1
      CONTACT_C1 = 'contact_c1'.freeze,

      # TODO: Write general description for CONTACT_C2
      CONTACT_C2 = 'contact_c2'.freeze,

      # TODO: Write general description for CONTACT_C3
      CONTACT_C3 = 'contact_c3'.freeze,

      # TODO: Write general description for PARENT_ID
      PARENT_ID = 'parent_id'.freeze,

      # TODO: Write general description for EMAIL
      EMAIL = 'email'.freeze,

      # TODO: Write general description for TOKEN_IMPORT_ID
      TOKEN_IMPORT_ID = 'token_import_id'.freeze,

      # TODO: Write general description for ID
      ID = 'id'.freeze,

      # TODO: Write general description for CREATED_TS
      CREATED_TS = 'created_ts'.freeze,

      # TODO: Write general description for MODIFIED_TS
      MODIFIED_TS = 'modified_ts'.freeze,

      # TODO: Write general description for ACTIVE
      ACTIVE = 'active'.freeze,

      # TODO: Write general description for CREATED_USER_ID
      CREATED_USER_ID = 'created_user_id'.freeze,

      # TODO: Write general description for RECEIVED_EMAILS
      RECEIVED_EMAILS = 'received_emails'.freeze,

      # TODO: Write general description for IS_DELETABLE
      IS_DELETABLE = 'is_deletable'.freeze,

      # TODO: Write general description for LOCATION
      LOCATION = 'location'.freeze,

      # TODO: Write general description for USER
      USER = 'user'.freeze,

      # TODO: Write general description for RECURRINGS
      RECURRINGS = 'recurrings'.freeze,

      # TODO: Write general description for EMAIL_BLACKLIST
      EMAIL_BLACKLIST = 'email_blacklist'.freeze,

      # TODO: Write general description for SMS_BLACKLIST
      SMS_BLACKLIST = 'sms_blacklist'.freeze,

      # TODO: Write general description for CHANGELOGS
      CHANGELOGS = 'changelogs'.freeze,

      # TODO: Write general description for POSTBACK_LOGS
      POSTBACK_LOGS = 'postback_logs'.freeze,

      # TODO: Write general description for CREATED_USER
      CREATED_USER = 'created_user'.freeze,

      # TODO: Write general description for PARENT
      PARENT = 'parent'.freeze,

      # TODO: Write general description for CHILDREN
      CHILDREN = 'children'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      true
    end

    def self.from_value(value, default_value = LOCATION_ID)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'location_id' then LOCATION_ID
      when 'account_number' then ACCOUNT_NUMBER
      when 'contact_api_id' then CONTACT_API_ID
      when 'first_name' then FIRST_NAME
      when 'last_name' then LAST_NAME
      when 'cell_phone' then CELL_PHONE
      when 'balance' then BALANCE
      when 'address' then ADDRESS
      when 'company_name' then COMPANY_NAME
      when 'header_message' then HEADER_MESSAGE
      when 'date_of_birth' then DATE_OF_BIRTH
      when 'email_trx_receipt' then EMAIL_TRX_RECEIPT
      when 'home_phone' then HOME_PHONE
      when 'office_phone' then OFFICE_PHONE
      when 'office_phone_ext' then OFFICE_PHONE_EXT
      when 'home_phone_country_code' then HOME_PHONE_COUNTRY_CODE
      when 'office_phone_country_code' then OFFICE_PHONE_COUNTRY_CODE
      when 'cell_phone_country_code' then CELL_PHONE_COUNTRY_CODE
      when 'header_message_type' then HEADER_MESSAGE_TYPE
      when 'update_if_exists' then UPDATE_IF_EXISTS
      when 'contact_c1' then CONTACT_C1
      when 'contact_c2' then CONTACT_C2
      when 'contact_c3' then CONTACT_C3
      when 'parent_id' then PARENT_ID
      when 'email' then EMAIL
      when 'token_import_id' then TOKEN_IMPORT_ID
      when 'id' then ID
      when 'created_ts' then CREATED_TS
      when 'modified_ts' then MODIFIED_TS
      when 'active' then ACTIVE
      when 'created_user_id' then CREATED_USER_ID
      when 'received_emails' then RECEIVED_EMAILS
      when 'is_deletable' then IS_DELETABLE
      when 'location' then LOCATION
      when 'user' then USER
      when 'recurrings' then RECURRINGS
      when 'email_blacklist' then EMAIL_BLACKLIST
      when 'sms_blacklist' then SMS_BLACKLIST
      when 'changelogs' then CHANGELOGS
      when 'postback_logs' then POSTBACK_LOGS
      when 'created_user' then CREATED_USER
      when 'parent' then PARENT
      when 'children' then CHILDREN
      else
        default_value
      end
    end
  end
end
