# fortis_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module FortisApi
  # field31.
  class Field31
    FIELD31 = [
      # TODO: Write general description for LOCATION_ID
      LOCATION_ID = 'location_id'.freeze,

      # TODO: Write general description for TERMINAL_ID
      TERMINAL_ID = 'terminal_id'.freeze,

      # TODO: Write general description for REQUIRE_SIGNATURE
      REQUIRE_SIGNATURE = 'require_signature'.freeze,

      # TODO: Write general description for DEVICE_TERM_API_ID
      DEVICE_TERM_API_ID = 'device_term_api_id'.freeze,

      # TODO: Write general description for TERMS_CONDITIONS
      TERMS_CONDITIONS = 'terms_conditions'.freeze,

      # TODO: Write general description for ID
      ID = 'id'.freeze,

      # TODO: Write general description for REASON_CODE_ID
      REASON_CODE_ID = 'reason_code_id'.freeze,

      # TODO: Write general description for SIGNATURE
      SIGNATURE = 'signature'.freeze,

      # TODO: Write general description for CREATED_TS
      CREATED_TS = 'created_ts'.freeze,

      # TODO: Write general description for MODIFIED_TS
      MODIFIED_TS = 'modified_ts'.freeze,

      # TODO: Write general description for CREATED_USER_ID
      CREATED_USER_ID = 'created_user_id'.freeze,

      # TODO: Write general description for CREATED_USER
      CREATED_USER = 'created_user'.freeze,

      # TODO: Write general description for LOCATION
      LOCATION = 'location'.freeze,

      # TODO: Write general description for TERMINAL
      TERMINAL = 'terminal'.freeze,

      # TODO: Write general description for CHANGELOGS
      CHANGELOGS = 'changelogs'.freeze,

      # TODO: Write general description for REASON_CODE
      REASON_CODE = 'reason_code'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      true
    end

    def self.from_value(value, default_value = LOCATION_ID)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'location_id' then LOCATION_ID
      when 'terminal_id' then TERMINAL_ID
      when 'require_signature' then REQUIRE_SIGNATURE
      when 'device_term_api_id' then DEVICE_TERM_API_ID
      when 'terms_conditions' then TERMS_CONDITIONS
      when 'id' then ID
      when 'reason_code_id' then REASON_CODE_ID
      when 'signature' then SIGNATURE
      when 'created_ts' then CREATED_TS
      when 'modified_ts' then MODIFIED_TS
      when 'created_user_id' then CREATED_USER_ID
      when 'created_user' then CREATED_USER
      when 'location' then LOCATION
      when 'terminal' then TERMINAL
      when 'changelogs' then CHANGELOGS
      when 'reason_code' then REASON_CODE
      else
        default_value
      end
    end
  end
end
