# fortis_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module FortisApi
  # File Model.
  class File < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # File Object
    # @return [Object]
    attr_accessor :file

    # Resource Id
    # @return [String]
    attr_accessor :resource_id

    # Resource Id
    # @return [Resource2]
    attr_accessor :resource

    # Product File Id
    # @return [String]
    attr_accessor :product_file_id

    # File Category Id
    # @return [String]
    attr_accessor :file_category_id

    # Visibility Group Id
    # @return [String]
    attr_accessor :visibility_group_id

    # File Description
    # @return [String]
    attr_accessor :file_description

    # Resource
    # @return [String]
    attr_accessor :id

    # File Name
    # @return [String]
    attr_accessor :file_name

    # File Extension
    # @return [String]
    attr_accessor :file_extension

    # File Size Bytes
    # @return [Integer]
    attr_accessor :file_size_bytes

    # Created Time Stamp
    # @return [Integer]
    attr_accessor :created_ts

    # Modified Time Stamp
    # @return [Integer]
    attr_accessor :modified_ts

    # User ID Created the register
    # @return [String]
    attr_accessor :created_user_id

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['file'] = 'file'
      @_hash['resource_id'] = 'resource_id'
      @_hash['resource'] = 'resource'
      @_hash['product_file_id'] = 'product_file_id'
      @_hash['file_category_id'] = 'file_category_id'
      @_hash['visibility_group_id'] = 'visibility_group_id'
      @_hash['file_description'] = 'file_description'
      @_hash['id'] = 'id'
      @_hash['file_name'] = 'file_name'
      @_hash['file_extension'] = 'file_extension'
      @_hash['file_size_bytes'] = 'file_size_bytes'
      @_hash['created_ts'] = 'created_ts'
      @_hash['modified_ts'] = 'modified_ts'
      @_hash['created_user_id'] = 'created_user_id'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        file
        resource_id
        resource
        product_file_id
        file_category_id
        visibility_group_id
        file_description
        id
        file_name
        file_extension
        file_size_bytes
        created_ts
        modified_ts
        created_user_id
      ]
    end

    # An array for nullable fields
    def self.nullables
      %w[
        product_file_id
        file_category_id
        visibility_group_id
        file_description
        file_name
        file_extension
        file_size_bytes
        created_user_id
      ]
    end

    def initialize(file: SKIP, resource_id: SKIP, resource: SKIP,
                   product_file_id: SKIP, file_category_id: SKIP,
                   visibility_group_id: SKIP, file_description: SKIP, id: SKIP,
                   file_name: SKIP, file_extension: SKIP, file_size_bytes: SKIP,
                   created_ts: SKIP, modified_ts: SKIP, created_user_id: SKIP,
                   additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @file = file unless file == SKIP
      @resource_id = resource_id unless resource_id == SKIP
      @resource = resource unless resource == SKIP
      @product_file_id = product_file_id unless product_file_id == SKIP
      @file_category_id = file_category_id unless file_category_id == SKIP
      @visibility_group_id = visibility_group_id unless visibility_group_id == SKIP
      @file_description = file_description unless file_description == SKIP
      @id = id unless id == SKIP
      @file_name = file_name unless file_name == SKIP
      @file_extension = file_extension unless file_extension == SKIP
      @file_size_bytes = file_size_bytes unless file_size_bytes == SKIP
      @created_ts = created_ts unless created_ts == SKIP
      @modified_ts = modified_ts unless modified_ts == SKIP
      @created_user_id = created_user_id unless created_user_id == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      file = hash.key?('file') ? hash['file'] : SKIP
      resource_id = hash.key?('resource_id') ? hash['resource_id'] : SKIP
      resource = hash.key?('resource') ? hash['resource'] : SKIP
      product_file_id =
        hash.key?('product_file_id') ? hash['product_file_id'] : SKIP
      file_category_id =
        hash.key?('file_category_id') ? hash['file_category_id'] : SKIP
      visibility_group_id =
        hash.key?('visibility_group_id') ? hash['visibility_group_id'] : SKIP
      file_description =
        hash.key?('file_description') ? hash['file_description'] : SKIP
      id = hash.key?('id') ? hash['id'] : SKIP
      file_name = hash.key?('file_name') ? hash['file_name'] : SKIP
      file_extension =
        hash.key?('file_extension') ? hash['file_extension'] : SKIP
      file_size_bytes =
        hash.key?('file_size_bytes') ? hash['file_size_bytes'] : SKIP
      created_ts = hash.key?('created_ts') ? hash['created_ts'] : SKIP
      modified_ts = hash.key?('modified_ts') ? hash['modified_ts'] : SKIP
      created_user_id =
        hash.key?('created_user_id') ? hash['created_user_id'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      File.new(file: file,
               resource_id: resource_id,
               resource: resource,
               product_file_id: product_file_id,
               file_category_id: file_category_id,
               visibility_group_id: visibility_group_id,
               file_description: file_description,
               id: id,
               file_name: file_name,
               file_extension: file_extension,
               file_size_bytes: file_size_bytes,
               created_ts: created_ts,
               modified_ts: modified_ts,
               created_user_id: created_user_id,
               additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} file: #{@file}, resource_id: #{@resource_id}, resource: #{@resource},"\
      " product_file_id: #{@product_file_id}, file_category_id: #{@file_category_id},"\
      " visibility_group_id: #{@visibility_group_id}, file_description: #{@file_description}, id:"\
      " #{@id}, file_name: #{@file_name}, file_extension: #{@file_extension}, file_size_bytes:"\
      " #{@file_size_bytes}, created_ts: #{@created_ts}, modified_ts: #{@modified_ts},"\
      " created_user_id: #{@created_user_id}, additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} file: #{@file.inspect}, resource_id: #{@resource_id.inspect}, resource:"\
      " #{@resource.inspect}, product_file_id: #{@product_file_id.inspect}, file_category_id:"\
      " #{@file_category_id.inspect}, visibility_group_id: #{@visibility_group_id.inspect},"\
      " file_description: #{@file_description.inspect}, id: #{@id.inspect}, file_name:"\
      " #{@file_name.inspect}, file_extension: #{@file_extension.inspect}, file_size_bytes:"\
      " #{@file_size_bytes.inspect}, created_ts: #{@created_ts.inspect}, modified_ts:"\
      " #{@modified_ts.inspect}, created_user_id: #{@created_user_id.inspect},"\
      " additional_properties: #{@additional_properties}>"
    end
  end
end
