# fortis_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module FortisApi
  # File2 Model.
  class File2 < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The file name including the extension
    # @return [String]
    attr_accessor :file_name

    # File contents as a base64 encoded string
    # @return [String]
    attr_accessor :content

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['file_name'] = 'file_name'
      @_hash['content'] = 'content'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        file_name
        content
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(file_name = SKIP, content = SKIP, additional_properties = {})
      # Add additional model properties to the instance.
      additional_properties.each do |_name, _value|
        instance_variable_set("@#{_name}", _value)
      end

      @file_name = file_name unless file_name == SKIP
      @content = content unless content == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      file_name = hash.key?('file_name') ? hash['file_name'] : SKIP
      content = hash.key?('content') ? hash['content'] : SKIP

      # Clean out expected properties from Hash.
      additional_properties = hash.reject { |k, _| names.value?(k) }

      # Create object from extracted values.
      File2.new(file_name,
                content,
                additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} file_name: #{@file_name}, content: #{@content}, additional_properties:"\
      " #{get_additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} file_name: #{@file_name.inspect}, content: #{@content.inspect},"\
      " additional_properties: #{get_additional_properties}>"
    end
  end
end
