# fortis_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module FortisApi
  # Hosted Payment Page Information on `expand`
  class HostedPaymentPage < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # User ID
    # @return [String]
    attr_accessor :user_id

    # Location ID
    # @return [String]
    attr_accessor :location_id

    # Location Api Id
    # @return [String]
    attr_accessor :location_api_id

    # Product Transaction ID
    # @return [String]
    attr_accessor :product_transaction_id

    # Title
    # @return [String]
    attr_accessor :title

    # Redirect Url Delay
    # @return [Float]
    attr_accessor :redirect_url_delay

    # Min Payment Amount
    # @return [Integer]
    attr_accessor :min_payment_amount

    # Max Payment Amount
    # @return [Integer]
    attr_accessor :max_payment_amount

    # Redirect Url On Approval
    # @return [String]
    attr_accessor :redirect_url_on_approve

    # Redirect Url On Decline
    # @return [String]
    attr_accessor :redirect_url_on_decline

    # Redirect Url On Decline
    # @return [FieldConfiguration2]
    attr_accessor :field_configuration

    # Encryption Key
    # @return [String]
    attr_accessor :encryption_key

    # Stylesheet Url
    # @return [String]
    attr_accessor :stylesheet_url

    # Parent Send Message
    # @return [TrueClass | FalseClass]
    attr_accessor :parent_send_message

    # Hide Optional Fields
    # @return [TrueClass | FalseClass]
    attr_accessor :hide_optional_fields

    # Hosted Payment Page Id
    # @return [String]
    attr_accessor :id

    # Created Time Stamp
    # @return [Integer]
    attr_accessor :created_ts

    # Modified Time Stamp
    # @return [Integer]
    attr_accessor :modified_ts

    # System generated id for user who created record
    # @return [String]
    attr_accessor :created_user_id

    # System generated id for user who created record
    # @return [String]
    attr_accessor :modified_user_id

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['user_id'] = 'user_id'
      @_hash['location_id'] = 'location_id'
      @_hash['location_api_id'] = 'location_api_id'
      @_hash['product_transaction_id'] = 'product_transaction_id'
      @_hash['title'] = 'title'
      @_hash['redirect_url_delay'] = 'redirect_url_delay'
      @_hash['min_payment_amount'] = 'min_payment_amount'
      @_hash['max_payment_amount'] = 'max_payment_amount'
      @_hash['redirect_url_on_approve'] = 'redirect_url_on_approve'
      @_hash['redirect_url_on_decline'] = 'redirect_url_on_decline'
      @_hash['field_configuration'] = 'field_configuration'
      @_hash['encryption_key'] = 'encryption_key'
      @_hash['stylesheet_url'] = 'stylesheet_url'
      @_hash['parent_send_message'] = 'parent_send_message'
      @_hash['hide_optional_fields'] = 'hide_optional_fields'
      @_hash['id'] = 'id'
      @_hash['created_ts'] = 'created_ts'
      @_hash['modified_ts'] = 'modified_ts'
      @_hash['created_user_id'] = 'created_user_id'
      @_hash['modified_user_id'] = 'modified_user_id'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        user_id
        location_id
        location_api_id
        product_transaction_id
        title
        redirect_url_delay
        min_payment_amount
        max_payment_amount
        redirect_url_on_approve
        redirect_url_on_decline
        field_configuration
        encryption_key
        stylesheet_url
        parent_send_message
        hide_optional_fields
        id
        created_ts
        modified_ts
        created_user_id
        modified_user_id
      ]
    end

    # An array for nullable fields
    def self.nullables
      %w[
        user_id
        location_id
        location_api_id
        redirect_url_delay
        min_payment_amount
        max_payment_amount
        redirect_url_on_approve
        redirect_url_on_decline
        encryption_key
        stylesheet_url
        created_user_id
        modified_user_id
      ]
    end

    def initialize(user_id: SKIP, location_id: SKIP, location_api_id: SKIP,
                   product_transaction_id: SKIP, title: SKIP,
                   redirect_url_delay: 15, min_payment_amount: SKIP,
                   max_payment_amount: 9999999999,
                   redirect_url_on_approve: SKIP, redirect_url_on_decline: SKIP,
                   field_configuration: SKIP, encryption_key: SKIP,
                   stylesheet_url: SKIP, parent_send_message: SKIP,
                   hide_optional_fields: SKIP, id: SKIP, created_ts: SKIP,
                   modified_ts: SKIP, created_user_id: SKIP,
                   modified_user_id: SKIP, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @user_id = user_id unless user_id == SKIP
      @location_id = location_id unless location_id == SKIP
      @location_api_id = location_api_id unless location_api_id == SKIP
      @product_transaction_id = product_transaction_id unless product_transaction_id == SKIP
      @title = title unless title == SKIP
      @redirect_url_delay = redirect_url_delay unless redirect_url_delay == SKIP
      @min_payment_amount = min_payment_amount unless min_payment_amount == SKIP
      @max_payment_amount = max_payment_amount unless max_payment_amount == SKIP
      @redirect_url_on_approve = redirect_url_on_approve unless redirect_url_on_approve == SKIP
      @redirect_url_on_decline = redirect_url_on_decline unless redirect_url_on_decline == SKIP
      @field_configuration = field_configuration unless field_configuration == SKIP
      @encryption_key = encryption_key unless encryption_key == SKIP
      @stylesheet_url = stylesheet_url unless stylesheet_url == SKIP
      @parent_send_message = parent_send_message unless parent_send_message == SKIP
      @hide_optional_fields = hide_optional_fields unless hide_optional_fields == SKIP
      @id = id unless id == SKIP
      @created_ts = created_ts unless created_ts == SKIP
      @modified_ts = modified_ts unless modified_ts == SKIP
      @created_user_id = created_user_id unless created_user_id == SKIP
      @modified_user_id = modified_user_id unless modified_user_id == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      user_id = hash.key?('user_id') ? hash['user_id'] : SKIP
      location_id = hash.key?('location_id') ? hash['location_id'] : SKIP
      location_api_id =
        hash.key?('location_api_id') ? hash['location_api_id'] : SKIP
      product_transaction_id =
        hash.key?('product_transaction_id') ? hash['product_transaction_id'] : SKIP
      title = hash.key?('title') ? hash['title'] : SKIP
      redirect_url_delay = hash['redirect_url_delay'] ||= 15
      min_payment_amount =
        hash.key?('min_payment_amount') ? hash['min_payment_amount'] : SKIP
      max_payment_amount = hash['max_payment_amount'] ||= 9999999999
      redirect_url_on_approve =
        hash.key?('redirect_url_on_approve') ? hash['redirect_url_on_approve'] : SKIP
      redirect_url_on_decline =
        hash.key?('redirect_url_on_decline') ? hash['redirect_url_on_decline'] : SKIP
      field_configuration = FieldConfiguration2.from_hash(hash['field_configuration']) if
        hash['field_configuration']
      encryption_key =
        hash.key?('encryption_key') ? hash['encryption_key'] : SKIP
      stylesheet_url =
        hash.key?('stylesheet_url') ? hash['stylesheet_url'] : SKIP
      parent_send_message =
        hash.key?('parent_send_message') ? hash['parent_send_message'] : SKIP
      hide_optional_fields =
        hash.key?('hide_optional_fields') ? hash['hide_optional_fields'] : SKIP
      id = hash.key?('id') ? hash['id'] : SKIP
      created_ts = hash.key?('created_ts') ? hash['created_ts'] : SKIP
      modified_ts = hash.key?('modified_ts') ? hash['modified_ts'] : SKIP
      created_user_id =
        hash.key?('created_user_id') ? hash['created_user_id'] : SKIP
      modified_user_id =
        hash.key?('modified_user_id') ? hash['modified_user_id'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      HostedPaymentPage.new(user_id: user_id,
                            location_id: location_id,
                            location_api_id: location_api_id,
                            product_transaction_id: product_transaction_id,
                            title: title,
                            redirect_url_delay: redirect_url_delay,
                            min_payment_amount: min_payment_amount,
                            max_payment_amount: max_payment_amount,
                            redirect_url_on_approve: redirect_url_on_approve,
                            redirect_url_on_decline: redirect_url_on_decline,
                            field_configuration: field_configuration,
                            encryption_key: encryption_key,
                            stylesheet_url: stylesheet_url,
                            parent_send_message: parent_send_message,
                            hide_optional_fields: hide_optional_fields,
                            id: id,
                            created_ts: created_ts,
                            modified_ts: modified_ts,
                            created_user_id: created_user_id,
                            modified_user_id: modified_user_id,
                            additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} user_id: #{@user_id}, location_id: #{@location_id}, location_api_id:"\
      " #{@location_api_id}, product_transaction_id: #{@product_transaction_id}, title: #{@title},"\
      " redirect_url_delay: #{@redirect_url_delay}, min_payment_amount: #{@min_payment_amount},"\
      " max_payment_amount: #{@max_payment_amount}, redirect_url_on_approve:"\
      " #{@redirect_url_on_approve}, redirect_url_on_decline: #{@redirect_url_on_decline},"\
      " field_configuration: #{@field_configuration}, encryption_key: #{@encryption_key},"\
      " stylesheet_url: #{@stylesheet_url}, parent_send_message: #{@parent_send_message},"\
      " hide_optional_fields: #{@hide_optional_fields}, id: #{@id}, created_ts: #{@created_ts},"\
      " modified_ts: #{@modified_ts}, created_user_id: #{@created_user_id}, modified_user_id:"\
      " #{@modified_user_id}, additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} user_id: #{@user_id.inspect}, location_id: #{@location_id.inspect},"\
      " location_api_id: #{@location_api_id.inspect}, product_transaction_id:"\
      " #{@product_transaction_id.inspect}, title: #{@title.inspect}, redirect_url_delay:"\
      " #{@redirect_url_delay.inspect}, min_payment_amount: #{@min_payment_amount.inspect},"\
      " max_payment_amount: #{@max_payment_amount.inspect}, redirect_url_on_approve:"\
      " #{@redirect_url_on_approve.inspect}, redirect_url_on_decline:"\
      " #{@redirect_url_on_decline.inspect}, field_configuration: #{@field_configuration.inspect},"\
      " encryption_key: #{@encryption_key.inspect}, stylesheet_url: #{@stylesheet_url.inspect},"\
      " parent_send_message: #{@parent_send_message.inspect}, hide_optional_fields:"\
      " #{@hide_optional_fields.inspect}, id: #{@id.inspect}, created_ts: #{@created_ts.inspect},"\
      " modified_ts: #{@modified_ts.inspect}, created_user_id: #{@created_user_id.inspect},"\
      " modified_user_id: #{@modified_user_id.inspect}, additional_properties:"\
      " #{@additional_properties}>"
    end
  end
end
