# fortis_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module FortisApi
  # LocationBillingAccount Model.
  class LocationBillingAccount < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Title
    # @return [String]
    attr_accessor :title

    # Location ID
    # @return [String]
    attr_accessor :location_id

    # Location Api Id
    # @return [String]
    attr_accessor :location_api_id

    # Ach Sec Code
    # @return [String]
    attr_accessor :ach_sec_code

    # Account number
    # @return [String]
    attr_accessor :account_number

    # Routing
    # @return [String]
    attr_accessor :routing

    # Exp Date
    # @return [String]
    attr_accessor :exp_date

    # Billing Zip
    # @return [String]
    attr_accessor :billing_zip

    # Account Type
    # @return [String]
    attr_accessor :account_type

    # Account Holder Name
    # @return [String]
    attr_accessor :account_holder_name

    # Location Billing Account Id
    # @return [String]
    attr_accessor :id

    # Created Time Stamp
    # @return [Integer]
    attr_accessor :created_ts

    # Modified Time Stamp
    # @return [Integer]
    attr_accessor :modified_ts

    # Created User Id
    # @return [String]
    attr_accessor :created_user_id

    # Modified User Id
    # @return [String]
    attr_accessor :modified_user_id

    # Billing Descriptor
    # @return [String]
    attr_accessor :billing_descriptor

    # Billing Descriptor
    # @return [String]
    attr_accessor :payment_method

    # Portfolio Id
    # @return [String]
    attr_accessor :portfolio_id

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['title'] = 'title'
      @_hash['location_id'] = 'location_id'
      @_hash['location_api_id'] = 'location_api_id'
      @_hash['ach_sec_code'] = 'ach_sec_code'
      @_hash['account_number'] = 'account_number'
      @_hash['routing'] = 'routing'
      @_hash['exp_date'] = 'exp_date'
      @_hash['billing_zip'] = 'billing_zip'
      @_hash['account_type'] = 'account_type'
      @_hash['account_holder_name'] = 'account_holder_name'
      @_hash['id'] = 'id'
      @_hash['created_ts'] = 'created_ts'
      @_hash['modified_ts'] = 'modified_ts'
      @_hash['created_user_id'] = 'created_user_id'
      @_hash['modified_user_id'] = 'modified_user_id'
      @_hash['billing_descriptor'] = 'billing_descriptor'
      @_hash['payment_method'] = 'payment_method'
      @_hash['portfolio_id'] = 'portfolio_id'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        title
        location_id
        location_api_id
        ach_sec_code
        account_number
        routing
        exp_date
        billing_zip
        account_type
        account_holder_name
        id
        created_ts
        modified_ts
        created_user_id
        modified_user_id
        billing_descriptor
        payment_method
        portfolio_id
      ]
    end

    # An array for nullable fields
    def self.nullables
      %w[
        location_id
        location_api_id
        ach_sec_code
        account_number
        routing
        exp_date
        billing_zip
        account_type
        account_holder_name
        created_user_id
        modified_user_id
        billing_descriptor
        payment_method
      ]
    end

    def initialize(title = SKIP, location_id = SKIP, location_api_id = SKIP,
                   ach_sec_code = SKIP, account_number = SKIP, routing = SKIP,
                   exp_date = SKIP, billing_zip = SKIP, account_type = SKIP,
                   account_holder_name = SKIP, id = SKIP, created_ts = SKIP,
                   modified_ts = SKIP, created_user_id = SKIP,
                   modified_user_id = SKIP, billing_descriptor = SKIP,
                   payment_method = SKIP, portfolio_id = SKIP,
                   additional_properties = {})
      # Add additional model properties to the instance.
      additional_properties.each do |_name, _value|
        instance_variable_set("@#{_name}", _value)
      end

      @title = title unless title == SKIP
      @location_id = location_id unless location_id == SKIP
      @location_api_id = location_api_id unless location_api_id == SKIP
      @ach_sec_code = ach_sec_code unless ach_sec_code == SKIP
      @account_number = account_number unless account_number == SKIP
      @routing = routing unless routing == SKIP
      @exp_date = exp_date unless exp_date == SKIP
      @billing_zip = billing_zip unless billing_zip == SKIP
      @account_type = account_type unless account_type == SKIP
      @account_holder_name = account_holder_name unless account_holder_name == SKIP
      @id = id unless id == SKIP
      @created_ts = created_ts unless created_ts == SKIP
      @modified_ts = modified_ts unless modified_ts == SKIP
      @created_user_id = created_user_id unless created_user_id == SKIP
      @modified_user_id = modified_user_id unless modified_user_id == SKIP
      @billing_descriptor = billing_descriptor unless billing_descriptor == SKIP
      @payment_method = payment_method unless payment_method == SKIP
      @portfolio_id = portfolio_id unless portfolio_id == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      title = hash.key?('title') ? hash['title'] : SKIP
      location_id = hash.key?('location_id') ? hash['location_id'] : SKIP
      location_api_id =
        hash.key?('location_api_id') ? hash['location_api_id'] : SKIP
      ach_sec_code = hash.key?('ach_sec_code') ? hash['ach_sec_code'] : SKIP
      account_number =
        hash.key?('account_number') ? hash['account_number'] : SKIP
      routing = hash.key?('routing') ? hash['routing'] : SKIP
      exp_date = hash.key?('exp_date') ? hash['exp_date'] : SKIP
      billing_zip = hash.key?('billing_zip') ? hash['billing_zip'] : SKIP
      account_type = hash.key?('account_type') ? hash['account_type'] : SKIP
      account_holder_name =
        hash.key?('account_holder_name') ? hash['account_holder_name'] : SKIP
      id = hash.key?('id') ? hash['id'] : SKIP
      created_ts = hash.key?('created_ts') ? hash['created_ts'] : SKIP
      modified_ts = hash.key?('modified_ts') ? hash['modified_ts'] : SKIP
      created_user_id =
        hash.key?('created_user_id') ? hash['created_user_id'] : SKIP
      modified_user_id =
        hash.key?('modified_user_id') ? hash['modified_user_id'] : SKIP
      billing_descriptor =
        hash.key?('billing_descriptor') ? hash['billing_descriptor'] : SKIP
      payment_method =
        hash.key?('payment_method') ? hash['payment_method'] : SKIP
      portfolio_id = hash.key?('portfolio_id') ? hash['portfolio_id'] : SKIP

      # Clean out expected properties from Hash.
      additional_properties = hash.reject { |k, _| names.value?(k) }

      # Create object from extracted values.
      LocationBillingAccount.new(title,
                                 location_id,
                                 location_api_id,
                                 ach_sec_code,
                                 account_number,
                                 routing,
                                 exp_date,
                                 billing_zip,
                                 account_type,
                                 account_holder_name,
                                 id,
                                 created_ts,
                                 modified_ts,
                                 created_user_id,
                                 modified_user_id,
                                 billing_descriptor,
                                 payment_method,
                                 portfolio_id,
                                 additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} title: #{@title}, location_id: #{@location_id}, location_api_id:"\
      " #{@location_api_id}, ach_sec_code: #{@ach_sec_code}, account_number: #{@account_number},"\
      " routing: #{@routing}, exp_date: #{@exp_date}, billing_zip: #{@billing_zip}, account_type:"\
      " #{@account_type}, account_holder_name: #{@account_holder_name}, id: #{@id}, created_ts:"\
      " #{@created_ts}, modified_ts: #{@modified_ts}, created_user_id: #{@created_user_id},"\
      " modified_user_id: #{@modified_user_id}, billing_descriptor: #{@billing_descriptor},"\
      " payment_method: #{@payment_method}, portfolio_id: #{@portfolio_id}, additional_properties:"\
      " #{get_additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} title: #{@title.inspect}, location_id: #{@location_id.inspect},"\
      " location_api_id: #{@location_api_id.inspect}, ach_sec_code: #{@ach_sec_code.inspect},"\
      " account_number: #{@account_number.inspect}, routing: #{@routing.inspect}, exp_date:"\
      " #{@exp_date.inspect}, billing_zip: #{@billing_zip.inspect}, account_type:"\
      " #{@account_type.inspect}, account_holder_name: #{@account_holder_name.inspect}, id:"\
      " #{@id.inspect}, created_ts: #{@created_ts.inspect}, modified_ts: #{@modified_ts.inspect},"\
      " created_user_id: #{@created_user_id.inspect}, modified_user_id:"\
      " #{@modified_user_id.inspect}, billing_descriptor: #{@billing_descriptor.inspect},"\
      " payment_method: #{@payment_method.inspect}, portfolio_id: #{@portfolio_id.inspect},"\
      " additional_properties: #{get_additional_properties}>"
    end
  end
end
