# fortis_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module FortisApi
  # Contains purchase information
  class MerchantRiskIndicator < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [ShipIndicator]
    attr_accessor :ship_indicator

    # TODO: Write general description for this method
    # @return [DeliveryTimeframe]
    attr_accessor :delivery_timeframe

    # For electronic delivery, the email address to which the merchandise was
    # delivered.
    # @return [String]
    attr_accessor :delivery_email_address

    # For electronic delivery, the email address to which the merchandise was
    # delivered.
    # @return [ReorderItemsInd]
    attr_accessor :reorder_items_ind

    # For electronic delivery, the email address to which the merchandise was
    # delivered.
    # @return [PreOrderPurchaseInd]
    attr_accessor :pre_order_purchase_ind

    # For a pre-ordered purchase, the expected date that the merchandise will be
    # available. Date format must be YYYYMMDD.
    # @return [String]
    attr_accessor :pre_order_date

    # For prepaid or gift card purchase, the purchase amount total of prepaid or
    # gift card(s) in major units (for example, USD 123.45 is 123).
    # @return [Integer]
    attr_accessor :gift_card_amount

    # For prepaid or gift card purchase, the currency code of the card as
    # defined in ISO 4217 except 955 - 964 and 999.
    # @return [String]
    attr_accessor :gift_card_curr

    # For prepaid or gift card purchase, total count of individual prepaid or
    # gift cards/codes purchased.
    # @return [Integer]
    attr_accessor :gift_card_count

    # Available starting in EMV 3DS 2.3.1.1.  Indicates to the ACS specific
    # transactions identified by the Merchant.
    # >01 - Cryptocurrency transaction
    # >
    # >02 - NFT transaction
    # >
    # @return [Array[TransChar]]
    attr_accessor :trans_char

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['ship_indicator'] = 'ship_indicator'
      @_hash['delivery_timeframe'] = 'delivery_timeframe'
      @_hash['delivery_email_address'] = 'delivery_email_address'
      @_hash['reorder_items_ind'] = 'reorder_items_ind'
      @_hash['pre_order_purchase_ind'] = 'pre_order_purchase_ind'
      @_hash['pre_order_date'] = 'pre_order_date'
      @_hash['gift_card_amount'] = 'gift_card_amount'
      @_hash['gift_card_curr'] = 'gift_card_curr'
      @_hash['gift_card_count'] = 'gift_card_count'
      @_hash['trans_char'] = 'trans_char'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        ship_indicator
        delivery_timeframe
        delivery_email_address
        reorder_items_ind
        pre_order_purchase_ind
        pre_order_date
        gift_card_amount
        gift_card_curr
        gift_card_count
        trans_char
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(ship_indicator: SKIP, delivery_timeframe: SKIP,
                   delivery_email_address: SKIP, reorder_items_ind: SKIP,
                   pre_order_purchase_ind: SKIP, pre_order_date: SKIP,
                   gift_card_amount: SKIP, gift_card_curr: SKIP,
                   gift_card_count: SKIP, trans_char: SKIP,
                   additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @ship_indicator = ship_indicator unless ship_indicator == SKIP
      @delivery_timeframe = delivery_timeframe unless delivery_timeframe == SKIP
      @delivery_email_address = delivery_email_address unless delivery_email_address == SKIP
      @reorder_items_ind = reorder_items_ind unless reorder_items_ind == SKIP
      @pre_order_purchase_ind = pre_order_purchase_ind unless pre_order_purchase_ind == SKIP
      @pre_order_date = pre_order_date unless pre_order_date == SKIP
      @gift_card_amount = gift_card_amount unless gift_card_amount == SKIP
      @gift_card_curr = gift_card_curr unless gift_card_curr == SKIP
      @gift_card_count = gift_card_count unless gift_card_count == SKIP
      @trans_char = trans_char unless trans_char == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      ship_indicator =
        hash.key?('ship_indicator') ? hash['ship_indicator'] : SKIP
      delivery_timeframe =
        hash.key?('delivery_timeframe') ? hash['delivery_timeframe'] : SKIP
      delivery_email_address =
        hash.key?('delivery_email_address') ? hash['delivery_email_address'] : SKIP
      reorder_items_ind =
        hash.key?('reorder_items_ind') ? hash['reorder_items_ind'] : SKIP
      pre_order_purchase_ind =
        hash.key?('pre_order_purchase_ind') ? hash['pre_order_purchase_ind'] : SKIP
      pre_order_date =
        hash.key?('pre_order_date') ? hash['pre_order_date'] : SKIP
      gift_card_amount =
        hash.key?('gift_card_amount') ? hash['gift_card_amount'] : SKIP
      gift_card_curr =
        hash.key?('gift_card_curr') ? hash['gift_card_curr'] : SKIP
      gift_card_count =
        hash.key?('gift_card_count') ? hash['gift_card_count'] : SKIP
      trans_char = hash.key?('trans_char') ? hash['trans_char'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      MerchantRiskIndicator.new(ship_indicator: ship_indicator,
                                delivery_timeframe: delivery_timeframe,
                                delivery_email_address: delivery_email_address,
                                reorder_items_ind: reorder_items_ind,
                                pre_order_purchase_ind: pre_order_purchase_ind,
                                pre_order_date: pre_order_date,
                                gift_card_amount: gift_card_amount,
                                gift_card_curr: gift_card_curr,
                                gift_card_count: gift_card_count,
                                trans_char: trans_char,
                                additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} ship_indicator: #{@ship_indicator}, delivery_timeframe:"\
      " #{@delivery_timeframe}, delivery_email_address: #{@delivery_email_address},"\
      " reorder_items_ind: #{@reorder_items_ind}, pre_order_purchase_ind:"\
      " #{@pre_order_purchase_ind}, pre_order_date: #{@pre_order_date}, gift_card_amount:"\
      " #{@gift_card_amount}, gift_card_curr: #{@gift_card_curr}, gift_card_count:"\
      " #{@gift_card_count}, trans_char: #{@trans_char}, additional_properties:"\
      " #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} ship_indicator: #{@ship_indicator.inspect}, delivery_timeframe:"\
      " #{@delivery_timeframe.inspect}, delivery_email_address:"\
      " #{@delivery_email_address.inspect}, reorder_items_ind: #{@reorder_items_ind.inspect},"\
      " pre_order_purchase_ind: #{@pre_order_purchase_ind.inspect}, pre_order_date:"\
      " #{@pre_order_date.inspect}, gift_card_amount: #{@gift_card_amount.inspect},"\
      " gift_card_curr: #{@gift_card_curr.inspect}, gift_card_count: #{@gift_card_count.inspect},"\
      " trans_char: #{@trans_char.inspect}, additional_properties: #{@additional_properties}>"
    end
  end
end
