# fortis_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module FortisApi
  # Meta Model.
  class Meta < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Error detail
    # @return [Array[Detail]]
    attr_accessor :details

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['details'] = 'details'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        details
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(details: SKIP, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @details = details unless details == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      details = nil
      unless hash['details'].nil?
        details = []
        hash['details'].each do |structure|
          details << (Detail.from_hash(structure) if structure)
        end
      end

      details = SKIP unless hash.key?('details')

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      Meta.new(details: details,
               additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} details: #{@details}, additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} details: #{@details.inspect}, additional_properties:"\
      " #{@additional_properties}>"
    end
  end
end
