# fortis_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module FortisApi
  # Method3 Model.
  class Method3 < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Payment type. Must be unique.
    # @return [Type29Enum]
    attr_accessor :type

    # The product_transaction_id of the cc or ach deposit account that the
    # transaction is inteded for. Use only the cc or ach id to display their
    # respective elements form only. The Product's method (cc/ach) has to match
    # the type.
    # @return [String]
    attr_accessor :product_transaction_id

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['type'] = 'type'
      @_hash['product_transaction_id'] = 'product_transaction_id'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        type
        product_transaction_id
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(type = SKIP, product_transaction_id = SKIP,
                   additional_properties = {})
      # Add additional model properties to the instance.
      additional_properties.each do |_name, _value|
        instance_variable_set("@#{_name}", _value)
      end

      @type = type unless type == SKIP
      @product_transaction_id = product_transaction_id unless product_transaction_id == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      type = hash.key?('type') ? hash['type'] : SKIP
      product_transaction_id =
        hash.key?('product_transaction_id') ? hash['product_transaction_id'] : SKIP

      # Clean out expected properties from Hash.
      additional_properties = hash.reject { |k, _| names.value?(k) }

      # Create object from extracted values.
      Method3.new(type,
                  product_transaction_id,
                  additional_properties)
    end

    # Validates an instance of the object from a given value.
    # @param [Method3 | Hash] The value against the validation is performed.
    def self.validate(value)
      return true if value.instance_of? self

      return false unless value.instance_of? Hash

      true
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} type: #{@type}, product_transaction_id: #{@product_transaction_id},"\
      " additional_properties: #{get_additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} type: #{@type.inspect}, product_transaction_id:"\
      " #{@product_transaction_id.inspect}, additional_properties: #{get_additional_properties}>"
    end
  end
end
