# fortis_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module FortisApi
  # Method5.
  class Method5
    METHOD5 = [
      # TODO: Write general description for OXOR
      OXOR = 'oxor'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      true
    end

    def self.from_value(value, default_value = OXOR)
      return default_value if value.nil?

      default_value
    end
  end
end
