# fortis_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module FortisApi
  # The mobile phone provided by the Cardholder. Refer to ITU-E.164 for
  # additional information on format and length. This field is required if
  # available, unless market or regional mandate restricts sending this
  # information.
  class MobilePhone < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Country Code of the phone
    # @return [String]
    attr_accessor :cc

    # Subscriber section of the number
    # @return [String]
    attr_accessor :subscriber

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['cc'] = 'cc'
      @_hash['subscriber'] = 'subscriber'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        cc
        subscriber
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(cc: SKIP, subscriber: SKIP, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @cc = cc unless cc == SKIP
      @subscriber = subscriber unless subscriber == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      cc = hash.key?('cc') ? hash['cc'] : SKIP
      subscriber = hash.key?('subscriber') ? hash['subscriber'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      MobilePhone.new(cc: cc,
                      subscriber: subscriber,
                      additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} cc: #{@cc}, subscriber: #{@subscriber}, additional_properties:"\
      " #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} cc: #{@cc.inspect}, subscriber: #{@subscriber.inspect},"\
      " additional_properties: #{@additional_properties}>"
    end
  end
end
