# fortis_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module FortisApi
  # the action that will be used by the form when making the payment possible
  # values: sale, auth-only
  class PaylinkActionEnum
    PAYLINK_ACTION_ENUM = [
      # TODO: Write general description for SALE
      SALE = 'sale'.freeze,

      # TODO: Write general description for AUTHONLY
      AUTHONLY = 'auth-only'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      PAYLINK_ACTION_ENUM.include?(value)
    end

    def self.from_value(value, default_value = SALE)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'sale' then SALE
      when 'authonly' then AUTHONLY
      else
        default_value
      end
    end
  end
end
