# fortis_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module FortisApi
  # Postback Status Id
  class PostbackStatusId
    POSTBACK_STATUS_ID = [
      # TODO: Write general description for ENUM_1
      ENUM_1 = 1,

      # TODO: Write general description for ENUM_2
      ENUM_2 = 2,

      # TODO: Write general description for ENUM_3
      ENUM_3 = 3,

      # TODO: Write general description for ENUM_4
      ENUM_4 = 4
    ].freeze

    def self.validate(value)
      return false if value.nil?

      true
    end

    def self.from_value(value, default_value = ENUM_1)
      return default_value if value.nil?

      str = value.to_s.strip
      if str.match?(/\A\d+\z/)
        num = str.to_i
        return num if POSTBACK_STATUS_ID.include?(num)

        return default_value
      end

      case str.downcase
      when 'enum_1' then ENUM_1
      when 'enum_2' then ENUM_2
      when 'enum_3' then ENUM_3
      when 'enum_4' then ENUM_4
      else
        default_value
      end
    end
  end
end
