# fortis_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module FortisApi
  # Specifies the preferred version of 3D Secure protocol to be utilized while
  # executing 3D Secure authentication. 3DS Server initiates an authentication
  # request with the preferred version and if this version is not supported by
  # other 3D Secure components, it falls back to the next supported version(s)
  # and continues authentication. If the preferred version is enforced by
  # setting  #enforcePreferredProtocolVersion flag, but this version is not
  # supported by one of the 3D Secure components, 3DS Server does not initiate
  # an authentication and provides corresponding error message to the customer.
  # If no value is provided, EMV 3DS 2.1.0 version will be used by default.
  # >2.1.0 - prefer authentication with 2.1.0 version > >2.2.0 - prefer
  # authentication with 2.2.0 version > >2.3.1 - prefer authentication with
  # 2.3.1 version >
  class PreferredProtocolVersionEnum
    PREFERRED_PROTOCOL_VERSION_ENUM = [
      # TODO: Write general description for ENUM_210
      ENUM_210 = '2.1.0'.freeze,

      # TODO: Write general description for ENUM_220
      ENUM_220 = '2.2.0'.freeze,

      # TODO: Write general description for ENUM_231
      ENUM_231 = '2.3.1'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      PREFERRED_PROTOCOL_VERSION_ENUM.include?(value)
    end

    def self.from_value(value, default_value = ENUM_210)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'enum_210' then ENUM_210
      when 'enum_220' then ENUM_220
      when 'enum_231' then ENUM_231
      else
        default_value
      end
    end
  end
end
