# fortis_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module FortisApi
  # Processor
  class ProcessorEnum
    PROCESSOR_ENUM = [
      # TODO: Write general description for ZGATE
      ZGATE = 'zgate'.freeze,

      # TODO: Write general description for ZGATE2
      ZGATE2 = 'zgate2'.freeze,

      # TODO: Write general description for ZACH
      ZACH = 'zach'.freeze,

      # TODO: Write general description for ACH
      ACH = 'ach'.freeze,

      # TODO: Write general description for FORTISACH
      FORTISACH = 'fortisach'.freeze,

      # TODO: Write general description for CASH
      CASH = 'cash'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      PROCESSOR_ENUM.include?(value)
    end

    def self.from_value(value, default_value = ZGATE)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'zgate' then ZGATE
      when 'zgate2' then ZGATE2
      when 'zach' then ZACH
      when 'ach' then ACH
      when 'fortisach' then FORTISACH
      when 'cash' then CASH
      else
        default_value
      end
    end
  end
end
