# fortis_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module FortisApi
  # ResponseOnboarding Model.
  class ResponseOnboarding < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Resource Type
    # @return [Type52Enum]
    attr_accessor :type

    # Resource Type
    # @return [Data15]
    attr_accessor :data

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['type'] = 'type'
      @_hash['data'] = 'data'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        type
        data
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(type = Type52Enum::ONBOARDING, data = SKIP,
                   additional_properties = {})
      # Add additional model properties to the instance.
      additional_properties.each do |_name, _value|
        instance_variable_set("@#{_name}", _value)
      end

      @type = type unless type == SKIP
      @data = data unless data == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      type = hash['type'] ||= Type52Enum::ONBOARDING
      data = Data15.from_hash(hash['data']) if hash['data']

      # Clean out expected properties from Hash.
      additional_properties = hash.reject { |k, _| names.value?(k) }

      # Create object from extracted values.
      ResponseOnboarding.new(type,
                             data,
                             additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} type: #{@type}, data: #{@data}, additional_properties:"\
      " #{get_additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} type: #{@type.inspect}, data: #{@data.inspect}, additional_properties:"\
      " #{get_additional_properties}>"
    end
  end
end
