# fortis_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module FortisApi
  # Settings Model.
  class Settings < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Enabled
    # @return [TrueClass | FalseClass]
    attr_accessor :enabled

    # Columns
    # @return [Float]
    attr_accessor :columns

    # Rows
    # @return [Float]
    attr_accessor :rows

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['enabled'] = 'enabled'
      @_hash['columns'] = 'columns'
      @_hash['rows'] = 'rows'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        enabled
        columns
        rows
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(enabled = SKIP, columns = SKIP, rows = SKIP,
                   additional_properties = {})
      # Add additional model properties to the instance.
      additional_properties.each do |_name, _value|
        instance_variable_set("@#{_name}", _value)
      end

      @enabled = enabled unless enabled == SKIP
      @columns = columns unless columns == SKIP
      @rows = rows unless rows == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      enabled = hash.key?('enabled') ? hash['enabled'] : SKIP
      columns = hash.key?('columns') ? hash['columns'] : SKIP
      rows = hash.key?('rows') ? hash['rows'] : SKIP

      # Clean out expected properties from Hash.
      additional_properties = hash.reject { |k, _| names.value?(k) }

      # Create object from extracted values.
      Settings.new(enabled,
                   columns,
                   rows,
                   additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} enabled: #{@enabled}, columns: #{@columns}, rows: #{@rows},"\
      " additional_properties: #{get_additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} enabled: #{@enabled.inspect}, columns: #{@columns.inspect}, rows:"\
      " #{@rows.inspect}, additional_properties: #{get_additional_properties}>"
    end
  end
end
