# fortis_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module FortisApi
  # Settings Model.
  class Settings < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Enabled
    # @return [TrueClass | FalseClass]
    attr_accessor :enabled

    # Columns
    # @return [Float]
    attr_accessor :columns

    # Rows
    # @return [Float]
    attr_accessor :rows

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['enabled'] = 'enabled'
      @_hash['columns'] = 'columns'
      @_hash['rows'] = 'rows'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        enabled
        columns
        rows
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(enabled: SKIP, columns: SKIP, rows: SKIP,
                   additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @enabled = enabled unless enabled == SKIP
      @columns = columns unless columns == SKIP
      @rows = rows unless rows == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      enabled = hash.key?('enabled') ? hash['enabled'] : SKIP
      columns = hash.key?('columns') ? hash['columns'] : SKIP
      rows = hash.key?('rows') ? hash['rows'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      Settings.new(enabled: enabled,
                   columns: columns,
                   rows: rows,
                   additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} enabled: #{@enabled}, columns: #{@columns}, rows: #{@rows},"\
      " additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} enabled: #{@enabled.inspect}, columns: #{@columns.inspect}, rows:"\
      " #{@rows.inspect}, additional_properties: #{@additional_properties}>"
    end
  end
end
