# fortis_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module FortisApi
  # TagTransaction Model.
  class TagTransaction < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # ID
    # @return [String]
    attr_accessor :id

    # Tag
    # @return [String]
    attr_accessor :tag_id

    # Transaction ID
    # @return [String]
    attr_accessor :transaction_id

    # Payment Method
    # @return [String]
    attr_accessor :payment_method

    # Created
    # @return [String]
    attr_accessor :created

    # Modified
    # @return [String]
    attr_accessor :modified

    # Created Time Stamp
    # @return [Integer]
    attr_accessor :created_ts

    # Modified Time Stamp
    # @return [Integer]
    attr_accessor :modified_ts

    # User ID Created the register
    # @return [String]
    attr_accessor :created_user_id

    # Last User ID that updated the register
    # @return [String]
    attr_accessor :modified_user_id

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['id'] = 'id'
      @_hash['tag_id'] = 'tag_id'
      @_hash['transaction_id'] = 'transaction_id'
      @_hash['payment_method'] = 'payment_method'
      @_hash['created'] = 'created'
      @_hash['modified'] = 'modified'
      @_hash['created_ts'] = 'created_ts'
      @_hash['modified_ts'] = 'modified_ts'
      @_hash['created_user_id'] = 'created_user_id'
      @_hash['modified_user_id'] = 'modified_user_id'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        id
        tag_id
        transaction_id
        payment_method
        created
        modified
        created_ts
        modified_ts
        created_user_id
        modified_user_id
      ]
    end

    # An array for nullable fields
    def self.nullables
      %w[
        payment_method
        created
        modified
        created_ts
        modified_ts
        created_user_id
        modified_user_id
      ]
    end

    def initialize(id = SKIP, tag_id = SKIP, transaction_id = SKIP,
                   payment_method = SKIP, created = SKIP, modified = SKIP,
                   created_ts = SKIP, modified_ts = SKIP,
                   created_user_id = SKIP, modified_user_id = SKIP,
                   additional_properties = {})
      # Add additional model properties to the instance.
      additional_properties.each do |_name, _value|
        instance_variable_set("@#{_name}", _value)
      end

      @id = id unless id == SKIP
      @tag_id = tag_id unless tag_id == SKIP
      @transaction_id = transaction_id unless transaction_id == SKIP
      @payment_method = payment_method unless payment_method == SKIP
      @created = created unless created == SKIP
      @modified = modified unless modified == SKIP
      @created_ts = created_ts unless created_ts == SKIP
      @modified_ts = modified_ts unless modified_ts == SKIP
      @created_user_id = created_user_id unless created_user_id == SKIP
      @modified_user_id = modified_user_id unless modified_user_id == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      id = hash.key?('id') ? hash['id'] : SKIP
      tag_id = hash.key?('tag_id') ? hash['tag_id'] : SKIP
      transaction_id =
        hash.key?('transaction_id') ? hash['transaction_id'] : SKIP
      payment_method =
        hash.key?('payment_method') ? hash['payment_method'] : SKIP
      created = hash.key?('created') ? hash['created'] : SKIP
      modified = hash.key?('modified') ? hash['modified'] : SKIP
      created_ts = hash.key?('created_ts') ? hash['created_ts'] : SKIP
      modified_ts = hash.key?('modified_ts') ? hash['modified_ts'] : SKIP
      created_user_id =
        hash.key?('created_user_id') ? hash['created_user_id'] : SKIP
      modified_user_id =
        hash.key?('modified_user_id') ? hash['modified_user_id'] : SKIP

      # Clean out expected properties from Hash.
      additional_properties = hash.reject { |k, _| names.value?(k) }

      # Create object from extracted values.
      TagTransaction.new(id,
                         tag_id,
                         transaction_id,
                         payment_method,
                         created,
                         modified,
                         created_ts,
                         modified_ts,
                         created_user_id,
                         modified_user_id,
                         additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} id: #{@id}, tag_id: #{@tag_id}, transaction_id: #{@transaction_id},"\
      " payment_method: #{@payment_method}, created: #{@created}, modified: #{@modified},"\
      " created_ts: #{@created_ts}, modified_ts: #{@modified_ts}, created_user_id:"\
      " #{@created_user_id}, modified_user_id: #{@modified_user_id}, additional_properties:"\
      " #{get_additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} id: #{@id.inspect}, tag_id: #{@tag_id.inspect}, transaction_id:"\
      " #{@transaction_id.inspect}, payment_method: #{@payment_method.inspect}, created:"\
      " #{@created.inspect}, modified: #{@modified.inspect}, created_ts: #{@created_ts.inspect},"\
      " modified_ts: #{@modified_ts.inspect}, created_user_id: #{@created_user_id.inspect},"\
      " modified_user_id: #{@modified_user_id.inspect}, additional_properties:"\
      " #{get_additional_properties}>"
    end
  end
end
