# fortis_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module FortisApi
  # How the transaction was obtained by the API. >1 - Unknown - The origination
  # of this transaction could not be determined. > >2 - Mobile - The origination
  # of this transaction is through the mobile application. This is always a
  # merchant submitted payment. > >3 - Web - The origination of this transaction
  # is through a web browser. This is always a merchant submitted payment.
  # Examples include Virtual Terminal, Contact Charge, and Transaction Details -
  # Run Again pages. > >4 - IVR Transaction - The origination of this
  # transaction is over the phone. This payment is submitted by an automated
  # system initiated by the cardholder. > >5 - Contact Statement - The
  # orignation of this transaction is through a Vericle statement. > >6 -
  # Contact Payment Mobile - The origination of this transaction is through the
  # mobile application. This is always submitted by a contact user.  > >7 -
  # Contact Payment - The origination of this transaction is through a web
  # browser. This is always submitted by a contact user. > >8 - Quick Invoice -
  # The orignation of this transaction is through a Quick Invoice. This is
  # typically submitted by a contact user, however the transaction can also be
  # submitted by a merchant. > >9 - Payform - The origination of this
  # transaction is through a Payform. This is typically a merchant submitted
  # transaction, and is always from an internal developer. > >10 - Hosted
  # Payment Page - The orignation of this transaction is through a Hosted
  # Payment Page. This is typically a cardholder submitted transaction. > >11 -
  # Emulator -  The origination of this transaction is through Auth.Net
  # emulator. This is typically submitted through an integration to a website or
  # a shopping cart. > >12 - Integration - The orignation of this transaction is
  # through an integrated solution. This will always be from an external
  # developer. > >13 - Recurring Billing - The orignation of this transaction is
  # through a scheduled recurring payment. This payment is system-initiated
  # based on a payment schedule that has been configured. > >14 - Recurring
  # Secondary - This feature has not been implented yet. > >15 - Declined
  # Recurring Email - The orignation of this transaction is through the email
  # notification sent when a recurring payment has been declined. This is
  # typically submitted by a cardholder. > >16 - Paylink - The orignation of
  # this transaction is through a Paylink. This is typically submitted by a
  # contact user, however the transaction can also be submitted by a merchant. >
  # >17 - Elements - The origination of this transaction is through the Elements
  # payments page. This can be a cardholder submitted or a merchant submitted
  # transaction. > >18 - ACH Import - The origination of this transaction is
  # through an ACH file import. This is a merchant initiated process. >
  class TrxSourceId
    TRX_SOURCE_ID = [
      # TODO: Write general description for ENUM_1
      ENUM_1 = 1,

      # TODO: Write general description for ENUM_2
      ENUM_2 = 2,

      # TODO: Write general description for ENUM_3
      ENUM_3 = 3,

      # TODO: Write general description for ENUM_4
      ENUM_4 = 4,

      # TODO: Write general description for ENUM_5
      ENUM_5 = 5,

      # TODO: Write general description for ENUM_6
      ENUM_6 = 6,

      # TODO: Write general description for ENUM_7
      ENUM_7 = 7,

      # TODO: Write general description for ENUM_8
      ENUM_8 = 8,

      # TODO: Write general description for ENUM_9
      ENUM_9 = 9,

      # TODO: Write general description for ENUM_10
      ENUM_10 = 10,

      # TODO: Write general description for ENUM_11
      ENUM_11 = 11,

      # TODO: Write general description for ENUM_12
      ENUM_12 = 12,

      # TODO: Write general description for ENUM_13
      ENUM_13 = 13,

      # TODO: Write general description for ENUM_14
      ENUM_14 = 14,

      # TODO: Write general description for ENUM_15
      ENUM_15 = 15,

      # TODO: Write general description for ENUM_16
      ENUM_16 = 16,

      # TODO: Write general description for ENUM_17
      ENUM_17 = 17,

      # TODO: Write general description for ENUM_18
      ENUM_18 = 18
    ].freeze

    def self.validate(value)
      return false if value.nil?

      true
    end

    def self.from_value(value, default_value = ENUM_1)
      return default_value if value.nil?

      str = value.to_s.strip
      if str.match?(/\A\d+\z/)
        num = str.to_i
        return num if TRX_SOURCE_ID.include?(num)

        return default_value
      end

      case str.downcase
      when 'enum_1' then ENUM_1
      when 'enum_2' then ENUM_2
      when 'enum_3' then ENUM_3
      when 'enum_4' then ENUM_4
      when 'enum_5' then ENUM_5
      when 'enum_6' then ENUM_6
      when 'enum_7' then ENUM_7
      when 'enum_8' then ENUM_8
      when 'enum_9' then ENUM_9
      when 'enum_10' then ENUM_10
      when 'enum_11' then ENUM_11
      when 'enum_12' then ENUM_12
      when 'enum_13' then ENUM_13
      when 'enum_14' then ENUM_14
      when 'enum_15' then ENUM_15
      when 'enum_16' then ENUM_16
      when 'enum_17' then ENUM_17
      when 'enum_18' then ENUM_18
      else
        default_value
      end
    end
  end
end
