# fortis_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module FortisApi
  # Resource Type
  class Type61Enum
    TYPE61_ENUM = [
      # TODO: Write general description for QUICKINVOICERESEND
      QUICKINVOICERESEND = 'QuickInvoiceResend'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      TYPE61_ENUM.include?(value)
    end

    def self.from_value(value, default_value = QUICKINVOICERESEND)
      return default_value if value.nil?

      default_value
    end
  end
end
