# fortis_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module FortisApi
  # Resource Type
  class Type130
    TYPE130 = [
      # TODO: Write general description for USERSCOLLECTION
      USERSCOLLECTION = 'UsersCollection'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      true
    end

    def self.from_value(value, default_value = USERSCOLLECTION)
      return default_value if value.nil?

      default_value
    end
  end
end
