# fortis_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module FortisApi
  # Resource Type
  class Type72Enum
    TYPE72_ENUM = [
      # TODO: Write general description for SIGNATURE
      SIGNATURE = 'Signature'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      TYPE72_ENUM.include?(value)
    end

    def self.from_value(value, default_value = SIGNATURE)
      return default_value if value.nil?

      default_value
    end
  end
end
