# fortis_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module FortisApi
  # Resource Type
  class Type113Enum
    TYPE113_ENUM = [
      # TODO: Write general description for TRANSACTIONBININFO
      TRANSACTIONBININFO = 'TransactionBinInfo'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      TYPE113_ENUM.include?(value)
    end

    def self.from_value(value, default_value = TRANSACTIONBININFO)
      return default_value if value.nil?

      default_value
    end
  end
end
