# fortis_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module FortisApi
  # Resource Type
  class Type92Enum
    TYPE92_ENUM = [
      # TODO: Write general description for TOKEN
      TOKEN = 'Token'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      TYPE92_ENUM.include?(value)
    end

    def self.from_value(value, default_value = TOKEN)
      return default_value if value.nil?

      default_value
    end
  end
end
