# fortis_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module FortisApi
  # Resource Type
  class Type136
    TYPE136 = [
      # TODO: Write general description for APPLEPAYVALIDATEMERCHANT
      APPLEPAYVALIDATEMERCHANT = 'ApplePayValidateMerchant'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      true
    end

    def self.from_value(value, default_value = APPLEPAYVALIDATEMERCHANT)
      return default_value if value.nil?

      default_value
    end
  end
end
