# fortis_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module FortisApi
  # Update If Exists
  class UpdateIfExists
    UPDATE_IF_EXISTS = [
      # TODO: Write general description for ENUM_1
      ENUM_1 = 1
    ].freeze

    def self.validate(value)
      return false if value.nil?

      true
    end

    def self.from_value(value, default_value = ENUM_1)
      return default_value if value.nil?

      default_value
    end
  end
end
