# fortis_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module FortisApi
  # V1ElementsTransactionIntentionRequest Model.
  class V1ElementsTransactionIntentionRequest < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [Object]
    attr_accessor :action

    # TODO: Write general description for this method
    # @return [TrueClass | FalseClass]
    attr_accessor :digital_wallets_only

    # By default the system will try to offer all the availables payment methods
    # from your account. However, if you need to display only cc or ach only use
    # the corresponding product transaction id.
    # @return [Array[Method50]]
    attr_accessor :methods

    # The total transaction amount to be charged with the transaction intention.
    # Allowed on the actions: `sale`, `auth-only`, `refund`
    # @return [Integer]
    attr_accessor :amount

    # Amount of Sales Tax. If supplied, this amount should be already included
    # in the transaction amount. Allowed on the actions: `sale`, `auth-only`,
    # `refund`
    # @return [Integer]
    attr_accessor :tax_amount

    # secondary_amount is used as a mechanism for partners to collect platform
    # or SaAs fees at a transaction level. This field is intended for use with
    # ISV integrations not standalone merchant integrations. Allowed on the
    # actions: `sale`, `auth-only`.
    # @return [Integer]
    attr_accessor :secondary_amount

    # Location ID
    # @return [String]
    attr_accessor :location_id

    # Contact ID
    # @return [String]
    attr_accessor :contact_id

    # Specifies to tokenize card/bank information within the transaction.
    # Allowed on the actions: `sale`, `auth-only`, `avs-only`, `refund`. Do not
    # include with `tokeniation` action.
    # @return [TrueClass | FalseClass]
    attr_accessor :save_account

    # Specifies to tokenize card/bank information within the transaction.
    # Allowed on the actions: `sale`, `auth-only`, `avs-only`, `refund`. Do not
    # include with `tokeniation` action.
    # @return [String]
    attr_accessor :save_account_title

    # A title for the token.
    # @return [String]
    attr_accessor :title

    # A title for the token.
    # @return [Object]
    attr_accessor :ach_sec_code

    # Bank Funded Only Override. Force the use of a bank funded debit card on
    # debit repayment type transactions.
    # @return [TrueClass | FalseClass]
    attr_accessor :bank_funded_only_override

    # Allow partial Authorization Override. Must have Fortis approval for
    # production access.
    # @return [TrueClass | FalseClass]
    attr_accessor :allow_partial_authorization_override

    # Auto Decline Cvv Override
    # @return [TrueClass | FalseClass]
    attr_accessor :auto_decline_cvv_override

    # Auto Decline Street Override
    # @return [TrueClass | FalseClass]
    attr_accessor :auto_decline_street_override

    # Auto Decline Zip Override
    # @return [TrueClass | FalseClass]
    attr_accessor :auto_decline_zip_override

    # A custom text message that displays after the payment is processed.
    # @return [String]
    attr_accessor :message

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['action'] = 'action'
      @_hash['digital_wallets_only'] = 'digitalWalletsOnly'
      @_hash['methods'] = 'methods'
      @_hash['amount'] = 'amount'
      @_hash['tax_amount'] = 'tax_amount'
      @_hash['secondary_amount'] = 'secondary_amount'
      @_hash['location_id'] = 'location_id'
      @_hash['contact_id'] = 'contact_id'
      @_hash['save_account'] = 'save_account'
      @_hash['save_account_title'] = 'save_account_title'
      @_hash['title'] = 'title'
      @_hash['ach_sec_code'] = 'ach_sec_code'
      @_hash['bank_funded_only_override'] = 'bank_funded_only_override'
      @_hash['allow_partial_authorization_override'] =
        'allow_partial_authorization_override'
      @_hash['auto_decline_cvv_override'] = 'auto_decline_cvv_override'
      @_hash['auto_decline_street_override'] = 'auto_decline_street_override'
      @_hash['auto_decline_zip_override'] = 'auto_decline_zip_override'
      @_hash['message'] = 'message'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        action
        digital_wallets_only
        methods
        amount
        tax_amount
        secondary_amount
        location_id
        contact_id
        save_account
        save_account_title
        title
        ach_sec_code
        bank_funded_only_override
        allow_partial_authorization_override
        auto_decline_cvv_override
        auto_decline_street_override
        auto_decline_zip_override
        message
      ]
    end

    # An array for nullable fields
    def self.nullables
      %w[
        location_id
        contact_id
        message
      ]
    end

    def initialize(action: SKIP, digital_wallets_only: false, methods: SKIP,
                   amount: SKIP, tax_amount: SKIP, secondary_amount: SKIP,
                   location_id: SKIP, contact_id: SKIP, save_account: SKIP,
                   save_account_title: SKIP, title: SKIP, ach_sec_code: SKIP,
                   bank_funded_only_override: SKIP,
                   allow_partial_authorization_override: SKIP,
                   auto_decline_cvv_override: SKIP,
                   auto_decline_street_override: SKIP,
                   auto_decline_zip_override: SKIP, message: SKIP,
                   additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @action = action unless action == SKIP
      @digital_wallets_only = digital_wallets_only unless digital_wallets_only == SKIP
      @methods = methods unless methods == SKIP
      @amount = amount unless amount == SKIP
      @tax_amount = tax_amount unless tax_amount == SKIP
      @secondary_amount = secondary_amount unless secondary_amount == SKIP
      @location_id = location_id unless location_id == SKIP
      @contact_id = contact_id unless contact_id == SKIP
      @save_account = save_account unless save_account == SKIP
      @save_account_title = save_account_title unless save_account_title == SKIP
      @title = title unless title == SKIP
      @ach_sec_code = ach_sec_code unless ach_sec_code == SKIP
      unless bank_funded_only_override == SKIP
        @bank_funded_only_override =
          bank_funded_only_override
      end
      unless allow_partial_authorization_override == SKIP
        @allow_partial_authorization_override =
          allow_partial_authorization_override
      end
      unless auto_decline_cvv_override == SKIP
        @auto_decline_cvv_override =
          auto_decline_cvv_override
      end
      unless auto_decline_street_override == SKIP
        @auto_decline_street_override =
          auto_decline_street_override
      end
      unless auto_decline_zip_override == SKIP
        @auto_decline_zip_override =
          auto_decline_zip_override
      end
      @message = message unless message == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      action = hash.key?('action') ? hash['action'] : SKIP
      digital_wallets_only = hash['digitalWalletsOnly'] ||= false
      # Parameter is an array, so we need to iterate through it
      methods = nil
      unless hash['methods'].nil?
        methods = []
        hash['methods'].each do |structure|
          methods << (Method50.from_hash(structure) if structure)
        end
      end

      methods = SKIP unless hash.key?('methods')
      amount = hash.key?('amount') ? hash['amount'] : SKIP
      tax_amount = hash.key?('tax_amount') ? hash['tax_amount'] : SKIP
      secondary_amount =
        hash.key?('secondary_amount') ? hash['secondary_amount'] : SKIP
      location_id = hash.key?('location_id') ? hash['location_id'] : SKIP
      contact_id = hash.key?('contact_id') ? hash['contact_id'] : SKIP
      save_account = hash.key?('save_account') ? hash['save_account'] : SKIP
      save_account_title =
        hash.key?('save_account_title') ? hash['save_account_title'] : SKIP
      title = hash.key?('title') ? hash['title'] : SKIP
      ach_sec_code = hash.key?('ach_sec_code') ? hash['ach_sec_code'] : SKIP
      bank_funded_only_override =
        hash.key?('bank_funded_only_override') ? hash['bank_funded_only_override'] : SKIP
      allow_partial_authorization_override =
        hash.key?('allow_partial_authorization_override') ? hash['allow_partial_authorization_override'] : SKIP
      auto_decline_cvv_override =
        hash.key?('auto_decline_cvv_override') ? hash['auto_decline_cvv_override'] : SKIP
      auto_decline_street_override =
        hash.key?('auto_decline_street_override') ? hash['auto_decline_street_override'] : SKIP
      auto_decline_zip_override =
        hash.key?('auto_decline_zip_override') ? hash['auto_decline_zip_override'] : SKIP
      message = hash.key?('message') ? hash['message'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      V1ElementsTransactionIntentionRequest.new(action: action,
                                                digital_wallets_only: digital_wallets_only,
                                                methods: methods,
                                                amount: amount,
                                                tax_amount: tax_amount,
                                                secondary_amount: secondary_amount,
                                                location_id: location_id,
                                                contact_id: contact_id,
                                                save_account: save_account,
                                                save_account_title: save_account_title,
                                                title: title,
                                                ach_sec_code: ach_sec_code,
                                                bank_funded_only_override: bank_funded_only_override,
                                                allow_partial_authorization_override: allow_partial_authorization_override,
                                                auto_decline_cvv_override: auto_decline_cvv_override,
                                                auto_decline_street_override: auto_decline_street_override,
                                                auto_decline_zip_override: auto_decline_zip_override,
                                                message: message,
                                                additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} action: #{@action}, digital_wallets_only: #{@digital_wallets_only},"\
      " methods: #{@methods}, amount: #{@amount}, tax_amount: #{@tax_amount}, secondary_amount:"\
      " #{@secondary_amount}, location_id: #{@location_id}, contact_id: #{@contact_id},"\
      " save_account: #{@save_account}, save_account_title: #{@save_account_title}, title:"\
      " #{@title}, ach_sec_code: #{@ach_sec_code}, bank_funded_only_override:"\
      " #{@bank_funded_only_override}, allow_partial_authorization_override:"\
      " #{@allow_partial_authorization_override}, auto_decline_cvv_override:"\
      " #{@auto_decline_cvv_override}, auto_decline_street_override:"\
      " #{@auto_decline_street_override}, auto_decline_zip_override:"\
      " #{@auto_decline_zip_override}, message: #{@message}, additional_properties:"\
      " #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} action: #{@action.inspect}, digital_wallets_only:"\
      " #{@digital_wallets_only.inspect}, methods: #{@methods.inspect}, amount:"\
      " #{@amount.inspect}, tax_amount: #{@tax_amount.inspect}, secondary_amount:"\
      " #{@secondary_amount.inspect}, location_id: #{@location_id.inspect}, contact_id:"\
      " #{@contact_id.inspect}, save_account: #{@save_account.inspect}, save_account_title:"\
      " #{@save_account_title.inspect}, title: #{@title.inspect}, ach_sec_code:"\
      " #{@ach_sec_code.inspect}, bank_funded_only_override:"\
      " #{@bank_funded_only_override.inspect}, allow_partial_authorization_override:"\
      " #{@allow_partial_authorization_override.inspect}, auto_decline_cvv_override:"\
      " #{@auto_decline_cvv_override.inspect}, auto_decline_street_override:"\
      " #{@auto_decline_street_override.inspect}, auto_decline_zip_override:"\
      " #{@auto_decline_zip_override.inspect}, message: #{@message.inspect},"\
      " additional_properties: #{@additional_properties}>"
    end
  end
end
