# fortis_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module FortisApi
  # V1OnboardingRequest Model.
  class V1OnboardingRequest < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Location ID
    # @return [String]
    attr_accessor :parent_id

    # Location ID
    # @return [PrimaryPrincipal2]
    attr_accessor :primary_principal

    # The ID of the template to be used - this value will be provided by Fortis.
    # @return [String]
    attr_accessor :template_code

    # Merchant email address.
    # @return [String]
    attr_accessor :email

    # Merchant 'Doing Business As' name.
    # @return [String]
    attr_accessor :dba_name

    # Merchant 'Doing Business As' name.
    # @return [Location19]
    attr_accessor :location

    # Merchant 'Doing Business As' name.
    # @return [AppDelivery]
    attr_accessor :app_delivery

    # Merchant 'Doing Business As' name.
    # @return [Object]
    attr_accessor :business_category

    # Merchant 'Doing Business As' name.
    # @return [Object]
    attr_accessor :business_type

    # Description of Goods or Services.
    # @return [String]
    attr_accessor :business_description

    # Card present/swiped percentage
    # >The sum total of "swiped_percent", "keyed_percent" and
    # "ecommerce_percent" must add up to 100.
    # >
    # @return [Integer]
    attr_accessor :swiped_percent

    # Card not present/keyed percentage
    # >The sum total of "swiped_percent", "keyed_percent" and
    # "ecommerce_percent" must add up to 100.
    # >
    # @return [Integer]
    attr_accessor :keyed_percent

    # eCommerce percentage.
    # >The sum total of "swiped_percent", "keyed_percent" and
    # "ecommerce_percent" must add up to 100.
    # >
    # @return [Integer]
    attr_accessor :ecommerce_percent

    # eCommerce percentage.
    # >The sum total of "swiped_percent", "keyed_percent" and
    # "ecommerce_percent" must add up to 100.
    # >
    # @return [Object]
    attr_accessor :ownership_type

    # Federal Tax ID (EIN).
    # @return [String]
    attr_accessor :fed_tax_id

    # Average Transaction Amount Range
    # >(Applicable when Template Application Type is 'credit_card' or 'both').
    # >
    # @return [Integer]
    attr_accessor :cc_average_ticket_range

    # Monthly Processing Volume Range
    # >(Applicable when Template Application Type is 'credit_card' or 'both').
    # >
    # @return [Integer]
    attr_accessor :cc_monthly_volume_range

    # Highest transaction amount rounded to the next dollar
    # > (No decimal and applicable when Template Application Type is
    # 'credit_card' or 'both').
    # >
    # @return [Integer]
    attr_accessor :cc_high_ticket

    # Average Transaction Amount Range
    # >(Applicable when Template Application Type is 'echeck' or 'both').
    # >
    # @return [Integer]
    attr_accessor :ec_average_ticket_range

    # Monthly Processing Volume Range
    # >(Applicable when Template Application Type is 'echeck' or 'both').
    # >
    # @return [Integer]
    attr_accessor :ec_monthly_volume_range

    # Highest transaction amount rounded to the next dollar
    # >(No decimal and applicable when Template Application Type is 'echeck' or
    # 'both').
    # >
    # @return [Integer]
    attr_accessor :ec_high_ticket

    # Merchant's business website.
    # >(Required if "ecommerce_percent" is greater than 0).
    # >
    # @return [String]
    attr_accessor :website

    # Merchant's business website.
    # >(Required if "ecommerce_percent" is greater than 0).
    # >
    # @return [BankAccount3]
    attr_accessor :bank_account

    # Merchant's business website.
    # >(Required if "ecommerce_percent" is greater than 0).
    # >
    # @return [AltBankAccount2]
    attr_accessor :alt_bank_account

    # Merchant legal name.
    # >(leave blank if same as DBA name).
    # >
    # @return [String]
    attr_accessor :legal_name

    # Merchant legal name.
    # >(leave blank if same as DBA name).
    # >
    # @return [Contact13]
    attr_accessor :contact

    # Client Issues Id to track that can be used to track each submitted
    # merchant application. This id should be generated and sent in the request
    # payload, and will be returned in the response payload. If no id is
    # submitted in the payload request, this field will be null in the response.
    # @return [String]
    attr_accessor :client_app_id

    # Array of SEC codes that will be allowed, Only applicable for ACH. Valid
    # values are 'PPD', 'WEB', 'TEL', 'CCD'.
    # @return [Array[SecCode]]
    attr_accessor :sec_codes

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['parent_id'] = 'parent_id'
      @_hash['primary_principal'] = 'primary_principal'
      @_hash['template_code'] = 'template_code'
      @_hash['email'] = 'email'
      @_hash['dba_name'] = 'dba_name'
      @_hash['location'] = 'location'
      @_hash['app_delivery'] = 'app_delivery'
      @_hash['business_category'] = 'business_category'
      @_hash['business_type'] = 'business_type'
      @_hash['business_description'] = 'business_description'
      @_hash['swiped_percent'] = 'swiped_percent'
      @_hash['keyed_percent'] = 'keyed_percent'
      @_hash['ecommerce_percent'] = 'ecommerce_percent'
      @_hash['ownership_type'] = 'ownership_type'
      @_hash['fed_tax_id'] = 'fed_tax_id'
      @_hash['cc_average_ticket_range'] = 'cc_average_ticket_range'
      @_hash['cc_monthly_volume_range'] = 'cc_monthly_volume_range'
      @_hash['cc_high_ticket'] = 'cc_high_ticket'
      @_hash['ec_average_ticket_range'] = 'ec_average_ticket_range'
      @_hash['ec_monthly_volume_range'] = 'ec_monthly_volume_range'
      @_hash['ec_high_ticket'] = 'ec_high_ticket'
      @_hash['website'] = 'website'
      @_hash['bank_account'] = 'bank_account'
      @_hash['alt_bank_account'] = 'alt_bank_account'
      @_hash['legal_name'] = 'legal_name'
      @_hash['contact'] = 'contact'
      @_hash['client_app_id'] = 'client_app_id'
      @_hash['sec_codes'] = 'sec_codes'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        parent_id
        business_category
        business_type
        business_description
        swiped_percent
        keyed_percent
        ecommerce_percent
        ownership_type
        fed_tax_id
        cc_average_ticket_range
        cc_monthly_volume_range
        cc_high_ticket
        ec_average_ticket_range
        ec_monthly_volume_range
        ec_high_ticket
        website
        bank_account
        alt_bank_account
        legal_name
        client_app_id
        sec_codes
      ]
    end

    # An array for nullable fields
    def self.nullables
      %w[
        parent_id
        business_description
        swiped_percent
        keyed_percent
        ecommerce_percent
        fed_tax_id
        cc_average_ticket_range
        cc_monthly_volume_range
        cc_high_ticket
        ec_average_ticket_range
        ec_monthly_volume_range
        ec_high_ticket
        website
        legal_name
        client_app_id
      ]
    end

    def initialize(primary_principal:, template_code:, email:, dba_name:,
                   location:, app_delivery:, contact:, parent_id: SKIP,
                   business_category: SKIP, business_type: SKIP,
                   business_description: SKIP, swiped_percent: SKIP,
                   keyed_percent: SKIP, ecommerce_percent: SKIP,
                   ownership_type: SKIP, fed_tax_id: SKIP,
                   cc_average_ticket_range: SKIP, cc_monthly_volume_range: SKIP,
                   cc_high_ticket: SKIP, ec_average_ticket_range: SKIP,
                   ec_monthly_volume_range: SKIP, ec_high_ticket: SKIP,
                   website: SKIP, bank_account: SKIP, alt_bank_account: SKIP,
                   legal_name: SKIP, client_app_id: SKIP, sec_codes: SKIP,
                   additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @parent_id = parent_id unless parent_id == SKIP
      @primary_principal = primary_principal
      @template_code = template_code
      @email = email
      @dba_name = dba_name
      @location = location
      @app_delivery = app_delivery
      @business_category = business_category unless business_category == SKIP
      @business_type = business_type unless business_type == SKIP
      @business_description = business_description unless business_description == SKIP
      @swiped_percent = swiped_percent unless swiped_percent == SKIP
      @keyed_percent = keyed_percent unless keyed_percent == SKIP
      @ecommerce_percent = ecommerce_percent unless ecommerce_percent == SKIP
      @ownership_type = ownership_type unless ownership_type == SKIP
      @fed_tax_id = fed_tax_id unless fed_tax_id == SKIP
      @cc_average_ticket_range = cc_average_ticket_range unless cc_average_ticket_range == SKIP
      @cc_monthly_volume_range = cc_monthly_volume_range unless cc_monthly_volume_range == SKIP
      @cc_high_ticket = cc_high_ticket unless cc_high_ticket == SKIP
      @ec_average_ticket_range = ec_average_ticket_range unless ec_average_ticket_range == SKIP
      @ec_monthly_volume_range = ec_monthly_volume_range unless ec_monthly_volume_range == SKIP
      @ec_high_ticket = ec_high_ticket unless ec_high_ticket == SKIP
      @website = website unless website == SKIP
      @bank_account = bank_account unless bank_account == SKIP
      @alt_bank_account = alt_bank_account unless alt_bank_account == SKIP
      @legal_name = legal_name unless legal_name == SKIP
      @contact = contact
      @client_app_id = client_app_id unless client_app_id == SKIP
      @sec_codes = sec_codes unless sec_codes == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      primary_principal = PrimaryPrincipal2.from_hash(hash['primary_principal']) if
        hash['primary_principal']
      template_code = hash.key?('template_code') ? hash['template_code'] : nil
      email = hash.key?('email') ? hash['email'] : nil
      dba_name = hash.key?('dba_name') ? hash['dba_name'] : nil
      location = Location19.from_hash(hash['location']) if hash['location']
      app_delivery = hash.key?('app_delivery') ? hash['app_delivery'] : nil
      contact = Contact13.from_hash(hash['contact']) if hash['contact']
      parent_id = hash.key?('parent_id') ? hash['parent_id'] : SKIP
      business_category =
        hash.key?('business_category') ? hash['business_category'] : SKIP
      business_type = hash.key?('business_type') ? hash['business_type'] : SKIP
      business_description =
        hash.key?('business_description') ? hash['business_description'] : SKIP
      swiped_percent =
        hash.key?('swiped_percent') ? hash['swiped_percent'] : SKIP
      keyed_percent = hash.key?('keyed_percent') ? hash['keyed_percent'] : SKIP
      ecommerce_percent =
        hash.key?('ecommerce_percent') ? hash['ecommerce_percent'] : SKIP
      ownership_type =
        hash.key?('ownership_type') ? hash['ownership_type'] : SKIP
      fed_tax_id = hash.key?('fed_tax_id') ? hash['fed_tax_id'] : SKIP
      cc_average_ticket_range =
        hash.key?('cc_average_ticket_range') ? hash['cc_average_ticket_range'] : SKIP
      cc_monthly_volume_range =
        hash.key?('cc_monthly_volume_range') ? hash['cc_monthly_volume_range'] : SKIP
      cc_high_ticket =
        hash.key?('cc_high_ticket') ? hash['cc_high_ticket'] : SKIP
      ec_average_ticket_range =
        hash.key?('ec_average_ticket_range') ? hash['ec_average_ticket_range'] : SKIP
      ec_monthly_volume_range =
        hash.key?('ec_monthly_volume_range') ? hash['ec_monthly_volume_range'] : SKIP
      ec_high_ticket =
        hash.key?('ec_high_ticket') ? hash['ec_high_ticket'] : SKIP
      website = hash.key?('website') ? hash['website'] : SKIP
      bank_account = BankAccount3.from_hash(hash['bank_account']) if hash['bank_account']
      alt_bank_account = AltBankAccount2.from_hash(hash['alt_bank_account']) if
        hash['alt_bank_account']
      legal_name = hash.key?('legal_name') ? hash['legal_name'] : SKIP
      client_app_id = hash.key?('client_app_id') ? hash['client_app_id'] : SKIP
      sec_codes = hash.key?('sec_codes') ? hash['sec_codes'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      V1OnboardingRequest.new(primary_principal: primary_principal,
                              template_code: template_code,
                              email: email,
                              dba_name: dba_name,
                              location: location,
                              app_delivery: app_delivery,
                              contact: contact,
                              parent_id: parent_id,
                              business_category: business_category,
                              business_type: business_type,
                              business_description: business_description,
                              swiped_percent: swiped_percent,
                              keyed_percent: keyed_percent,
                              ecommerce_percent: ecommerce_percent,
                              ownership_type: ownership_type,
                              fed_tax_id: fed_tax_id,
                              cc_average_ticket_range: cc_average_ticket_range,
                              cc_monthly_volume_range: cc_monthly_volume_range,
                              cc_high_ticket: cc_high_ticket,
                              ec_average_ticket_range: ec_average_ticket_range,
                              ec_monthly_volume_range: ec_monthly_volume_range,
                              ec_high_ticket: ec_high_ticket,
                              website: website,
                              bank_account: bank_account,
                              alt_bank_account: alt_bank_account,
                              legal_name: legal_name,
                              client_app_id: client_app_id,
                              sec_codes: sec_codes,
                              additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} parent_id: #{@parent_id}, primary_principal: #{@primary_principal},"\
      " template_code: #{@template_code}, email: #{@email}, dba_name: #{@dba_name}, location:"\
      " #{@location}, app_delivery: #{@app_delivery}, business_category: #{@business_category},"\
      " business_type: #{@business_type}, business_description: #{@business_description},"\
      " swiped_percent: #{@swiped_percent}, keyed_percent: #{@keyed_percent}, ecommerce_percent:"\
      " #{@ecommerce_percent}, ownership_type: #{@ownership_type}, fed_tax_id: #{@fed_tax_id},"\
      " cc_average_ticket_range: #{@cc_average_ticket_range}, cc_monthly_volume_range:"\
      " #{@cc_monthly_volume_range}, cc_high_ticket: #{@cc_high_ticket}, ec_average_ticket_range:"\
      " #{@ec_average_ticket_range}, ec_monthly_volume_range: #{@ec_monthly_volume_range},"\
      " ec_high_ticket: #{@ec_high_ticket}, website: #{@website}, bank_account: #{@bank_account},"\
      " alt_bank_account: #{@alt_bank_account}, legal_name: #{@legal_name}, contact: #{@contact},"\
      " client_app_id: #{@client_app_id}, sec_codes: #{@sec_codes}, additional_properties:"\
      " #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} parent_id: #{@parent_id.inspect}, primary_principal:"\
      " #{@primary_principal.inspect}, template_code: #{@template_code.inspect}, email:"\
      " #{@email.inspect}, dba_name: #{@dba_name.inspect}, location: #{@location.inspect},"\
      " app_delivery: #{@app_delivery.inspect}, business_category: #{@business_category.inspect},"\
      " business_type: #{@business_type.inspect}, business_description:"\
      " #{@business_description.inspect}, swiped_percent: #{@swiped_percent.inspect},"\
      " keyed_percent: #{@keyed_percent.inspect}, ecommerce_percent:"\
      " #{@ecommerce_percent.inspect}, ownership_type: #{@ownership_type.inspect}, fed_tax_id:"\
      " #{@fed_tax_id.inspect}, cc_average_ticket_range: #{@cc_average_ticket_range.inspect},"\
      " cc_monthly_volume_range: #{@cc_monthly_volume_range.inspect}, cc_high_ticket:"\
      " #{@cc_high_ticket.inspect}, ec_average_ticket_range: #{@ec_average_ticket_range.inspect},"\
      " ec_monthly_volume_range: #{@ec_monthly_volume_range.inspect}, ec_high_ticket:"\
      " #{@ec_high_ticket.inspect}, website: #{@website.inspect}, bank_account:"\
      " #{@bank_account.inspect}, alt_bank_account: #{@alt_bank_account.inspect}, legal_name:"\
      " #{@legal_name.inspect}, contact: #{@contact.inspect}, client_app_id:"\
      " #{@client_app_id.inspect}, sec_codes: #{@sec_codes.inspect}, additional_properties:"\
      " #{@additional_properties}>"
    end
  end
end
