# fortis_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module FortisApi
  # V1TransactionsCcBalanceInquirySwipedRequest Model.
  class V1TransactionsCcBalanceInquirySwipedRequest < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Additional amounts
    # @return [Array[AdditionalAmount]]
    attr_accessor :additional_amounts

    # Billing Address Object
    # @return [BillingAddress1]
    attr_accessor :billing_address

    # Checkin Date - The time difference between checkin_date and checkout_date
    # must be less than or equal to 99 days. NOTE: if checkin_date is in the
    # future, set the advance_deposit to 1
    # >Required if merchant industry type is lodging. 
    # >
    # @return [String]
    attr_accessor :checkin_date

    # Checkout Date - The time difference between checkin_date and checkout_date
    # must be less than or equal to 99 days.
    # >Required if merchant industry type is lodging.
    # >
    # @return [String]
    attr_accessor :checkout_date

    # Clerk or Employee Identifier
    # @return [String]
    attr_accessor :clerk_number

    # This can be supplied in place of contact_id if you would like to use a
    # contact for the transaction and are using your own custom api_id's to
    # track contacts in the system.
    # @return [String]
    attr_accessor :contact_api_id

    # If contact_id is provided, ensure it belongs to the same location as the
    # transaction. You cannot move transaction across locations.
    # @return [String]
    attr_accessor :contact_id

    # A field that allows custom JSON to be entered to store extra data.
    # @return [Object]
    attr_accessor :custom_data

    # Can be used by Merchants to identify Contacts in our system by an ID from
    # another system.
    # @return [String]
    attr_accessor :customer_id

    # Description
    # @return [String]
    attr_accessor :description

    # Identity Verification
    # @return [IdentityVerification]
    attr_accessor :identity_verification

    # Possible values are '0', '1','2'
    # @return [IiasIndEnum]
    attr_accessor :iias_ind

    # A base64 encoded string for the image.  Used with Check21 ACH
    # transactions.
    # @return [String]
    attr_accessor :image_front

    # A base64 encoded string for the image.  Used with Check21 ACH
    # transactions.
    # @return [String]
    attr_accessor :image_back

    # Flag that is allowed to be passed on card not present industries to
    # signify the transaction is a fixed installment plan transaction.
    # @return [TrueClass | FalseClass]
    attr_accessor :installment

    # If this is a fixed installment plan and installment field is being passed
    # as 1, then this field must have a vlue of 1-999 specifying the current
    # installment number that is running.
    # @return [Integer]
    attr_accessor :installment_number

    # If this is a fixed installment plan and installment field is being passed
    # as 1, then this field must have a vlue of 1-999 specifying the total
    # number of installments on the plan. This number must be grater than or
    # equal to installment_number.
    # @return [Integer]
    attr_accessor :installment_count

    # Recurring Flag
    # @return [RecurringFlagEnum]
    attr_accessor :recurring_flag

    # Installment Counter
    # @return [Integer]
    attr_accessor :installment_counter

    # Installment Total
    # @return [Integer]
    attr_accessor :installment_total

    # Subscription
    # @return [TrueClass | FalseClass]
    attr_accessor :subscription

    # Standing Order
    # @return [TrueClass | FalseClass]
    attr_accessor :standing_order

    # This can be supplied in place of location_id for the transaction if you
    # are using your own custom api_id's for your locations.
    # @return [String]
    attr_accessor :location_api_id

    # A valid Location Id to associate the transaction with.
    # @return [String]
    attr_accessor :location_id

    # The Product's method (cc/ach) has to match the action. If not provided,
    # the API will use the default configured for the Location.
    # @return [String]
    attr_accessor :product_transaction_id

    # Advance Deposit
    # @return [TrueClass | FalseClass]
    attr_accessor :advance_deposit

    # Used in Lodging
    # @return [TrueClass | FalseClass]
    attr_accessor :no_show

    # If email is supplied then receipt will be emailed
    # @return [String]
    attr_accessor :notification_email_address

    # Required for CC transactions , if merchant's deposit account's duplicate
    # check per batch has 'order_number' field
    # @return [String]
    attr_accessor :order_number

    # Purchase Order number
    # @return [String]
    attr_accessor :po_number

    # Can be used to associate a transaction to a Quick Invoice.  Quick Invoice
    # transactions will have a value for this field automatically.
    # @return [String]
    attr_accessor :quick_invoice_id

    # Flag that is allowed to be passed on card not present industries to
    # signify the transaction is an ongoing recurring transaction. Possible
    # values to send are 0 or 1. This field must be 0 or not present if
    # installment is sent as 1.
    # @return [TrueClass | FalseClass]
    attr_accessor :recurring

    # If this is an ongoing recurring and recurring field is being passed as 1,
    # then this field must have a vlue of 1-999 specifying the current recurring
    # number that is running.
    # @return [Integer]
    attr_accessor :recurring_number

    # Used in Lodging
    # @return [String]
    attr_accessor :room_num

    # Required if merchant industry type is lodging.
    # @return [Integer]
    attr_accessor :room_rate

    # Specifies to save account to contacts profile if account_number/track_data
    # is present with either contact_id or contact_api_id in params.
    # @return [TrueClass | FalseClass]
    attr_accessor :save_account

    # If saving token while running a transaction, this will be the title of the
    # token.
    # @return [String]
    attr_accessor :save_account_title

    # This field is allowed and required for transactions that have a product
    # where surcharge is configured. Use only integer numbers, so $10.99 will be
    # 1099.
    # @return [Integer]
    attr_accessor :subtotal_amount

    # This field is allowed and required for transactions that have a product
    # where surcharge is configured. Use only integer numbers, so $10.99 will be
    # 1099.
    # @return [Integer]
    attr_accessor :surcharge_amount

    # Tags
    # @return [Array[String]]
    attr_accessor :tags

    # Amount of Sales tax - If supplied, this amount should be included in the
    # total transaction_amount field. Use only integer numbers, so $10.99 will
    # be 1099.
    # @return [Integer]
    attr_accessor :tax

    # Optional tip amount. Tip is not supported for lodging and ecommerce
    # merchants. Use only integer numbers, so $10.99 will be 1099.
    # @return [Integer]
    attr_accessor :tip_amount

    # Amount of the transaction. This should always be the desired settle amount
    # of the transaction. Use only integer numbers, so $10.99 will be 1099.
    # @return [Integer]
    attr_accessor :transaction_amount

    # Retained Amount of the transaction. This should always be less than
    # transaction amount. Use only integer numbers, so $10.99 will be 1099
    # @return [Integer]
    attr_accessor :secondary_amount

    # See api_id page for more details
    # @return [String]
    attr_accessor :transaction_api_id

    # Custom field 1 for api users to store custom data
    # @return [String]
    attr_accessor :transaction_c1

    # Custom field 2 for api users to store custom data
    # @return [String]
    attr_accessor :transaction_c2

    # Custom field 3 for api users to store custom data
    # @return [String]
    attr_accessor :transaction_c3

    # Bank Funded Only Override
    # @return [TrueClass | FalseClass]
    attr_accessor :bank_funded_only_override

    # Allow Partial Authorization Override
    # @return [TrueClass | FalseClass]
    attr_accessor :allow_partial_authorization_override

    # Auto Decline CVV Override
    # @return [TrueClass | FalseClass]
    attr_accessor :auto_decline_cvv_override

    # Auto Decline Street Override
    # @return [TrueClass | FalseClass]
    attr_accessor :auto_decline_street_override

    # Auto Decline Zip Override
    # @return [TrueClass | FalseClass]
    attr_accessor :auto_decline_zip_override

    # EBT Type
    # @return [EbtTypeEnum]
    attr_accessor :ebt_type

    # If the cardholder is present at the point of service
    # @return [TrueClass | FalseClass]
    attr_accessor :cardholder_present

    # A POST only field to specify whether or not the card is present.
    # >This field will be defaulted to '1' for all card present industries
    # (retail, lodging, restaurant) and '0' for card not present industries
    # (MOTO/e-commerce).
    # For lodging, if the no_show flag is set to '1', this field will
    # automatically be set to '0'.
    # For transactions where account_vault_id is used, this filed will be set to
    # '0'.
    # >
    # @return [TrueClass | FalseClass]
    attr_accessor :card_present

    # (ECOMM) The token authentication value associated with 3D secure
    # transactions (Such as CAVV, UCAF auth data)
    # @return [String]
    attr_accessor :secure_auth_data

    # (ECOMM)  Secure Program Protocol Version
    # @return [Integer]
    attr_accessor :secure_protocol_version

    # (ECOMM) Used for UCAF collection indicator or Discover Autentication type
    # @return [Integer]
    attr_accessor :secure_collection_indicator

    # (ECOMM) Used to supply the Digital Payment Cryptogram obtained from a
    # Digital Secure Remote Payment (DSRP) transaction
    # @return [String]
    attr_accessor :secure_cryptogram

    # (ECOMM) Directory Server Transaction ID (Such as XID, TAVV)
    # @return [String]
    attr_accessor :secure_directory_server_transaction_id

    # (ECOMM) This field is used to enter a merchant identifier such as the
    # Merchant URL or reverse domain name as presented to the consumer during
    # the checkout process for a Digital Secure Remote payment transaction
    # @return [String]
    attr_accessor :secure_ecomm_url

    # If transaction was processed using a terminal, this field would contain
    # the terminal's serial number
    # @return [String]
    attr_accessor :terminal_serial_number

    # (ECOMM) Specify if the transaction is obtained by 3DSecure.
    # @return [TrueClass | FalseClass]
    attr_accessor :threedsecure

    # 3DS Server Transaction ID.  If this field is sent and 3DS authentication
    # was done with Fortis, the 3DS fields
    # secure_directory_server_transaction_id, secure_protocol_version, and
    # secure_collection_indicator will be pre-populated.
    # @return [String]
    attr_accessor :three_ds_server_trans_id

    # This value provides information from where the transaction was initialized
    # (Such as In-App provider)
    # >000 - Unknown wallet type (i.e., Discover PayButton)
    # >
    # >101 - MasterPass by MasterCard
    # >
    # >103 - Apple Pay
    # >
    # >216 - Google Pay
    # >
    # >217 - Samsung Pay
    # >
    # >327 - Merchant tokenization program
    # >
    # @return [WalletTypeEnum]
    attr_accessor :wallet_type

    # Clerk ID
    # @return [String]
    attr_accessor :clerk_id

    # Voucher Number
    # @return [String]
    attr_accessor :voucher_number

    # Initiation Type
    # @return [InitiationTypeEnum]
    attr_accessor :initiation_type

    # If transaction is a bill payment
    # @return [TrueClass | FalseClass]
    attr_accessor :bill_payment

    # Delay Charge
    # @return [TrueClass | FalseClass]
    attr_accessor :delay_charge

    # Deferred Auth
    # @return [TrueClass | FalseClass]
    attr_accessor :deferred_auth

    # Mini Bar
    # @return [TrueClass | FalseClass]
    attr_accessor :mini_bar

    # EBT Food Eligible Amount
    # @return [Integer]
    attr_accessor :ebt_food_eligible_amount

    # EBT Cash Eligible Amount
    # @return [Integer]
    attr_accessor :ebt_cash_eligible_amount

    # Entry Mode - See entry mode section for more detail
    # @return [EntryModeIdEnum]
    attr_accessor :entry_mode_id

    # Track Data from a magnetic card swipe.
    # @return [String]
    attr_accessor :track_data

    # For CC, this is the 'Name (as it appears) on Card'. For ACH, this is the
    # 'Name on Account'.
    # >Required for ACH transactions if account_vault_id is not provided. For CC
    # transactions that are run through a terminal, this field may be
    # overwritten by data acquired from the credit card track data.
    # >
    # @return [String]
    attr_accessor :account_holder_name

    # Required for CC transactions if vt_require_cvv is true on
    # producttransaction(Merchant Deposit Account).
    # @return [String]
    attr_accessor :cvv

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['additional_amounts'] = 'additional_amounts'
      @_hash['billing_address'] = 'billing_address'
      @_hash['checkin_date'] = 'checkin_date'
      @_hash['checkout_date'] = 'checkout_date'
      @_hash['clerk_number'] = 'clerk_number'
      @_hash['contact_api_id'] = 'contact_api_id'
      @_hash['contact_id'] = 'contact_id'
      @_hash['custom_data'] = 'custom_data'
      @_hash['customer_id'] = 'customer_id'
      @_hash['description'] = 'description'
      @_hash['identity_verification'] = 'identity_verification'
      @_hash['iias_ind'] = 'iias_ind'
      @_hash['image_front'] = 'image_front'
      @_hash['image_back'] = 'image_back'
      @_hash['installment'] = 'installment'
      @_hash['installment_number'] = 'installment_number'
      @_hash['installment_count'] = 'installment_count'
      @_hash['recurring_flag'] = 'recurring_flag'
      @_hash['installment_counter'] = 'installment_counter'
      @_hash['installment_total'] = 'installment_total'
      @_hash['subscription'] = 'subscription'
      @_hash['standing_order'] = 'standing_order'
      @_hash['location_api_id'] = 'location_api_id'
      @_hash['location_id'] = 'location_id'
      @_hash['product_transaction_id'] = 'product_transaction_id'
      @_hash['advance_deposit'] = 'advance_deposit'
      @_hash['no_show'] = 'no_show'
      @_hash['notification_email_address'] = 'notification_email_address'
      @_hash['order_number'] = 'order_number'
      @_hash['po_number'] = 'po_number'
      @_hash['quick_invoice_id'] = 'quick_invoice_id'
      @_hash['recurring'] = 'recurring'
      @_hash['recurring_number'] = 'recurring_number'
      @_hash['room_num'] = 'room_num'
      @_hash['room_rate'] = 'room_rate'
      @_hash['save_account'] = 'save_account'
      @_hash['save_account_title'] = 'save_account_title'
      @_hash['subtotal_amount'] = 'subtotal_amount'
      @_hash['surcharge_amount'] = 'surcharge_amount'
      @_hash['tags'] = 'tags'
      @_hash['tax'] = 'tax'
      @_hash['tip_amount'] = 'tip_amount'
      @_hash['transaction_amount'] = 'transaction_amount'
      @_hash['secondary_amount'] = 'secondary_amount'
      @_hash['transaction_api_id'] = 'transaction_api_id'
      @_hash['transaction_c1'] = 'transaction_c1'
      @_hash['transaction_c2'] = 'transaction_c2'
      @_hash['transaction_c3'] = 'transaction_c3'
      @_hash['bank_funded_only_override'] = 'bank_funded_only_override'
      @_hash['allow_partial_authorization_override'] =
        'allow_partial_authorization_override'
      @_hash['auto_decline_cvv_override'] = 'auto_decline_cvv_override'
      @_hash['auto_decline_street_override'] = 'auto_decline_street_override'
      @_hash['auto_decline_zip_override'] = 'auto_decline_zip_override'
      @_hash['ebt_type'] = 'ebt_type'
      @_hash['cardholder_present'] = 'cardholder_present'
      @_hash['card_present'] = 'card_present'
      @_hash['secure_auth_data'] = 'secure_auth_data'
      @_hash['secure_protocol_version'] = 'secure_protocol_version'
      @_hash['secure_collection_indicator'] = 'secure_collection_indicator'
      @_hash['secure_cryptogram'] = 'secure_cryptogram'
      @_hash['secure_directory_server_transaction_id'] =
        'secure_directory_server_transaction_id'
      @_hash['secure_ecomm_url'] = 'secure_ecomm_url'
      @_hash['terminal_serial_number'] = 'terminal_serial_number'
      @_hash['threedsecure'] = 'threedsecure'
      @_hash['three_ds_server_trans_id'] = 'three_ds_server_trans_id'
      @_hash['wallet_type'] = 'wallet_type'
      @_hash['clerk_id'] = 'clerk_id'
      @_hash['voucher_number'] = 'voucher_number'
      @_hash['initiation_type'] = 'initiation_type'
      @_hash['bill_payment'] = 'bill_payment'
      @_hash['delay_charge'] = 'delay_charge'
      @_hash['deferred_auth'] = 'deferred_auth'
      @_hash['mini_bar'] = 'mini_bar'
      @_hash['ebt_food_eligible_amount'] = 'ebt_food_eligible_amount'
      @_hash['ebt_cash_eligible_amount'] = 'ebt_cash_eligible_amount'
      @_hash['entry_mode_id'] = 'entry_mode_id'
      @_hash['track_data'] = 'track_data'
      @_hash['account_holder_name'] = 'account_holder_name'
      @_hash['cvv'] = 'cvv'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        additional_amounts
        billing_address
        checkin_date
        checkout_date
        clerk_number
        contact_api_id
        contact_id
        custom_data
        customer_id
        description
        identity_verification
        iias_ind
        image_front
        image_back
        installment
        installment_number
        installment_count
        recurring_flag
        installment_counter
        installment_total
        subscription
        standing_order
        location_api_id
        location_id
        product_transaction_id
        advance_deposit
        no_show
        notification_email_address
        order_number
        po_number
        quick_invoice_id
        recurring
        recurring_number
        room_num
        room_rate
        save_account
        save_account_title
        subtotal_amount
        surcharge_amount
        tags
        tax
        tip_amount
        transaction_amount
        secondary_amount
        transaction_api_id
        transaction_c1
        transaction_c2
        transaction_c3
        bank_funded_only_override
        allow_partial_authorization_override
        auto_decline_cvv_override
        auto_decline_street_override
        auto_decline_zip_override
        ebt_type
        cardholder_present
        card_present
        secure_auth_data
        secure_protocol_version
        secure_collection_indicator
        secure_cryptogram
        secure_directory_server_transaction_id
        secure_ecomm_url
        terminal_serial_number
        threedsecure
        three_ds_server_trans_id
        wallet_type
        clerk_id
        voucher_number
        initiation_type
        bill_payment
        delay_charge
        deferred_auth
        mini_bar
        ebt_food_eligible_amount
        ebt_cash_eligible_amount
        entry_mode_id
        account_holder_name
        cvv
      ]
    end

    # An array for nullable fields
    def self.nullables
      %w[
        checkin_date
        checkout_date
        clerk_number
        contact_api_id
        contact_id
        customer_id
        description
        iias_ind
        image_front
        image_back
        installment_number
        installment_count
        recurring_flag
        installment_counter
        installment_total
        location_api_id
        location_id
        product_transaction_id
        notification_email_address
        order_number
        po_number
        quick_invoice_id
        recurring_number
        room_num
        room_rate
        save_account_title
        subtotal_amount
        surcharge_amount
        tags
        tax
        tip_amount
        transaction_amount
        secondary_amount
        transaction_api_id
        transaction_c1
        transaction_c2
        transaction_c3
        ebt_type
        secure_auth_data
        secure_protocol_version
        secure_collection_indicator
        secure_cryptogram
        secure_directory_server_transaction_id
        secure_ecomm_url
        terminal_serial_number
        three_ds_server_trans_id
        wallet_type
        clerk_id
        voucher_number
        initiation_type
        ebt_food_eligible_amount
        ebt_cash_eligible_amount
        entry_mode_id
        account_holder_name
        cvv
      ]
    end

    def initialize(track_data = nil, additional_amounts = SKIP,
                   billing_address = SKIP, checkin_date = SKIP,
                   checkout_date = SKIP, clerk_number = SKIP,
                   contact_api_id = SKIP, contact_id = SKIP, custom_data = SKIP,
                   customer_id = SKIP, description = SKIP,
                   identity_verification = SKIP, iias_ind = SKIP,
                   image_front = SKIP, image_back = SKIP, installment = SKIP,
                   installment_number = SKIP, installment_count = SKIP,
                   recurring_flag = SKIP, installment_counter = SKIP,
                   installment_total = SKIP, subscription = SKIP,
                   standing_order = SKIP, location_api_id = SKIP,
                   location_id = SKIP, product_transaction_id = SKIP,
                   advance_deposit = SKIP, no_show = SKIP,
                   notification_email_address = SKIP, order_number = SKIP,
                   po_number = SKIP, quick_invoice_id = SKIP, recurring = SKIP,
                   recurring_number = SKIP, room_num = SKIP, room_rate = SKIP,
                   save_account = SKIP, save_account_title = SKIP,
                   subtotal_amount = SKIP, surcharge_amount = SKIP, tags = SKIP,
                   tax = SKIP, tip_amount = SKIP, transaction_amount = SKIP,
                   secondary_amount = SKIP, transaction_api_id = SKIP,
                   transaction_c1 = SKIP, transaction_c2 = SKIP,
                   transaction_c3 = SKIP, bank_funded_only_override = SKIP,
                   allow_partial_authorization_override = SKIP,
                   auto_decline_cvv_override = SKIP,
                   auto_decline_street_override = SKIP,
                   auto_decline_zip_override = SKIP, ebt_type = SKIP,
                   cardholder_present = SKIP, card_present = SKIP,
                   secure_auth_data = SKIP, secure_protocol_version = SKIP,
                   secure_collection_indicator = SKIP, secure_cryptogram = SKIP,
                   secure_directory_server_transaction_id = SKIP,
                   secure_ecomm_url = SKIP, terminal_serial_number = SKIP,
                   threedsecure = SKIP, three_ds_server_trans_id = SKIP,
                   wallet_type = SKIP, clerk_id = SKIP, voucher_number = SKIP,
                   initiation_type = SKIP, bill_payment = SKIP,
                   delay_charge = SKIP, deferred_auth = SKIP, mini_bar = SKIP,
                   ebt_food_eligible_amount = SKIP,
                   ebt_cash_eligible_amount = SKIP, entry_mode_id = SKIP,
                   account_holder_name = SKIP, cvv = SKIP,
                   additional_properties = {})
      # Add additional model properties to the instance.
      additional_properties.each do |_name, _value|
        instance_variable_set("@#{_name}", _value)
      end

      @additional_amounts = additional_amounts unless additional_amounts == SKIP
      @billing_address = billing_address unless billing_address == SKIP
      @checkin_date = checkin_date unless checkin_date == SKIP
      @checkout_date = checkout_date unless checkout_date == SKIP
      @clerk_number = clerk_number unless clerk_number == SKIP
      @contact_api_id = contact_api_id unless contact_api_id == SKIP
      @contact_id = contact_id unless contact_id == SKIP
      @custom_data = custom_data unless custom_data == SKIP
      @customer_id = customer_id unless customer_id == SKIP
      @description = description unless description == SKIP
      @identity_verification = identity_verification unless identity_verification == SKIP
      @iias_ind = iias_ind unless iias_ind == SKIP
      @image_front = image_front unless image_front == SKIP
      @image_back = image_back unless image_back == SKIP
      @installment = installment unless installment == SKIP
      @installment_number = installment_number unless installment_number == SKIP
      @installment_count = installment_count unless installment_count == SKIP
      @recurring_flag = recurring_flag unless recurring_flag == SKIP
      @installment_counter = installment_counter unless installment_counter == SKIP
      @installment_total = installment_total unless installment_total == SKIP
      @subscription = subscription unless subscription == SKIP
      @standing_order = standing_order unless standing_order == SKIP
      @location_api_id = location_api_id unless location_api_id == SKIP
      @location_id = location_id unless location_id == SKIP
      @product_transaction_id = product_transaction_id unless product_transaction_id == SKIP
      @advance_deposit = advance_deposit unless advance_deposit == SKIP
      @no_show = no_show unless no_show == SKIP
      unless notification_email_address == SKIP
        @notification_email_address =
          notification_email_address
      end
      @order_number = order_number unless order_number == SKIP
      @po_number = po_number unless po_number == SKIP
      @quick_invoice_id = quick_invoice_id unless quick_invoice_id == SKIP
      @recurring = recurring unless recurring == SKIP
      @recurring_number = recurring_number unless recurring_number == SKIP
      @room_num = room_num unless room_num == SKIP
      @room_rate = room_rate unless room_rate == SKIP
      @save_account = save_account unless save_account == SKIP
      @save_account_title = save_account_title unless save_account_title == SKIP
      @subtotal_amount = subtotal_amount unless subtotal_amount == SKIP
      @surcharge_amount = surcharge_amount unless surcharge_amount == SKIP
      @tags = tags unless tags == SKIP
      @tax = tax unless tax == SKIP
      @tip_amount = tip_amount unless tip_amount == SKIP
      @transaction_amount = transaction_amount unless transaction_amount == SKIP
      @secondary_amount = secondary_amount unless secondary_amount == SKIP
      @transaction_api_id = transaction_api_id unless transaction_api_id == SKIP
      @transaction_c1 = transaction_c1 unless transaction_c1 == SKIP
      @transaction_c2 = transaction_c2 unless transaction_c2 == SKIP
      @transaction_c3 = transaction_c3 unless transaction_c3 == SKIP
      unless bank_funded_only_override == SKIP
        @bank_funded_only_override =
          bank_funded_only_override
      end
      unless allow_partial_authorization_override == SKIP
        @allow_partial_authorization_override =
          allow_partial_authorization_override
      end
      unless auto_decline_cvv_override == SKIP
        @auto_decline_cvv_override =
          auto_decline_cvv_override
      end
      unless auto_decline_street_override == SKIP
        @auto_decline_street_override =
          auto_decline_street_override
      end
      unless auto_decline_zip_override == SKIP
        @auto_decline_zip_override =
          auto_decline_zip_override
      end
      @ebt_type = ebt_type unless ebt_type == SKIP
      @cardholder_present = cardholder_present unless cardholder_present == SKIP
      @card_present = card_present unless card_present == SKIP
      @secure_auth_data = secure_auth_data unless secure_auth_data == SKIP
      @secure_protocol_version = secure_protocol_version unless secure_protocol_version == SKIP
      unless secure_collection_indicator == SKIP
        @secure_collection_indicator =
          secure_collection_indicator
      end
      @secure_cryptogram = secure_cryptogram unless secure_cryptogram == SKIP
      unless secure_directory_server_transaction_id == SKIP
        @secure_directory_server_transaction_id =
          secure_directory_server_transaction_id
      end
      @secure_ecomm_url = secure_ecomm_url unless secure_ecomm_url == SKIP
      @terminal_serial_number = terminal_serial_number unless terminal_serial_number == SKIP
      @threedsecure = threedsecure unless threedsecure == SKIP
      @three_ds_server_trans_id = three_ds_server_trans_id unless three_ds_server_trans_id == SKIP
      @wallet_type = wallet_type unless wallet_type == SKIP
      @clerk_id = clerk_id unless clerk_id == SKIP
      @voucher_number = voucher_number unless voucher_number == SKIP
      @initiation_type = initiation_type unless initiation_type == SKIP
      @bill_payment = bill_payment unless bill_payment == SKIP
      @delay_charge = delay_charge unless delay_charge == SKIP
      @deferred_auth = deferred_auth unless deferred_auth == SKIP
      @mini_bar = mini_bar unless mini_bar == SKIP
      @ebt_food_eligible_amount = ebt_food_eligible_amount unless ebt_food_eligible_amount == SKIP
      @ebt_cash_eligible_amount = ebt_cash_eligible_amount unless ebt_cash_eligible_amount == SKIP
      @entry_mode_id = entry_mode_id unless entry_mode_id == SKIP
      @track_data = track_data
      @account_holder_name = account_holder_name unless account_holder_name == SKIP
      @cvv = cvv unless cvv == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      track_data = hash.key?('track_data') ? hash['track_data'] : nil
      # Parameter is an array, so we need to iterate through it
      additional_amounts = nil
      unless hash['additional_amounts'].nil?
        additional_amounts = []
        hash['additional_amounts'].each do |structure|
          additional_amounts << (AdditionalAmount.from_hash(structure) if structure)
        end
      end

      additional_amounts = SKIP unless hash.key?('additional_amounts')
      billing_address = BillingAddress1.from_hash(hash['billing_address']) if
        hash['billing_address']
      checkin_date = hash.key?('checkin_date') ? hash['checkin_date'] : SKIP
      checkout_date = hash.key?('checkout_date') ? hash['checkout_date'] : SKIP
      clerk_number = hash.key?('clerk_number') ? hash['clerk_number'] : SKIP
      contact_api_id =
        hash.key?('contact_api_id') ? hash['contact_api_id'] : SKIP
      contact_id = hash.key?('contact_id') ? hash['contact_id'] : SKIP
      custom_data = hash.key?('custom_data') ? hash['custom_data'] : SKIP
      customer_id = hash.key?('customer_id') ? hash['customer_id'] : SKIP
      description = hash.key?('description') ? hash['description'] : SKIP
      identity_verification = IdentityVerification.from_hash(hash['identity_verification']) if
        hash['identity_verification']
      iias_ind = hash.key?('iias_ind') ? hash['iias_ind'] : SKIP
      image_front = hash.key?('image_front') ? hash['image_front'] : SKIP
      image_back = hash.key?('image_back') ? hash['image_back'] : SKIP
      installment = hash.key?('installment') ? hash['installment'] : SKIP
      installment_number =
        hash.key?('installment_number') ? hash['installment_number'] : SKIP
      installment_count =
        hash.key?('installment_count') ? hash['installment_count'] : SKIP
      recurring_flag =
        hash.key?('recurring_flag') ? hash['recurring_flag'] : SKIP
      installment_counter =
        hash.key?('installment_counter') ? hash['installment_counter'] : SKIP
      installment_total =
        hash.key?('installment_total') ? hash['installment_total'] : SKIP
      subscription = hash.key?('subscription') ? hash['subscription'] : SKIP
      standing_order =
        hash.key?('standing_order') ? hash['standing_order'] : SKIP
      location_api_id =
        hash.key?('location_api_id') ? hash['location_api_id'] : SKIP
      location_id = hash.key?('location_id') ? hash['location_id'] : SKIP
      product_transaction_id =
        hash.key?('product_transaction_id') ? hash['product_transaction_id'] : SKIP
      advance_deposit =
        hash.key?('advance_deposit') ? hash['advance_deposit'] : SKIP
      no_show = hash.key?('no_show') ? hash['no_show'] : SKIP
      notification_email_address =
        hash.key?('notification_email_address') ? hash['notification_email_address'] : SKIP
      order_number = hash.key?('order_number') ? hash['order_number'] : SKIP
      po_number = hash.key?('po_number') ? hash['po_number'] : SKIP
      quick_invoice_id =
        hash.key?('quick_invoice_id') ? hash['quick_invoice_id'] : SKIP
      recurring = hash.key?('recurring') ? hash['recurring'] : SKIP
      recurring_number =
        hash.key?('recurring_number') ? hash['recurring_number'] : SKIP
      room_num = hash.key?('room_num') ? hash['room_num'] : SKIP
      room_rate = hash.key?('room_rate') ? hash['room_rate'] : SKIP
      save_account = hash.key?('save_account') ? hash['save_account'] : SKIP
      save_account_title =
        hash.key?('save_account_title') ? hash['save_account_title'] : SKIP
      subtotal_amount =
        hash.key?('subtotal_amount') ? hash['subtotal_amount'] : SKIP
      surcharge_amount =
        hash.key?('surcharge_amount') ? hash['surcharge_amount'] : SKIP
      tags = hash.key?('tags') ? hash['tags'] : SKIP
      tax = hash.key?('tax') ? hash['tax'] : SKIP
      tip_amount = hash.key?('tip_amount') ? hash['tip_amount'] : SKIP
      transaction_amount =
        hash.key?('transaction_amount') ? hash['transaction_amount'] : SKIP
      secondary_amount =
        hash.key?('secondary_amount') ? hash['secondary_amount'] : SKIP
      transaction_api_id =
        hash.key?('transaction_api_id') ? hash['transaction_api_id'] : SKIP
      transaction_c1 =
        hash.key?('transaction_c1') ? hash['transaction_c1'] : SKIP
      transaction_c2 =
        hash.key?('transaction_c2') ? hash['transaction_c2'] : SKIP
      transaction_c3 =
        hash.key?('transaction_c3') ? hash['transaction_c3'] : SKIP
      bank_funded_only_override =
        hash.key?('bank_funded_only_override') ? hash['bank_funded_only_override'] : SKIP
      allow_partial_authorization_override =
        hash.key?('allow_partial_authorization_override') ? hash['allow_partial_authorization_override'] : SKIP
      auto_decline_cvv_override =
        hash.key?('auto_decline_cvv_override') ? hash['auto_decline_cvv_override'] : SKIP
      auto_decline_street_override =
        hash.key?('auto_decline_street_override') ? hash['auto_decline_street_override'] : SKIP
      auto_decline_zip_override =
        hash.key?('auto_decline_zip_override') ? hash['auto_decline_zip_override'] : SKIP
      ebt_type = hash.key?('ebt_type') ? hash['ebt_type'] : SKIP
      cardholder_present =
        hash.key?('cardholder_present') ? hash['cardholder_present'] : SKIP
      card_present = hash.key?('card_present') ? hash['card_present'] : SKIP
      secure_auth_data =
        hash.key?('secure_auth_data') ? hash['secure_auth_data'] : SKIP
      secure_protocol_version =
        hash.key?('secure_protocol_version') ? hash['secure_protocol_version'] : SKIP
      secure_collection_indicator =
        hash.key?('secure_collection_indicator') ? hash['secure_collection_indicator'] : SKIP
      secure_cryptogram =
        hash.key?('secure_cryptogram') ? hash['secure_cryptogram'] : SKIP
      secure_directory_server_transaction_id =
        hash.key?('secure_directory_server_transaction_id') ? hash['secure_directory_server_transaction_id'] : SKIP
      secure_ecomm_url =
        hash.key?('secure_ecomm_url') ? hash['secure_ecomm_url'] : SKIP
      terminal_serial_number =
        hash.key?('terminal_serial_number') ? hash['terminal_serial_number'] : SKIP
      threedsecure = hash.key?('threedsecure') ? hash['threedsecure'] : SKIP
      three_ds_server_trans_id =
        hash.key?('three_ds_server_trans_id') ? hash['three_ds_server_trans_id'] : SKIP
      wallet_type = hash.key?('wallet_type') ? hash['wallet_type'] : SKIP
      clerk_id = hash.key?('clerk_id') ? hash['clerk_id'] : SKIP
      voucher_number =
        hash.key?('voucher_number') ? hash['voucher_number'] : SKIP
      initiation_type =
        hash.key?('initiation_type') ? hash['initiation_type'] : SKIP
      bill_payment = hash.key?('bill_payment') ? hash['bill_payment'] : SKIP
      delay_charge = hash.key?('delay_charge') ? hash['delay_charge'] : SKIP
      deferred_auth = hash.key?('deferred_auth') ? hash['deferred_auth'] : SKIP
      mini_bar = hash.key?('mini_bar') ? hash['mini_bar'] : SKIP
      ebt_food_eligible_amount =
        hash.key?('ebt_food_eligible_amount') ? hash['ebt_food_eligible_amount'] : SKIP
      ebt_cash_eligible_amount =
        hash.key?('ebt_cash_eligible_amount') ? hash['ebt_cash_eligible_amount'] : SKIP
      entry_mode_id = hash.key?('entry_mode_id') ? hash['entry_mode_id'] : SKIP
      account_holder_name =
        hash.key?('account_holder_name') ? hash['account_holder_name'] : SKIP
      cvv = hash.key?('cvv') ? hash['cvv'] : SKIP

      # Clean out expected properties from Hash.
      additional_properties = hash.reject { |k, _| names.value?(k) }

      # Create object from extracted values.
      V1TransactionsCcBalanceInquirySwipedRequest.new(track_data,
                                                      additional_amounts,
                                                      billing_address,
                                                      checkin_date,
                                                      checkout_date,
                                                      clerk_number,
                                                      contact_api_id,
                                                      contact_id,
                                                      custom_data,
                                                      customer_id,
                                                      description,
                                                      identity_verification,
                                                      iias_ind,
                                                      image_front,
                                                      image_back,
                                                      installment,
                                                      installment_number,
                                                      installment_count,
                                                      recurring_flag,
                                                      installment_counter,
                                                      installment_total,
                                                      subscription,
                                                      standing_order,
                                                      location_api_id,
                                                      location_id,
                                                      product_transaction_id,
                                                      advance_deposit,
                                                      no_show,
                                                      notification_email_address,
                                                      order_number,
                                                      po_number,
                                                      quick_invoice_id,
                                                      recurring,
                                                      recurring_number,
                                                      room_num,
                                                      room_rate,
                                                      save_account,
                                                      save_account_title,
                                                      subtotal_amount,
                                                      surcharge_amount,
                                                      tags,
                                                      tax,
                                                      tip_amount,
                                                      transaction_amount,
                                                      secondary_amount,
                                                      transaction_api_id,
                                                      transaction_c1,
                                                      transaction_c2,
                                                      transaction_c3,
                                                      bank_funded_only_override,
                                                      allow_partial_authorization_override,
                                                      auto_decline_cvv_override,
                                                      auto_decline_street_override,
                                                      auto_decline_zip_override,
                                                      ebt_type,
                                                      cardholder_present,
                                                      card_present,
                                                      secure_auth_data,
                                                      secure_protocol_version,
                                                      secure_collection_indicator,
                                                      secure_cryptogram,
                                                      secure_directory_server_transaction_id,
                                                      secure_ecomm_url,
                                                      terminal_serial_number,
                                                      threedsecure,
                                                      three_ds_server_trans_id,
                                                      wallet_type,
                                                      clerk_id,
                                                      voucher_number,
                                                      initiation_type,
                                                      bill_payment,
                                                      delay_charge,
                                                      deferred_auth,
                                                      mini_bar,
                                                      ebt_food_eligible_amount,
                                                      ebt_cash_eligible_amount,
                                                      entry_mode_id,
                                                      account_holder_name,
                                                      cvv,
                                                      additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} additional_amounts: #{@additional_amounts}, billing_address:"\
      " #{@billing_address}, checkin_date: #{@checkin_date}, checkout_date: #{@checkout_date},"\
      " clerk_number: #{@clerk_number}, contact_api_id: #{@contact_api_id}, contact_id:"\
      " #{@contact_id}, custom_data: #{@custom_data}, customer_id: #{@customer_id}, description:"\
      " #{@description}, identity_verification: #{@identity_verification}, iias_ind: #{@iias_ind},"\
      " image_front: #{@image_front}, image_back: #{@image_back}, installment: #{@installment},"\
      " installment_number: #{@installment_number}, installment_count: #{@installment_count},"\
      " recurring_flag: #{@recurring_flag}, installment_counter: #{@installment_counter},"\
      " installment_total: #{@installment_total}, subscription: #{@subscription}, standing_order:"\
      " #{@standing_order}, location_api_id: #{@location_api_id}, location_id: #{@location_id},"\
      " product_transaction_id: #{@product_transaction_id}, advance_deposit: #{@advance_deposit},"\
      " no_show: #{@no_show}, notification_email_address: #{@notification_email_address},"\
      " order_number: #{@order_number}, po_number: #{@po_number}, quick_invoice_id:"\
      " #{@quick_invoice_id}, recurring: #{@recurring}, recurring_number: #{@recurring_number},"\
      " room_num: #{@room_num}, room_rate: #{@room_rate}, save_account: #{@save_account},"\
      " save_account_title: #{@save_account_title}, subtotal_amount: #{@subtotal_amount},"\
      " surcharge_amount: #{@surcharge_amount}, tags: #{@tags}, tax: #{@tax}, tip_amount:"\
      " #{@tip_amount}, transaction_amount: #{@transaction_amount}, secondary_amount:"\
      " #{@secondary_amount}, transaction_api_id: #{@transaction_api_id}, transaction_c1:"\
      " #{@transaction_c1}, transaction_c2: #{@transaction_c2}, transaction_c3:"\
      " #{@transaction_c3}, bank_funded_only_override: #{@bank_funded_only_override},"\
      " allow_partial_authorization_override: #{@allow_partial_authorization_override},"\
      " auto_decline_cvv_override: #{@auto_decline_cvv_override}, auto_decline_street_override:"\
      " #{@auto_decline_street_override}, auto_decline_zip_override:"\
      " #{@auto_decline_zip_override}, ebt_type: #{@ebt_type}, cardholder_present:"\
      " #{@cardholder_present}, card_present: #{@card_present}, secure_auth_data:"\
      " #{@secure_auth_data}, secure_protocol_version: #{@secure_protocol_version},"\
      " secure_collection_indicator: #{@secure_collection_indicator}, secure_cryptogram:"\
      " #{@secure_cryptogram}, secure_directory_server_transaction_id:"\
      " #{@secure_directory_server_transaction_id}, secure_ecomm_url: #{@secure_ecomm_url},"\
      " terminal_serial_number: #{@terminal_serial_number}, threedsecure: #{@threedsecure},"\
      " three_ds_server_trans_id: #{@three_ds_server_trans_id}, wallet_type: #{@wallet_type},"\
      " clerk_id: #{@clerk_id}, voucher_number: #{@voucher_number}, initiation_type:"\
      " #{@initiation_type}, bill_payment: #{@bill_payment}, delay_charge: #{@delay_charge},"\
      " deferred_auth: #{@deferred_auth}, mini_bar: #{@mini_bar}, ebt_food_eligible_amount:"\
      " #{@ebt_food_eligible_amount}, ebt_cash_eligible_amount: #{@ebt_cash_eligible_amount},"\
      " entry_mode_id: #{@entry_mode_id}, track_data: #{@track_data}, account_holder_name:"\
      " #{@account_holder_name}, cvv: #{@cvv}, additional_properties:"\
      " #{get_additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} additional_amounts: #{@additional_amounts.inspect}, billing_address:"\
      " #{@billing_address.inspect}, checkin_date: #{@checkin_date.inspect}, checkout_date:"\
      " #{@checkout_date.inspect}, clerk_number: #{@clerk_number.inspect}, contact_api_id:"\
      " #{@contact_api_id.inspect}, contact_id: #{@contact_id.inspect}, custom_data:"\
      " #{@custom_data.inspect}, customer_id: #{@customer_id.inspect}, description:"\
      " #{@description.inspect}, identity_verification: #{@identity_verification.inspect},"\
      " iias_ind: #{@iias_ind.inspect}, image_front: #{@image_front.inspect}, image_back:"\
      " #{@image_back.inspect}, installment: #{@installment.inspect}, installment_number:"\
      " #{@installment_number.inspect}, installment_count: #{@installment_count.inspect},"\
      " recurring_flag: #{@recurring_flag.inspect}, installment_counter:"\
      " #{@installment_counter.inspect}, installment_total: #{@installment_total.inspect},"\
      " subscription: #{@subscription.inspect}, standing_order: #{@standing_order.inspect},"\
      " location_api_id: #{@location_api_id.inspect}, location_id: #{@location_id.inspect},"\
      " product_transaction_id: #{@product_transaction_id.inspect}, advance_deposit:"\
      " #{@advance_deposit.inspect}, no_show: #{@no_show.inspect}, notification_email_address:"\
      " #{@notification_email_address.inspect}, order_number: #{@order_number.inspect}, po_number:"\
      " #{@po_number.inspect}, quick_invoice_id: #{@quick_invoice_id.inspect}, recurring:"\
      " #{@recurring.inspect}, recurring_number: #{@recurring_number.inspect}, room_num:"\
      " #{@room_num.inspect}, room_rate: #{@room_rate.inspect}, save_account:"\
      " #{@save_account.inspect}, save_account_title: #{@save_account_title.inspect},"\
      " subtotal_amount: #{@subtotal_amount.inspect}, surcharge_amount:"\
      " #{@surcharge_amount.inspect}, tags: #{@tags.inspect}, tax: #{@tax.inspect}, tip_amount:"\
      " #{@tip_amount.inspect}, transaction_amount: #{@transaction_amount.inspect},"\
      " secondary_amount: #{@secondary_amount.inspect}, transaction_api_id:"\
      " #{@transaction_api_id.inspect}, transaction_c1: #{@transaction_c1.inspect},"\
      " transaction_c2: #{@transaction_c2.inspect}, transaction_c3: #{@transaction_c3.inspect},"\
      " bank_funded_only_override: #{@bank_funded_only_override.inspect},"\
      " allow_partial_authorization_override: #{@allow_partial_authorization_override.inspect},"\
      " auto_decline_cvv_override: #{@auto_decline_cvv_override.inspect},"\
      " auto_decline_street_override: #{@auto_decline_street_override.inspect},"\
      " auto_decline_zip_override: #{@auto_decline_zip_override.inspect}, ebt_type:"\
      " #{@ebt_type.inspect}, cardholder_present: #{@cardholder_present.inspect}, card_present:"\
      " #{@card_present.inspect}, secure_auth_data: #{@secure_auth_data.inspect},"\
      " secure_protocol_version: #{@secure_protocol_version.inspect}, secure_collection_indicator:"\
      " #{@secure_collection_indicator.inspect}, secure_cryptogram: #{@secure_cryptogram.inspect},"\
      ' secure_directory_server_transaction_id:'\
      " #{@secure_directory_server_transaction_id.inspect}, secure_ecomm_url:"\
      " #{@secure_ecomm_url.inspect}, terminal_serial_number: #{@terminal_serial_number.inspect},"\
      " threedsecure: #{@threedsecure.inspect}, three_ds_server_trans_id:"\
      " #{@three_ds_server_trans_id.inspect}, wallet_type: #{@wallet_type.inspect}, clerk_id:"\
      " #{@clerk_id.inspect}, voucher_number: #{@voucher_number.inspect}, initiation_type:"\
      " #{@initiation_type.inspect}, bill_payment: #{@bill_payment.inspect}, delay_charge:"\
      " #{@delay_charge.inspect}, deferred_auth: #{@deferred_auth.inspect}, mini_bar:"\
      " #{@mini_bar.inspect}, ebt_food_eligible_amount: #{@ebt_food_eligible_amount.inspect},"\
      " ebt_cash_eligible_amount: #{@ebt_cash_eligible_amount.inspect}, entry_mode_id:"\
      " #{@entry_mode_id.inspect}, track_data: #{@track_data.inspect}, account_holder_name:"\
      " #{@account_holder_name.inspect}, cvv: #{@cvv.inspect}, additional_properties:"\
      " #{get_additional_properties}>"
    end
  end
end
