# fortis_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module FortisApi
  # V1WebhooksTransactionRequest1 Model.
  class V1WebhooksTransactionRequest1 < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Number of seconds before another retry is submitted
    # @return [Integer]
    attr_accessor :attempt_interval

    # The Basic authorization username for the URL, if not supplied, the
    # postback will be submitted without Basic authorization headers
    # >This is only expandable for response but settable in the POST/PUT request
    # >
    # @return [String]
    attr_accessor :basic_auth_username

    # The basic authorization password
    # >This is only expandable for response but settable in the POST/PUT request
    # >
    # @return [String]
    attr_accessor :basic_auth_password

    # An option list of expanded data to send with base data. (i.e. set this
    # field to “contact,account_vault” to get the contact an accountvault used
    # to run a transaction.)
    # @return [String]
    attr_accessor :expands

    # An option list of expanded data to send with base data. (i.e. set this
    # field to “contact,account_vault” to get the contact an accountvault used
    # to run a transaction.)
    # @return [Object]
    attr_accessor :format

    # Flag to indicate whether configuration is active (in effect).
    # @return [TrueClass | FalseClass]
    attr_accessor :is_active

    # The location identifier of the resource you want to recieve postbacks
    # from.
    # @return [String]
    attr_accessor :location_id

    # Location Api ID
    # @return [String]
    attr_accessor :location_api_id

    # To receive postbacks on the creation of a resource
    # @return [TrueClass | FalseClass]
    attr_accessor :on_create

    # To receive postbacks on the updating of a resource
    # @return [TrueClass | FalseClass]
    attr_accessor :on_update

    # To receive postbacks when the record is deleted
    # @return [TrueClass | FalseClass]
    attr_accessor :on_delete

    # Prefer the legacy api format.
    # @return [TrueClass | FalseClass]
    attr_accessor :legacy

    # Postback Config ID
    # @return [String]
    attr_accessor :postback_config_id

    # Required when using 'transaction' or 'transactionbatch' resource
    # @return [String]
    attr_accessor :product_transaction_id

    # Required when using 'transaction' or 'transactionbatch' resource
    # @return [Object]
    attr_accessor :resource

    # Maximum number of attempts on failure
    # @return [Integer]
    attr_accessor :number_of_attempts

    # The URL where the postback will be submitted
    # @return [String]
    attr_accessor :url

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['attempt_interval'] = 'attempt_interval'
      @_hash['basic_auth_username'] = 'basic_auth_username'
      @_hash['basic_auth_password'] = 'basic_auth_password'
      @_hash['expands'] = 'expands'
      @_hash['format'] = 'format'
      @_hash['is_active'] = 'is_active'
      @_hash['location_id'] = 'location_id'
      @_hash['location_api_id'] = 'location_api_id'
      @_hash['on_create'] = 'on_create'
      @_hash['on_update'] = 'on_update'
      @_hash['on_delete'] = 'on_delete'
      @_hash['legacy'] = 'legacy'
      @_hash['postback_config_id'] = 'postback_config_id'
      @_hash['product_transaction_id'] = 'product_transaction_id'
      @_hash['resource'] = 'resource'
      @_hash['number_of_attempts'] = 'number_of_attempts'
      @_hash['url'] = 'url'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        attempt_interval
        basic_auth_username
        basic_auth_password
        expands
        format
        is_active
        location_id
        location_api_id
        on_create
        on_update
        on_delete
        legacy
        postback_config_id
        product_transaction_id
        resource
        number_of_attempts
        url
      ]
    end

    # An array for nullable fields
    def self.nullables
      %w[
        attempt_interval
        basic_auth_username
        basic_auth_password
        expands
        location_id
        location_api_id
        postback_config_id
        product_transaction_id
        number_of_attempts
        url
      ]
    end

    def initialize(attempt_interval: 300, basic_auth_username: SKIP,
                   basic_auth_password: SKIP, expands: SKIP, format: SKIP,
                   is_active: SKIP, location_id: SKIP, location_api_id: SKIP,
                   on_create: SKIP, on_update: SKIP, on_delete: SKIP,
                   legacy: true, postback_config_id: SKIP,
                   product_transaction_id: SKIP, resource: SKIP,
                   number_of_attempts: SKIP, url: SKIP,
                   additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @attempt_interval = attempt_interval unless attempt_interval == SKIP
      @basic_auth_username = basic_auth_username unless basic_auth_username == SKIP
      @basic_auth_password = basic_auth_password unless basic_auth_password == SKIP
      @expands = expands unless expands == SKIP
      @format = format unless format == SKIP
      @is_active = is_active unless is_active == SKIP
      @location_id = location_id unless location_id == SKIP
      @location_api_id = location_api_id unless location_api_id == SKIP
      @on_create = on_create unless on_create == SKIP
      @on_update = on_update unless on_update == SKIP
      @on_delete = on_delete unless on_delete == SKIP
      @legacy = legacy unless legacy == SKIP
      @postback_config_id = postback_config_id unless postback_config_id == SKIP
      @product_transaction_id = product_transaction_id unless product_transaction_id == SKIP
      @resource = resource unless resource == SKIP
      @number_of_attempts = number_of_attempts unless number_of_attempts == SKIP
      @url = url unless url == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      attempt_interval = hash['attempt_interval'] ||= 300
      basic_auth_username =
        hash.key?('basic_auth_username') ? hash['basic_auth_username'] : SKIP
      basic_auth_password =
        hash.key?('basic_auth_password') ? hash['basic_auth_password'] : SKIP
      expands = hash.key?('expands') ? hash['expands'] : SKIP
      format = hash.key?('format') ? hash['format'] : SKIP
      is_active = hash.key?('is_active') ? hash['is_active'] : SKIP
      location_id = hash.key?('location_id') ? hash['location_id'] : SKIP
      location_api_id =
        hash.key?('location_api_id') ? hash['location_api_id'] : SKIP
      on_create = hash.key?('on_create') ? hash['on_create'] : SKIP
      on_update = hash.key?('on_update') ? hash['on_update'] : SKIP
      on_delete = hash.key?('on_delete') ? hash['on_delete'] : SKIP
      legacy = hash['legacy'] ||= true
      postback_config_id =
        hash.key?('postback_config_id') ? hash['postback_config_id'] : SKIP
      product_transaction_id =
        hash.key?('product_transaction_id') ? hash['product_transaction_id'] : SKIP
      resource = hash.key?('resource') ? hash['resource'] : SKIP
      number_of_attempts =
        hash.key?('number_of_attempts') ? hash['number_of_attempts'] : SKIP
      url = hash.key?('url') ? hash['url'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      V1WebhooksTransactionRequest1.new(attempt_interval: attempt_interval,
                                        basic_auth_username: basic_auth_username,
                                        basic_auth_password: basic_auth_password,
                                        expands: expands,
                                        format: format,
                                        is_active: is_active,
                                        location_id: location_id,
                                        location_api_id: location_api_id,
                                        on_create: on_create,
                                        on_update: on_update,
                                        on_delete: on_delete,
                                        legacy: legacy,
                                        postback_config_id: postback_config_id,
                                        product_transaction_id: product_transaction_id,
                                        resource: resource,
                                        number_of_attempts: number_of_attempts,
                                        url: url,
                                        additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} attempt_interval: #{@attempt_interval}, basic_auth_username:"\
      " #{@basic_auth_username}, basic_auth_password: #{@basic_auth_password}, expands:"\
      " #{@expands}, format: #{@format}, is_active: #{@is_active}, location_id: #{@location_id},"\
      " location_api_id: #{@location_api_id}, on_create: #{@on_create}, on_update: #{@on_update},"\
      " on_delete: #{@on_delete}, legacy: #{@legacy}, postback_config_id: #{@postback_config_id},"\
      " product_transaction_id: #{@product_transaction_id}, resource: #{@resource},"\
      " number_of_attempts: #{@number_of_attempts}, url: #{@url}, additional_properties:"\
      " #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} attempt_interval: #{@attempt_interval.inspect}, basic_auth_username:"\
      " #{@basic_auth_username.inspect}, basic_auth_password: #{@basic_auth_password.inspect},"\
      " expands: #{@expands.inspect}, format: #{@format.inspect}, is_active:"\
      " #{@is_active.inspect}, location_id: #{@location_id.inspect}, location_api_id:"\
      " #{@location_api_id.inspect}, on_create: #{@on_create.inspect}, on_update:"\
      " #{@on_update.inspect}, on_delete: #{@on_delete.inspect}, legacy: #{@legacy.inspect},"\
      " postback_config_id: #{@postback_config_id.inspect}, product_transaction_id:"\
      " #{@product_transaction_id.inspect}, resource: #{@resource.inspect}, number_of_attempts:"\
      " #{@number_of_attempts.inspect}, url: #{@url.inspect}, additional_properties:"\
      " #{@additional_properties}>"
    end
  end
end
