# fortis_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module FortisApi
  # Values51.
  class Values51Enum
    VALUES51_ENUM = [
      # TODO: Write general description for ACCOUNT_NUMBER
      ACCOUNT_NUMBER = 'account_number'.freeze,

      # TODO: Write general description for ACCOUNT_HOLDER_NAME
      ACCOUNT_HOLDER_NAME = 'account_holder_name'.freeze,

      # TODO: Write general description for ROUTING_NUMBER
      ROUTING_NUMBER = 'routing_number'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      VALUES51_ENUM.include?(value)
    end

    def self.from_value(value, default_value = ACCOUNT_NUMBER)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'account_number' then ACCOUNT_NUMBER
      when 'account_holder_name' then ACCOUNT_HOLDER_NAME
      when 'routing_number' then ROUTING_NUMBER
      else
        default_value
      end
    end
  end
end
