# fortis_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module FortisApi
  # Wallet Provider
  class WalletProvider
    WALLET_PROVIDER = [
      # TODO: Write general description for GOOGLEPAY
      GOOGLEPAY = 'GooglePay'.freeze,

      # TODO: Write general description for APPLEPAY
      APPLEPAY = 'ApplePay'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      true
    end

    def self.from_value(value, default_value = GOOGLEPAY)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'googlepay' then GOOGLEPAY
      when 'applepay' then APPLEPAY
      else
        default_value
      end
    end
  end
end
