# fortis_api
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module FortisApi
  # TransactionsCreditCardController
  class TransactionsCreditCardController < BaseController
    # Create a new keyed Credit Card authorization only transaction
    # @param [V1TransactionsCcAuthOnlyKeyedRequest] body Required parameter:
    # TODO: type description here
    # @param [Array[Expand60]] expand Optional parameter: Most endpoints in the
    # API have a way to retrieve extra data related to the current record being
    # retrieved. For example, if the API request is for the accountvaults
    # endpoint, and the end user also needs to know which contact the token
    # belongs to, this data can be returned in the accountvaults endpoint
    # request.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def cc_auth_only(body,
                     expand: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/v1/transactions/cc/auth-only/keyed',
                                     Server::DEFAULT)
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(body)
                                .is_required(true))
                   .query_param(new_parameter(expand, key: 'expand'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .body_serializer(proc do |param| param.to_json unless param.nil? end)
                   .auth(And.new('user-id', 'user-api-key', 'developer-id')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(ResponseTransaction.method(:from_hash))
                    .is_api_response(true)
                    .local_error('401',
                                 'Unauthorized',
                                 Response401TokenException)
                    .local_error('412',
                                 'Precondition Failed',
                                 Response412Exception))
        .execute
    end

    # Create a new Credit Card authorization only transaction using previous
    # transaction id
    # @param [V1TransactionsCcAuthOnlyPrevTrxnRequest] body Required parameter:
    # TODO: type description here
    # @param [Array[Expand60]] expand Optional parameter: Most endpoints in the
    # API have a way to retrieve extra data related to the current record being
    # retrieved. For example, if the API request is for the accountvaults
    # endpoint, and the end user also needs to know which contact the token
    # belongs to, this data can be returned in the accountvaults endpoint
    # request.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def cc_auth_only_previous_transaction(body,
                                          expand: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/v1/transactions/cc/auth-only/prev-trxn',
                                     Server::DEFAULT)
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(body)
                                .is_required(true))
                   .query_param(new_parameter(expand, key: 'expand'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .body_serializer(proc do |param| param.to_json unless param.nil? end)
                   .auth(And.new('user-id', 'user-api-key', 'developer-id')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(ResponseTransaction.method(:from_hash))
                    .is_api_response(true)
                    .local_error('401',
                                 'Unauthorized',
                                 Response401TokenException)
                    .local_error('412',
                                 'Precondition Failed',
                                 Response412Exception))
        .execute
    end

    # Create a new swiped Credit Card authorization only transaction
    # @param [V1TransactionsCcAuthOnlySwipedRequest] body Required parameter:
    # TODO: type description here
    # @param [Array[Expand60]] expand Optional parameter: Most endpoints in the
    # API have a way to retrieve extra data related to the current record being
    # retrieved. For example, if the API request is for the accountvaults
    # endpoint, and the end user also needs to know which contact the token
    # belongs to, this data can be returned in the accountvaults endpoint
    # request.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def cc_auth_only_swiped(body,
                            expand: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/v1/transactions/cc/auth-only/swiped',
                                     Server::DEFAULT)
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(body)
                                .is_required(true))
                   .query_param(new_parameter(expand, key: 'expand'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .body_serializer(proc do |param| param.to_json unless param.nil? end)
                   .auth(And.new('user-id', 'user-api-key', 'developer-id')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(ResponseTransaction.method(:from_hash))
                    .is_api_response(true)
                    .local_error('401',
                                 'Unauthorized',
                                 Response401TokenException)
                    .local_error('412',
                                 'Precondition Failed',
                                 Response412Exception))
        .execute
    end

    # Create a new Tap To Pay Credit Card authorization only transaction
    # @param [V1TransactionsCcAuthOnlyTaptopayRequest] body Required parameter:
    # TODO: type description here
    # @param [Array[Expand60]] expand Optional parameter: Most endpoints in the
    # API have a way to retrieve extra data related to the current record being
    # retrieved. For example, if the API request is for the accountvaults
    # endpoint, and the end user also needs to know which contact the token
    # belongs to, this data can be returned in the accountvaults endpoint
    # request.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def cc_auth_only_tap_to_pay(body,
                                expand: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/v1/transactions/cc/auth-only/taptopay',
                                     Server::DEFAULT)
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(body)
                                .is_required(true))
                   .query_param(new_parameter(expand, key: 'expand'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .body_serializer(proc do |param| param.to_json unless param.nil? end)
                   .auth(And.new('user-id', 'user-api-key', 'developer-id')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(ResponseTransaction.method(:from_hash))
                    .is_api_response(true)
                    .local_error('401',
                                 'Unauthorized',
                                 Response401TokenException)
                    .local_error('412',
                                 'Precondition Failed',
                                 Response412Exception))
        .execute
    end

    # Create a new terminal Credit Card authorization only transaction
    # @param [V1TransactionsCcAuthOnlyTerminalRequest] body Required parameter:
    # TODO: type description here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def cc_auth_only_terminal(body)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/v1/transactions/cc/auth-only/terminal',
                                     Server::DEFAULT)
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(body)
                                .is_required(true))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .body_serializer(proc do |param| param.to_json unless param.nil? end)
                   .auth(And.new('user-id', 'user-api-key', 'developer-id')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(ResponseTransactionProcessing.method(:from_hash))
                    .is_api_response(true)
                    .local_error('401',
                                 'Unauthorized',
                                 Response401TokenException)
                    .local_error('412',
                                 'Precondition Failed',
                                 Response412Exception))
        .execute
    end

    # Create a new ticket Credit Card authorization only transaction
    # @param [V1TransactionsCcAuthOnlyTicketRequest] body Required parameter:
    # TODO: type description here
    # @param [Array[Expand60]] expand Optional parameter: Most endpoints in the
    # API have a way to retrieve extra data related to the current record being
    # retrieved. For example, if the API request is for the accountvaults
    # endpoint, and the end user also needs to know which contact the token
    # belongs to, this data can be returned in the accountvaults endpoint
    # request.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def cc_auth_only_ticket(body,
                            expand: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/v1/transactions/cc/auth-only/ticket',
                                     Server::DEFAULT)
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(body)
                                .is_required(true))
                   .query_param(new_parameter(expand, key: 'expand'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .body_serializer(proc do |param| param.to_json unless param.nil? end)
                   .auth(And.new('user-id', 'user-api-key', 'developer-id')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(ResponseTransaction.method(:from_hash))
                    .is_api_response(true)
                    .local_error('401',
                                 'Unauthorized',
                                 Response401TokenException)
                    .local_error('412',
                                 'Precondition Failed',
                                 Response412Exception))
        .execute
    end

    # Create a new tokenized Credit Card authorization only transaction
    # @param [V1TransactionsCcAuthOnlyTokenRequest] body Required parameter:
    # TODO: type description here
    # @param [Array[Expand60]] expand Optional parameter: Most endpoints in the
    # API have a way to retrieve extra data related to the current record being
    # retrieved. For example, if the API request is for the accountvaults
    # endpoint, and the end user also needs to know which contact the token
    # belongs to, this data can be returned in the accountvaults endpoint
    # request.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def cc_auth_only_tokenized(body,
                               expand: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/v1/transactions/cc/auth-only/token',
                                     Server::DEFAULT)
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(body)
                                .is_required(true))
                   .query_param(new_parameter(expand, key: 'expand'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .body_serializer(proc do |param| param.to_json unless param.nil? end)
                   .auth(And.new('user-id', 'user-api-key', 'developer-id')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(ResponseTransaction.method(:from_hash))
                    .is_api_response(true)
                    .local_error('401',
                                 'Unauthorized',
                                 Response401TokenException)
                    .local_error('412',
                                 'Precondition Failed',
                                 Response412Exception))
        .execute
    end

    # Create a new Wallet Credit Card authorization only transaction
    # @param [V1TransactionsCcAuthOnlyWalletRequest] body Required parameter:
    # TODO: type description here
    # @param [Array[Expand60]] expand Optional parameter: Most endpoints in the
    # API have a way to retrieve extra data related to the current record being
    # retrieved. For example, if the API request is for the accountvaults
    # endpoint, and the end user also needs to know which contact the token
    # belongs to, this data can be returned in the accountvaults endpoint
    # request.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def cc_auth_only_wallet(body,
                            expand: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/v1/transactions/cc/auth-only/wallet',
                                     Server::DEFAULT)
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(body)
                                .is_required(true))
                   .query_param(new_parameter(expand, key: 'expand'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .body_serializer(proc do |param| param.to_json unless param.nil? end)
                   .auth(And.new('user-id', 'user-api-key', 'developer-id')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(ResponseTransaction.method(:from_hash))
                    .is_api_response(true)
                    .local_error('401',
                                 'Unauthorized',
                                 Response401TokenException)
                    .local_error('412',
                                 'Precondition Failed',
                                 Response412Exception))
        .execute
    end

    # Create a new keyed Credit Card AVS only transaction
    # @param [V1TransactionsCcAvsOnlyKeyedRequest] body Required parameter:
    # TODO: type description here
    # @param [Array[Expand60]] expand Optional parameter: Most endpoints in the
    # API have a way to retrieve extra data related to the current record being
    # retrieved. For example, if the API request is for the accountvaults
    # endpoint, and the end user also needs to know which contact the token
    # belongs to, this data can be returned in the accountvaults endpoint
    # request.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def ccavs(body,
              expand: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/v1/transactions/cc/avs-only/keyed',
                                     Server::DEFAULT)
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(body)
                                .is_required(true))
                   .query_param(new_parameter(expand, key: 'expand'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .body_serializer(proc do |param| param.to_json unless param.nil? end)
                   .auth(And.new('user-id', 'user-api-key', 'developer-id')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(ResponseTransaction.method(:from_hash))
                    .is_api_response(true)
                    .local_error('401',
                                 'Unauthorized',
                                 Response401TokenException)
                    .local_error('412',
                                 'Precondition Failed',
                                 Response412Exception))
        .execute
    end

    # Create a new Credit Card AVS only transaction using previous transaction
    # id
    # @param [V1TransactionsCcAvsOnlyPrevTrxnRequest] body Required parameter:
    # TODO: type description here
    # @param [Array[Expand60]] expand Optional parameter: Most endpoints in the
    # API have a way to retrieve extra data related to the current record being
    # retrieved. For example, if the API request is for the accountvaults
    # endpoint, and the end user also needs to know which contact the token
    # belongs to, this data can be returned in the accountvaults endpoint
    # request.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def ccavs_previous_transaction(body,
                                   expand: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/v1/transactions/cc/avs-only/prev-trxn',
                                     Server::DEFAULT)
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(body)
                                .is_required(true))
                   .query_param(new_parameter(expand, key: 'expand'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .body_serializer(proc do |param| param.to_json unless param.nil? end)
                   .auth(And.new('user-id', 'user-api-key', 'developer-id')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(ResponseTransaction.method(:from_hash))
                    .is_api_response(true)
                    .local_error('401',
                                 'Unauthorized',
                                 Response401TokenException)
                    .local_error('412',
                                 'Precondition Failed',
                                 Response412Exception))
        .execute
    end

    # Create a new swiped Credit Card AVS only transaction
    # @param [V1TransactionsCcAvsOnlySwipedRequest] body Required parameter:
    # TODO: type description here
    # @param [Array[Expand60]] expand Optional parameter: Most endpoints in the
    # API have a way to retrieve extra data related to the current record being
    # retrieved. For example, if the API request is for the accountvaults
    # endpoint, and the end user also needs to know which contact the token
    # belongs to, this data can be returned in the accountvaults endpoint
    # request.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def ccavs_swiped(body,
                     expand: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/v1/transactions/cc/avs-only/swiped',
                                     Server::DEFAULT)
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(body)
                                .is_required(true))
                   .query_param(new_parameter(expand, key: 'expand'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .body_serializer(proc do |param| param.to_json unless param.nil? end)
                   .auth(And.new('user-id', 'user-api-key', 'developer-id')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(ResponseTransaction.method(:from_hash))
                    .is_api_response(true)
                    .local_error('401',
                                 'Unauthorized',
                                 Response401TokenException)
                    .local_error('412',
                                 'Precondition Failed',
                                 Response412Exception))
        .execute
    end

    # Create a new terminal Credit Card AVS only transaction
    # @param [V1TransactionsCcAvsOnlyTerminalRequest] body Required parameter:
    # TODO: type description here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def ccavs_terminal(body)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/v1/transactions/cc/avs-only/terminal',
                                     Server::DEFAULT)
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(body)
                                .is_required(true))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .body_serializer(proc do |param| param.to_json unless param.nil? end)
                   .auth(And.new('user-id', 'user-api-key', 'developer-id')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(ResponseTransactionProcessing.method(:from_hash))
                    .is_api_response(true)
                    .local_error('401',
                                 'Unauthorized',
                                 Response401TokenException)
                    .local_error('412',
                                 'Precondition Failed',
                                 Response412Exception))
        .execute
    end

    # Create a new ticket Credit Card AVS only transaction
    # @param [V1TransactionsCcAvsOnlyTicketRequest] body Required parameter:
    # TODO: type description here
    # @param [Array[Expand60]] expand Optional parameter: Most endpoints in the
    # API have a way to retrieve extra data related to the current record being
    # retrieved. For example, if the API request is for the accountvaults
    # endpoint, and the end user also needs to know which contact the token
    # belongs to, this data can be returned in the accountvaults endpoint
    # request.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def ccavs_ticket(body,
                     expand: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/v1/transactions/cc/avs-only/ticket',
                                     Server::DEFAULT)
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(body)
                                .is_required(true))
                   .query_param(new_parameter(expand, key: 'expand'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .body_serializer(proc do |param| param.to_json unless param.nil? end)
                   .auth(And.new('user-id', 'user-api-key', 'developer-id')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(ResponseTransaction.method(:from_hash))
                    .is_api_response(true)
                    .local_error('401',
                                 'Unauthorized',
                                 Response401TokenException)
                    .local_error('412',
                                 'Precondition Failed',
                                 Response412Exception))
        .execute
    end

    # Create a new tokenized Credit Card AVS only transaction
    # @param [V1TransactionsCcAvsOnlyTokenRequest] body Required parameter:
    # TODO: type description here
    # @param [Array[Expand60]] expand Optional parameter: Most endpoints in the
    # API have a way to retrieve extra data related to the current record being
    # retrieved. For example, if the API request is for the accountvaults
    # endpoint, and the end user also needs to know which contact the token
    # belongs to, this data can be returned in the accountvaults endpoint
    # request.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def ccavs_tokenized(body,
                        expand: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/v1/transactions/cc/avs-only/token',
                                     Server::DEFAULT)
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(body)
                                .is_required(true))
                   .query_param(new_parameter(expand, key: 'expand'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .body_serializer(proc do |param| param.to_json unless param.nil? end)
                   .auth(And.new('user-id', 'user-api-key', 'developer-id')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(ResponseTransaction.method(:from_hash))
                    .is_api_response(true)
                    .local_error('401',
                                 'Unauthorized',
                                 Response401TokenException)
                    .local_error('412',
                                 'Precondition Failed',
                                 Response412Exception))
        .execute
    end

    # Create a new Wallet Credit Card AVS only transaction
    # @param [V1TransactionsCcAvsOnlyWalletRequest] body Required parameter:
    # TODO: type description here
    # @param [Array[Expand60]] expand Optional parameter: Most endpoints in the
    # API have a way to retrieve extra data related to the current record being
    # retrieved. For example, if the API request is for the accountvaults
    # endpoint, and the end user also needs to know which contact the token
    # belongs to, this data can be returned in the accountvaults endpoint
    # request.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def ccavs_wallet(body,
                     expand: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/v1/transactions/cc/avs-only/wallet',
                                     Server::DEFAULT)
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(body)
                                .is_required(true))
                   .query_param(new_parameter(expand, key: 'expand'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .body_serializer(proc do |param| param.to_json unless param.nil? end)
                   .auth(And.new('user-id', 'user-api-key', 'developer-id')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(ResponseTransaction.method(:from_hash))
                    .is_api_response(true)
                    .local_error('401',
                                 'Unauthorized',
                                 Response401TokenException)
                    .local_error('412',
                                 'Precondition Failed',
                                 Response412Exception))
        .execute
    end

    # Create a new keyed Credit Card balance inquiry transaction
    # @param [V1TransactionsCcBalanceInquiryKeyedRequest] body Required
    # parameter: TODO: type description here
    # @param [Array[Expand60]] expand Optional parameter: Most endpoints in the
    # API have a way to retrieve extra data related to the current record being
    # retrieved. For example, if the API request is for the accountvaults
    # endpoint, and the end user also needs to know which contact the token
    # belongs to, this data can be returned in the accountvaults endpoint
    # request.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def cc_balance_inquiry(body,
                           expand: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/v1/transactions/cc/balance-inquiry/keyed',
                                     Server::DEFAULT)
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(body)
                                .is_required(true))
                   .query_param(new_parameter(expand, key: 'expand'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .body_serializer(proc do |param| param.to_json unless param.nil? end)
                   .auth(And.new('user-id', 'user-api-key', 'developer-id')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(ResponseTransaction.method(:from_hash))
                    .is_api_response(true)
                    .local_error('401',
                                 'Unauthorized',
                                 Response401TokenException)
                    .local_error('412',
                                 'Precondition Failed',
                                 Response412Exception))
        .execute
    end

    # Create a new Credit Card balance inquiry transaction using previous
    # transaction id
    # @param [V1TransactionsCcBalanceInquiryPrevTrxnRequest] body Required
    # parameter: TODO: type description here
    # @param [Array[Expand60]] expand Optional parameter: Most endpoints in the
    # API have a way to retrieve extra data related to the current record being
    # retrieved. For example, if the API request is for the accountvaults
    # endpoint, and the end user also needs to know which contact the token
    # belongs to, this data can be returned in the accountvaults endpoint
    # request.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def cc_balance_inquiry_previous_transaction(body,
                                                expand: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/v1/transactions/cc/balance-inquiry/prev-trxn',
                                     Server::DEFAULT)
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(body)
                                .is_required(true))
                   .query_param(new_parameter(expand, key: 'expand'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .body_serializer(proc do |param| param.to_json unless param.nil? end)
                   .auth(And.new('user-id', 'user-api-key', 'developer-id')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(ResponseTransaction.method(:from_hash))
                    .is_api_response(true)
                    .local_error('401',
                                 'Unauthorized',
                                 Response401TokenException)
                    .local_error('412',
                                 'Precondition Failed',
                                 Response412Exception))
        .execute
    end

    # Create a new swiped Credit Card balance inquiry transaction
    # @param [V1TransactionsCcBalanceInquirySwipedRequest] body Required
    # parameter: TODO: type description here
    # @param [Array[Expand60]] expand Optional parameter: Most endpoints in the
    # API have a way to retrieve extra data related to the current record being
    # retrieved. For example, if the API request is for the accountvaults
    # endpoint, and the end user also needs to know which contact the token
    # belongs to, this data can be returned in the accountvaults endpoint
    # request.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def cc_balance_inquiry_swiped(body,
                                  expand: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/v1/transactions/cc/balance-inquiry/swiped',
                                     Server::DEFAULT)
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(body)
                                .is_required(true))
                   .query_param(new_parameter(expand, key: 'expand'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .body_serializer(proc do |param| param.to_json unless param.nil? end)
                   .auth(And.new('user-id', 'user-api-key', 'developer-id')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(ResponseTransaction.method(:from_hash))
                    .is_api_response(true)
                    .local_error('401',
                                 'Unauthorized',
                                 Response401TokenException)
                    .local_error('412',
                                 'Precondition Failed',
                                 Response412Exception))
        .execute
    end

    # Create a new terminal Credit Card balance inquiry transaction
    # @param [V1TransactionsCcBalanceInquiryTerminalRequest] body Required
    # parameter: TODO: type description here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def cc_balance_inquiry_terminal(body)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/v1/transactions/cc/balance-inquiry/terminal',
                                     Server::DEFAULT)
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(body)
                                .is_required(true))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .body_serializer(proc do |param| param.to_json unless param.nil? end)
                   .auth(And.new('user-id', 'user-api-key', 'developer-id')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(ResponseTransactionProcessing.method(:from_hash))
                    .is_api_response(true)
                    .local_error('401',
                                 'Unauthorized',
                                 Response401TokenException)
                    .local_error('412',
                                 'Precondition Failed',
                                 Response412Exception))
        .execute
    end

    # Create a new Ticket Credit Card balance inquiry transaction
    # @param [V1TransactionsCcBalanceInquiryTicketRequest] body Required
    # parameter: TODO: type description here
    # @param [Array[Expand60]] expand Optional parameter: Most endpoints in the
    # API have a way to retrieve extra data related to the current record being
    # retrieved. For example, if the API request is for the accountvaults
    # endpoint, and the end user also needs to know which contact the token
    # belongs to, this data can be returned in the accountvaults endpoint
    # request.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def cc_balance_inquiry_ticket(body,
                                  expand: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/v1/transactions/cc/balance-inquiry/ticket',
                                     Server::DEFAULT)
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(body)
                                .is_required(true))
                   .query_param(new_parameter(expand, key: 'expand'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .body_serializer(proc do |param| param.to_json unless param.nil? end)
                   .auth(And.new('user-id', 'user-api-key', 'developer-id')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(ResponseTransaction.method(:from_hash))
                    .is_api_response(true)
                    .local_error('401',
                                 'Unauthorized',
                                 Response401TokenException)
                    .local_error('412',
                                 'Precondition Failed',
                                 Response412Exception))
        .execute
    end

    # Create a new tokenized Credit Card balance inquiry transaction
    # @param [V1TransactionsCcBalanceInquiryTokenRequest] body Required
    # parameter: TODO: type description here
    # @param [Array[Expand60]] expand Optional parameter: Most endpoints in the
    # API have a way to retrieve extra data related to the current record being
    # retrieved. For example, if the API request is for the accountvaults
    # endpoint, and the end user also needs to know which contact the token
    # belongs to, this data can be returned in the accountvaults endpoint
    # request.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def cc_balance_inquiry_tokenized(body,
                                     expand: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/v1/transactions/cc/balance-inquiry/token',
                                     Server::DEFAULT)
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(body)
                                .is_required(true))
                   .query_param(new_parameter(expand, key: 'expand'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .body_serializer(proc do |param| param.to_json unless param.nil? end)
                   .auth(And.new('user-id', 'user-api-key', 'developer-id')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(ResponseTransaction.method(:from_hash))
                    .is_api_response(true)
                    .local_error('401',
                                 'Unauthorized',
                                 Response401TokenException)
                    .local_error('412',
                                 'Precondition Failed',
                                 Response412Exception))
        .execute
    end

    # Create a new Wallet Credit Card balance inquiry transaction
    # @param [V1TransactionsCcBalanceInquiryWalletRequest] body Required
    # parameter: TODO: type description here
    # @param [Array[Expand60]] expand Optional parameter: Most endpoints in the
    # API have a way to retrieve extra data related to the current record being
    # retrieved. For example, if the API request is for the accountvaults
    # endpoint, and the end user also needs to know which contact the token
    # belongs to, this data can be returned in the accountvaults endpoint
    # request.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def cc_balance_inquiry_wallet(body,
                                  expand: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/v1/transactions/cc/balance-inquiry/wallet',
                                     Server::DEFAULT)
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(body)
                                .is_required(true))
                   .query_param(new_parameter(expand, key: 'expand'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .body_serializer(proc do |param| param.to_json unless param.nil? end)
                   .auth(And.new('user-id', 'user-api-key', 'developer-id')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(ResponseTransaction.method(:from_hash))
                    .is_api_response(true)
                    .local_error('401',
                                 'Unauthorized',
                                 Response401TokenException)
                    .local_error('412',
                                 'Precondition Failed',
                                 Response412Exception))
        .execute
    end

    # Create a new keyed Credit Card force transaction
    # @param [V1TransactionsCcForceKeyedRequest] body Required parameter: TODO:
    # type description here
    # @param [Array[Expand60]] expand Optional parameter: Most endpoints in the
    # API have a way to retrieve extra data related to the current record being
    # retrieved. For example, if the API request is for the accountvaults
    # endpoint, and the end user also needs to know which contact the token
    # belongs to, this data can be returned in the accountvaults endpoint
    # request.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def cc_force(body,
                 expand: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/v1/transactions/cc/force/keyed',
                                     Server::DEFAULT)
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(body)
                                .is_required(true))
                   .query_param(new_parameter(expand, key: 'expand'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .body_serializer(proc do |param| param.to_json unless param.nil? end)
                   .auth(And.new('user-id', 'user-api-key', 'developer-id')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(ResponseTransaction.method(:from_hash))
                    .is_api_response(true)
                    .local_error('401',
                                 'Unauthorized',
                                 Response401TokenException)
                    .local_error('412',
                                 'Precondition Failed',
                                 Response412Exception))
        .execute
    end

    # Create a new Credit Card force transaction using previous transaction id
    # @param [V1TransactionsCcForcePrevTrxnRequest] body Required parameter:
    # TODO: type description here
    # @param [Array[Expand60]] expand Optional parameter: Most endpoints in the
    # API have a way to retrieve extra data related to the current record being
    # retrieved. For example, if the API request is for the accountvaults
    # endpoint, and the end user also needs to know which contact the token
    # belongs to, this data can be returned in the accountvaults endpoint
    # request.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def cc_force_previous_transaction(body,
                                      expand: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/v1/transactions/cc/force/prev-trxn',
                                     Server::DEFAULT)
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(body)
                                .is_required(true))
                   .query_param(new_parameter(expand, key: 'expand'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .body_serializer(proc do |param| param.to_json unless param.nil? end)
                   .auth(And.new('user-id', 'user-api-key', 'developer-id')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(ResponseTransaction.method(:from_hash))
                    .is_api_response(true)
                    .local_error('401',
                                 'Unauthorized',
                                 Response401TokenException)
                    .local_error('412',
                                 'Precondition Failed',
                                 Response412Exception))
        .execute
    end

    # Create a new swiped Credit Card force transaction
    # @param [V1TransactionsCcForceSwipedRequest] body Required parameter: TODO:
    # type description here
    # @param [Array[Expand60]] expand Optional parameter: Most endpoints in the
    # API have a way to retrieve extra data related to the current record being
    # retrieved. For example, if the API request is for the accountvaults
    # endpoint, and the end user also needs to know which contact the token
    # belongs to, this data can be returned in the accountvaults endpoint
    # request.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def cc_force_swiped(body,
                        expand: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/v1/transactions/cc/force/swiped',
                                     Server::DEFAULT)
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(body)
                                .is_required(true))
                   .query_param(new_parameter(expand, key: 'expand'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .body_serializer(proc do |param| param.to_json unless param.nil? end)
                   .auth(And.new('user-id', 'user-api-key', 'developer-id')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(ResponseTransaction.method(:from_hash))
                    .is_api_response(true)
                    .local_error('401',
                                 'Unauthorized',
                                 Response401TokenException)
                    .local_error('412',
                                 'Precondition Failed',
                                 Response412Exception))
        .execute
    end

    # Create a new ticket Credit Card force transaction
    # @param [V1TransactionsCcForceTicketRequest] body Required parameter: TODO:
    # type description here
    # @param [Array[Expand60]] expand Optional parameter: Most endpoints in the
    # API have a way to retrieve extra data related to the current record being
    # retrieved. For example, if the API request is for the accountvaults
    # endpoint, and the end user also needs to know which contact the token
    # belongs to, this data can be returned in the accountvaults endpoint
    # request.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def cc_force_ticket(body,
                        expand: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/v1/transactions/cc/force/ticket',
                                     Server::DEFAULT)
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(body)
                                .is_required(true))
                   .query_param(new_parameter(expand, key: 'expand'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .body_serializer(proc do |param| param.to_json unless param.nil? end)
                   .auth(And.new('user-id', 'user-api-key', 'developer-id')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(ResponseTransaction.method(:from_hash))
                    .is_api_response(true)
                    .local_error('401',
                                 'Unauthorized',
                                 Response401TokenException)
                    .local_error('412',
                                 'Precondition Failed',
                                 Response412Exception))
        .execute
    end

    # Create a new tokenized Credit Card force transaction
    # @param [V1TransactionsCcForceTokenRequest] body Required parameter: TODO:
    # type description here
    # @param [Array[Expand60]] expand Optional parameter: Most endpoints in the
    # API have a way to retrieve extra data related to the current record being
    # retrieved. For example, if the API request is for the accountvaults
    # endpoint, and the end user also needs to know which contact the token
    # belongs to, this data can be returned in the accountvaults endpoint
    # request.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def cc_force_tokenized(body,
                           expand: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/v1/transactions/cc/force/token',
                                     Server::DEFAULT)
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(body)
                                .is_required(true))
                   .query_param(new_parameter(expand, key: 'expand'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .body_serializer(proc do |param| param.to_json unless param.nil? end)
                   .auth(And.new('user-id', 'user-api-key', 'developer-id')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(ResponseTransaction.method(:from_hash))
                    .is_api_response(true)
                    .local_error('401',
                                 'Unauthorized',
                                 Response401TokenException)
                    .local_error('412',
                                 'Precondition Failed',
                                 Response412Exception))
        .execute
    end

    # Create a new Wallet Credit Card force transaction
    # @param [V1TransactionsCcForceWalletRequest] body Required parameter: TODO:
    # type description here
    # @param [Array[Expand60]] expand Optional parameter: Most endpoints in the
    # API have a way to retrieve extra data related to the current record being
    # retrieved. For example, if the API request is for the accountvaults
    # endpoint, and the end user also needs to know which contact the token
    # belongs to, this data can be returned in the accountvaults endpoint
    # request.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def cc_force_wallet(body,
                        expand: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/v1/transactions/cc/force/wallet',
                                     Server::DEFAULT)
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(body)
                                .is_required(true))
                   .query_param(new_parameter(expand, key: 'expand'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .body_serializer(proc do |param| param.to_json unless param.nil? end)
                   .auth(And.new('user-id', 'user-api-key', 'developer-id')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(ResponseTransaction.method(:from_hash))
                    .is_api_response(true)
                    .local_error('401',
                                 'Unauthorized',
                                 Response401TokenException)
                    .local_error('412',
                                 'Precondition Failed',
                                 Response412Exception))
        .execute
    end

    # Create a new keyed Credit Card refund transaction
    # @param [V1TransactionsCcRefundKeyedRequest] body Required parameter: TODO:
    # type description here
    # @param [Array[Expand60]] expand Optional parameter: Most endpoints in the
    # API have a way to retrieve extra data related to the current record being
    # retrieved. For example, if the API request is for the accountvaults
    # endpoint, and the end user also needs to know which contact the token
    # belongs to, this data can be returned in the accountvaults endpoint
    # request.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def cc_refund(body,
                  expand: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/v1/transactions/cc/refund/keyed',
                                     Server::DEFAULT)
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(body)
                                .is_required(true))
                   .query_param(new_parameter(expand, key: 'expand'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .body_serializer(proc do |param| param.to_json unless param.nil? end)
                   .auth(And.new('user-id', 'user-api-key', 'developer-id')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(ResponseTransaction.method(:from_hash))
                    .is_api_response(true)
                    .local_error('401',
                                 'Unauthorized',
                                 Response401TokenException)
                    .local_error('412',
                                 'Precondition Failed',
                                 Response412Exception))
        .execute
    end

    # Create a new Credit Card refund transaction using previous transaction id
    # @param [V1TransactionsCcRefundPrevTrxnRequest] body Required parameter:
    # TODO: type description here
    # @param [Array[Expand60]] expand Optional parameter: Most endpoints in the
    # API have a way to retrieve extra data related to the current record being
    # retrieved. For example, if the API request is for the accountvaults
    # endpoint, and the end user also needs to know which contact the token
    # belongs to, this data can be returned in the accountvaults endpoint
    # request.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def cc_refund_previous_transaction(body,
                                       expand: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/v1/transactions/cc/refund/prev-trxn',
                                     Server::DEFAULT)
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(body)
                                .is_required(true))
                   .query_param(new_parameter(expand, key: 'expand'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .body_serializer(proc do |param| param.to_json unless param.nil? end)
                   .auth(And.new('user-id', 'user-api-key', 'developer-id')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(ResponseTransaction.method(:from_hash))
                    .is_api_response(true)
                    .local_error('401',
                                 'Unauthorized',
                                 Response401TokenException)
                    .local_error('412',
                                 'Precondition Failed',
                                 Response412Exception))
        .execute
    end

    # Create a new swiped Credit Card refund transaction
    # @param [V1TransactionsCcRefundSwipedRequest] body Required parameter:
    # TODO: type description here
    # @param [Array[Expand60]] expand Optional parameter: Most endpoints in the
    # API have a way to retrieve extra data related to the current record being
    # retrieved. For example, if the API request is for the accountvaults
    # endpoint, and the end user also needs to know which contact the token
    # belongs to, this data can be returned in the accountvaults endpoint
    # request.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def cc_refund_swiped(body,
                         expand: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/v1/transactions/cc/refund/swiped',
                                     Server::DEFAULT)
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(body)
                                .is_required(true))
                   .query_param(new_parameter(expand, key: 'expand'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .body_serializer(proc do |param| param.to_json unless param.nil? end)
                   .auth(And.new('user-id', 'user-api-key', 'developer-id')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(ResponseTransaction.method(:from_hash))
                    .is_api_response(true)
                    .local_error('401',
                                 'Unauthorized',
                                 Response401TokenException)
                    .local_error('412',
                                 'Precondition Failed',
                                 Response412Exception))
        .execute
    end

    # Create a new Tap To Pay Credit Card refund transaction
    # @param [V1TransactionsCcRefundTaptopayRequest] body Required parameter:
    # TODO: type description here
    # @param [Array[Expand60]] expand Optional parameter: Most endpoints in the
    # API have a way to retrieve extra data related to the current record being
    # retrieved. For example, if the API request is for the accountvaults
    # endpoint, and the end user also needs to know which contact the token
    # belongs to, this data can be returned in the accountvaults endpoint
    # request.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def cc_refund_tap_to_pay(body,
                             expand: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/v1/transactions/cc/refund/taptopay',
                                     Server::DEFAULT)
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(body)
                                .is_required(true))
                   .query_param(new_parameter(expand, key: 'expand'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .body_serializer(proc do |param| param.to_json unless param.nil? end)
                   .auth(And.new('user-id', 'user-api-key', 'developer-id')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(ResponseTransaction.method(:from_hash))
                    .is_api_response(true)
                    .local_error('401',
                                 'Unauthorized',
                                 Response401TokenException)
                    .local_error('412',
                                 'Precondition Failed',
                                 Response412Exception))
        .execute
    end

    # Create a new terminal Credit Card refund transaction
    # @param [V1TransactionsCcRefundTerminalRequest] body Required parameter:
    # TODO: type description here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def cc_refund_terminal(body)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/v1/transactions/cc/refund/terminal',
                                     Server::DEFAULT)
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(body)
                                .is_required(true))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .body_serializer(proc do |param| param.to_json unless param.nil? end)
                   .auth(And.new('user-id', 'user-api-key', 'developer-id')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(ResponseTransactionProcessing.method(:from_hash))
                    .is_api_response(true)
                    .local_error('401',
                                 'Unauthorized',
                                 Response401TokenException)
                    .local_error('412',
                                 'Precondition Failed',
                                 Response412Exception))
        .execute
    end

    # Create a new ticket Credit Card refund transaction
    # @param [V1TransactionsCcRefundTicketRequest] body Required parameter:
    # TODO: type description here
    # @param [Array[Expand60]] expand Optional parameter: Most endpoints in the
    # API have a way to retrieve extra data related to the current record being
    # retrieved. For example, if the API request is for the accountvaults
    # endpoint, and the end user also needs to know which contact the token
    # belongs to, this data can be returned in the accountvaults endpoint
    # request.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def cc_refund_ticket(body,
                         expand: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/v1/transactions/cc/refund/ticket',
                                     Server::DEFAULT)
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(body)
                                .is_required(true))
                   .query_param(new_parameter(expand, key: 'expand'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .body_serializer(proc do |param| param.to_json unless param.nil? end)
                   .auth(And.new('user-id', 'user-api-key', 'developer-id')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(ResponseTransaction.method(:from_hash))
                    .is_api_response(true)
                    .local_error('401',
                                 'Unauthorized',
                                 Response401TokenException)
                    .local_error('412',
                                 'Precondition Failed',
                                 Response412Exception))
        .execute
    end

    # Create a new tokenized Credit Card refund transaction
    # @param [V1TransactionsCcRefundTokenRequest] body Required parameter: TODO:
    # type description here
    # @param [Array[Expand60]] expand Optional parameter: Most endpoints in the
    # API have a way to retrieve extra data related to the current record being
    # retrieved. For example, if the API request is for the accountvaults
    # endpoint, and the end user also needs to know which contact the token
    # belongs to, this data can be returned in the accountvaults endpoint
    # request.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def cc_refund_tokenized(body,
                            expand: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/v1/transactions/cc/refund/token',
                                     Server::DEFAULT)
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(body)
                                .is_required(true))
                   .query_param(new_parameter(expand, key: 'expand'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .body_serializer(proc do |param| param.to_json unless param.nil? end)
                   .auth(And.new('user-id', 'user-api-key', 'developer-id')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(ResponseTransaction.method(:from_hash))
                    .is_api_response(true)
                    .local_error('401',
                                 'Unauthorized',
                                 Response401TokenException)
                    .local_error('412',
                                 'Precondition Failed',
                                 Response412Exception))
        .execute
    end

    # Create a new Wallet Credit Card refund transaction
    # @param [V1TransactionsCcRefundWalletRequest] body Required parameter:
    # TODO: type description here
    # @param [Array[Expand60]] expand Optional parameter: Most endpoints in the
    # API have a way to retrieve extra data related to the current record being
    # retrieved. For example, if the API request is for the accountvaults
    # endpoint, and the end user also needs to know which contact the token
    # belongs to, this data can be returned in the accountvaults endpoint
    # request.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def cc_refund_wallet(body,
                         expand: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/v1/transactions/cc/refund/wallet',
                                     Server::DEFAULT)
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(body)
                                .is_required(true))
                   .query_param(new_parameter(expand, key: 'expand'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .body_serializer(proc do |param| param.to_json unless param.nil? end)
                   .auth(And.new('user-id', 'user-api-key', 'developer-id')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(ResponseTransaction.method(:from_hash))
                    .is_api_response(true)
                    .local_error('401',
                                 'Unauthorized',
                                 Response401TokenException)
                    .local_error('412',
                                 'Precondition Failed',
                                 Response412Exception))
        .execute
    end

    # Create a new keyed Credit Card sale transaction with a non hosted card
    # form. This is an in PCI Scope endpoint and requires PCI compliance
    # verification.
    # @param [V1TransactionsCcSaleKeyedRequest] body Required parameter: TODO:
    # type description here
    # @param [Array[Expand60]] expand Optional parameter: Most endpoints in the
    # API have a way to retrieve extra data related to the current record being
    # retrieved. For example, if the API request is for the accountvaults
    # endpoint, and the end user also needs to know which contact the token
    # belongs to, this data can be returned in the accountvaults endpoint
    # request.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def cc_sale(body,
                expand: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/v1/transactions/cc/sale/keyed',
                                     Server::DEFAULT)
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(body)
                                .is_required(true))
                   .query_param(new_parameter(expand, key: 'expand'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .body_serializer(proc do |param| param.to_json unless param.nil? end)
                   .auth(And.new('user-id', 'user-api-key', 'developer-id')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(ResponseTransaction.method(:from_hash))
                    .is_api_response(true)
                    .local_error('401',
                                 'Unauthorized',
                                 Response401TokenException)
                    .local_error('412',
                                 'Precondition Failed',
                                 Response412Exception))
        .execute
    end

    # Create a new Credit Card sale transaction using previous transaction id
    # @param [V1TransactionsCcSalePrevTrxnRequest] body Required parameter:
    # TODO: type description here
    # @param [Array[Expand60]] expand Optional parameter: Most endpoints in the
    # API have a way to retrieve extra data related to the current record being
    # retrieved. For example, if the API request is for the accountvaults
    # endpoint, and the end user also needs to know which contact the token
    # belongs to, this data can be returned in the accountvaults endpoint
    # request.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def cc_sale_previous_transaction(body,
                                     expand: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/v1/transactions/cc/sale/prev-trxn',
                                     Server::DEFAULT)
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(body)
                                .is_required(true))
                   .query_param(new_parameter(expand, key: 'expand'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .body_serializer(proc do |param| param.to_json unless param.nil? end)
                   .auth(And.new('user-id', 'user-api-key', 'developer-id')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(ResponseTransaction.method(:from_hash))
                    .is_api_response(true)
                    .local_error('401',
                                 'Unauthorized',
                                 Response401TokenException)
                    .local_error('412',
                                 'Precondition Failed',
                                 Response412Exception))
        .execute
    end

    # Create a new swiped Credit Card sale transaction
    # @param [V1TransactionsCcSaleSwipedRequest] body Required parameter: TODO:
    # type description here
    # @param [Array[Expand60]] expand Optional parameter: Most endpoints in the
    # API have a way to retrieve extra data related to the current record being
    # retrieved. For example, if the API request is for the accountvaults
    # endpoint, and the end user also needs to know which contact the token
    # belongs to, this data can be returned in the accountvaults endpoint
    # request.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def cc_sale_swiped(body,
                       expand: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/v1/transactions/cc/sale/swiped',
                                     Server::DEFAULT)
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(body)
                                .is_required(true))
                   .query_param(new_parameter(expand, key: 'expand'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .body_serializer(proc do |param| param.to_json unless param.nil? end)
                   .auth(And.new('user-id', 'user-api-key', 'developer-id')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(ResponseTransaction.method(:from_hash))
                    .is_api_response(true)
                    .local_error('401',
                                 'Unauthorized',
                                 Response401TokenException)
                    .local_error('412',
                                 'Precondition Failed',
                                 Response412Exception))
        .execute
    end

    # Create a new Tap To Pay Credit card sale transaction. Only supported on
    # native iOS integrations.
    # @param [V1TransactionsCcSaleTaptopayRequest] body Required parameter:
    # TODO: type description here
    # @param [Array[Expand60]] expand Optional parameter: Most endpoints in the
    # API have a way to retrieve extra data related to the current record being
    # retrieved. For example, if the API request is for the accountvaults
    # endpoint, and the end user also needs to know which contact the token
    # belongs to, this data can be returned in the accountvaults endpoint
    # request.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def cc_sale_tap_to_pay(body,
                           expand: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/v1/transactions/cc/sale/taptopay',
                                     Server::DEFAULT)
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(body)
                                .is_required(true))
                   .query_param(new_parameter(expand, key: 'expand'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .body_serializer(proc do |param| param.to_json unless param.nil? end)
                   .auth(And.new('user-id', 'user-api-key', 'developer-id')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(ResponseTransaction.method(:from_hash))
                    .is_api_response(true)
                    .local_error('401',
                                 'Unauthorized',
                                 Response401TokenException)
                    .local_error('412',
                                 'Precondition Failed',
                                 Response412Exception))
        .execute
    end

    # Create a new Credit Card Sale for card present EMV transactions using any
    # of the Certified terminals.
    # @param [V1TransactionsCcSaleTerminalRequest] body Required parameter:
    # TODO: type description here
    # @return [ApiResponse] Complete http response with raw body and status code.
    def cc_sale_terminal(body)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/v1/transactions/cc/sale/terminal',
                                     Server::DEFAULT)
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(body)
                                .is_required(true))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .body_serializer(proc do |param| param.to_json unless param.nil? end)
                   .auth(And.new('user-id', 'user-api-key', 'developer-id')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(ResponseTransactionProcessing.method(:from_hash))
                    .is_api_response(true)
                    .local_error('401',
                                 'Unauthorized',
                                 Response401TokenException)
                    .local_error('412',
                                 'Precondition Failed',
                                 Response412Exception))
        .execute
    end

    # Create a new Credit Card Sale using the Ticket_id obtained from the
    # Elements form submission done event.
    # @param [V1TransactionsCcSaleTicketRequest] body Required parameter: TODO:
    # type description here
    # @param [Array[Expand60]] expand Optional parameter: Most endpoints in the
    # API have a way to retrieve extra data related to the current record being
    # retrieved. For example, if the API request is for the accountvaults
    # endpoint, and the end user also needs to know which contact the token
    # belongs to, this data can be returned in the accountvaults endpoint
    # request.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def cc_sale_ticket(body,
                       expand: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/v1/transactions/cc/sale/ticket',
                                     Server::DEFAULT)
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(body)
                                .is_required(true))
                   .query_param(new_parameter(expand, key: 'expand'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .body_serializer(proc do |param| param.to_json unless param.nil? end)
                   .auth(And.new('user-id', 'user-api-key', 'developer-id')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(ResponseTransaction.method(:from_hash))
                    .is_api_response(true)
                    .local_error('401',
                                 'Unauthorized',
                                 Response401TokenException)
                    .local_error('412',
                                 'Precondition Failed',
                                 Response412Exception))
        .execute
    end

    # Create a new Credit Card Sale with a previously created token_id.
    # @param [V1TransactionsCcSaleTokenRequest] body Required parameter: TODO:
    # type description here
    # @param [Array[Expand60]] expand Optional parameter: Most endpoints in the
    # API have a way to retrieve extra data related to the current record being
    # retrieved. For example, if the API request is for the accountvaults
    # endpoint, and the end user also needs to know which contact the token
    # belongs to, this data can be returned in the accountvaults endpoint
    # request.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def cc_sale_tokenized(body,
                          expand: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/v1/transactions/cc/sale/token',
                                     Server::DEFAULT)
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(body)
                                .is_required(true))
                   .query_param(new_parameter(expand, key: 'expand'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .body_serializer(proc do |param| param.to_json unless param.nil? end)
                   .auth(And.new('user-id', 'user-api-key', 'developer-id')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(ResponseTransaction.method(:from_hash))
                    .is_api_response(true)
                    .local_error('401',
                                 'Unauthorized',
                                 Response401TokenException)
                    .local_error('412',
                                 'Precondition Failed',
                                 Response412Exception))
        .execute
    end

    # Create a new Wallet Credit Card sale transaction
    # @param [V1TransactionsCcSaleWalletRequest] body Required parameter: TODO:
    # type description here
    # @param [Array[Expand60]] expand Optional parameter: Most endpoints in the
    # API have a way to retrieve extra data related to the current record being
    # retrieved. For example, if the API request is for the accountvaults
    # endpoint, and the end user also needs to know which contact the token
    # belongs to, this data can be returned in the accountvaults endpoint
    # request.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def cc_sale_wallet(body,
                       expand: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/v1/transactions/cc/sale/wallet',
                                     Server::DEFAULT)
                   .header_param(new_parameter('application/json', key: 'Content-Type'))
                   .body_param(new_parameter(body)
                                .is_required(true))
                   .query_param(new_parameter(expand, key: 'expand'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .body_serializer(proc do |param| param.to_json unless param.nil? end)
                   .auth(And.new('user-id', 'user-api-key', 'developer-id')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(ResponseTransaction.method(:from_hash))
                    .is_api_response(true)
                    .local_error('401',
                                 'Unauthorized',
                                 Response401TokenException)
                    .local_error('412',
                                 'Precondition Failed',
                                 Response412Exception))
        .execute
    end
  end
end
